### ISSUE TITLE
Support import type {} from ""

### ISSUE THREAD

**Issue by deadcoder0904** [codesandbox/codesandbox-client#5316] opened 2020-12-23 06:07 UTC
# 🐛 bug report

## Preflight Checklist

- [x] I have read the
      [Contributing Guidelines](https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md)
      for this project.
- [x] I agree to follow the
      [Code of Conduct](https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md)
      that this project adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem

I want to use `import type {} from ""`

### To Reproduce

1. Open a TS + React project
2. Create `hello.ts` & paste the following:

```ts
export type Hello {
  greet: string;
}
```

3. Open `App.tsx` & insert the following at the top:

```tsx
import type { Hello } from "./hello";
```

It should throw an error `Unexpected token`

**Comment by deadcoder0904** [comment] 2021-01-06 05:19
Nope, I'm not a TS guy..just started using it. But I do use `import type` everywhere to differentiate between normal imports & the ones with types, that's why when I try to copy-paste my code from VSCode to Codesandbox, it throws error

**Comment by SaraVieira** [comment] 2021-01-06 15:13
Oh, gonna ping @christianalfoni since I am not a TS person either

**Comment by KATT** [comment] 2021-02-04 12:51
I'm having the same (I think) issue - see example here https://codesandbox.io/s/github/trpc/trpc/tree/main/examples/next-hello-world?file=/pages/index.tsx

Open the same project in VSCode (also using 4.1.2) and the type inference and export/import work perfectly.

Also, probably unrelated - colours etc is broken [in this file](https://codesandbox.io/s/github/trpc/trpc/tree/main/examples/next-hello-world?file=/pages/api/trpc/%5B...trpc%5D.ts)

**Comment by imrishabh18** [comment] 2021-05-04 20:28
@siddharthkp Is this issue still relevant? Can I look into this?

**Comment by deadcoder0904** [comment] 2021-05-05 06:28
@imrishabh18 Of course, it's relevant :)

**Comment by lbogdan** [comment] 2021-05-25 09:24
Closing this, as it seems to be working in this sandbox: https://codesandbox.io/s/import-type-39ub8 . If this is still an issue for you, please reopen and provide a reproduction sandbox.

**Closed by lbogdan** 2021-05-25 09:24 UTC
Labels: VS Code

**Comment by deadcoder0904** [comment] 2021-05-25 10:25
@lbogdan it works now but it wasn't working early on. I guess you guys must've updated TS now only on Codesandbox :)
