### ISSUE TITLE
'Prettify on Save' replaces 'unique symbol' type to 'keyof symbol'

### ISSUE THREAD

**Issue by tomsiwik** [codesandbox/codesandbox-client#980] opened 2018-07-18 14:29 UTC
## Description of the problem

Using typescript and enabling `Prettify on Save` in the settings causes the editor to autoformat the  `unique` type to an unknown `keyof` on save.

## How has this issue affected you?

I have to disable said feature due to this bug.

###  Link to sandbox: [link](https://codesandbox.io/s/2w32owln6p)

| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  |  PROD-1531843111-627c19c
| Browser | Chrome
| Operating System | Mac

Thanks 👍

**Comment by lbogdan** [comment] 2018-07-18 14:45
Hey @tomsiwik , thanks for your report!

At a quick glance it seems to be caused by [this prettier issue](https://github.com/prettier/prettier/issues/4013), which was fixed with [this PR](https://github.com/prettier/prettier/pull/3967).

We should probably update prettier to a newer version. Cc: @CompuIves .

**Closed as completed** 2018-07-18 23:24 UTC

**Comment by tomsiwik** [comment] 2018-07-20 07:22
Thanks guys :)
