### ISSUE TITLE
使いにくい。萎える

### ISSUE THREAD

**Issue by MasanobuWiz** [codesandbox/codesandbox-client#4323] opened 2020-06-07 21:31 UTC
<h1>💥 Crash Report</h1>

  <h2>What were you trying to accomplish when the crash occurred?</h2>

  > Please use this issue template to describe what you were doing when you encountered this crash. While we are able to fill in some details automatically, it's not always enough to reproduce!

  <h3>Link to sandbox: [link]() (optional)</h3>

  <h3>Crash Details</h3>

  <details>
  <summary>Environment</summary>

  | Browser |  Version  | Operating System | CodeSandbox Version |
  | ------- | --------- | ---------------- | ------------------- |
  | chrome | 83.0.4103 | Windows 10           | 550c67259          |

  **Route:**
  https://codesandbox.io/s/admiring-napier-grkyp?file=/package.json

  </details>

  <details>
  <summary>Error Message</summary>

  ```bash
  NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
  Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at ys (https://codesandbox.io/static/js/common.92a9f0a9c.chunk.js?_sw-precache=afd2ac8c20f60e4ac636224943a7c80c:1:1754640)
    at ms (https://codesandbox.io/static/js/common.92a9f0a9c.chunk.js?_sw-precache=afd2ac8c20f60e4ac636224943a7c80c:1:1752641)
    at ys (https://codesandbox.io/static/js/common.92a9f0a9c.chunk.js?_sw-precache=afd2ac8c20f60e4ac636224943a7c80c:1:1754377)
    at yl (https://codesandbox.io/static/js/common.92a9f0a9c.chunk.js?_sw-precache=afd2ac8c20f60e4ac636224943a7c80c:1:1773642)
    at https://codesandbox.io/static/js/common.92a9f0a9c.chunk.js?_sw-precache=afd2ac8c20f60e4ac636224943a7c80c:1:1795174
    at qo (https://codesandbox.io/static/js/common.92a9f0a9c.chunk.js?_sw-precache=afd2ac8c20f60e4ac636224943a7c80c:1:1719547)
    at bl (https://codesandbox.io/static/js/common.92a9f0a9c.chunk.js?_sw-precache=afd2ac8c20f60e4ac636224943a7c80c:1:1771527)
    at il (https://codesandbox.io/static/js/common.92a9f0a9c.chunk.js?_sw-precache=afd2ac8c20f60e4ac636224943a7c80c:1:1761854)
    at https://codesandbox.io/static/js/common.92a9f0a9c.chunk.js?_sw-precache=afd2ac8c20f60e4ac636224943a7c80c:1:1719838
    at https://codesandbox.io/static/js/common.92a9f0a9c.chunk.js?_sw-precache=afd2ac8c20f60e4ac636224943a7c80c:1:1795174
  
    in elements__Container
    in div
    in Si
    in div
    in Styled(styled.div)
    in li
    in Entry___StyledListAction
    in div
    in n
    in div
    in Unknown
    in DragSource(Component)
    in Unknown
    in div
    in dc
    in div
    in elements__Opener
    in div
    in Unknown
    in DropTarget(Component)
    in div
    in Styled(styled.div)
    in section
    in Styled(styled.div)
    in Unknown
    in Files___StyledCollapsible
    in Ic
    in yl
    in div
    in je
    in Unknown
    in div
    in elements__Container
    in Unknown
    in WithTheme(Component)
    in div
    in t
    in div
    in t
    in div
    in div
    in styled.div
    in div
    in elements__Container
    in je
    in Unknown
    in Unknown
    in Unknown
    in t
    in t
    in div
    in elements__Content
    in n
    in withRouter(n)
    in div
    in elements__Container
    in Unknown
    in withRouter()
    in t
    in Unknown
    in je
    in c
    in t
  ```

  </details>

**Comment by garethx** [comment] 2020-06-08 12:23
@MasanobuWiz What were you trying to accomplish when the crash occurred?

**Comment by lbogdan** [comment] 2020-06-16 12:29
Closing this as duplicate of #4374 .

@MasanobuWiz Please comment on that ^^ issue instead. Thanks!

**Closed by lbogdan** 2020-06-16 12:29 UTC
Labels: Need Info, 💥 Crash Report
