### ISSUE TITLE
Sign in with Github crashed

### ISSUE THREAD

**Issue by lrd373** [codesandbox/codesandbox-client#4614] opened 2020-07-28 18:54 UTC
<h1>💥 Crash Report</h1>

  <h2>What were you trying to accomplish when the crash occurred?</h2>

  >On a premade codesandbox project, I was trying to sign in with Github. I was able to click the "Sign in with Github" button, but the window it opened showed an error.
  <h3>Link to sandbox: "https://codesandbox.io/s/javascript-expressions-in-jsx-practice-completed-ekgvl?fontsize=14&file=/src/index.js"</h3>

  <h3>Crash Details</h3>

  <details>
  <summary>Environment</summary>

  | Browser |  Version  | Operating System | CodeSandbox Version |
  | ------- | --------- | ---------------- | ------------------- |
  | chrome | 84.0.4147 | OS X 10.13.6           | bef7486a2          |

  **Route:**
  https://codesandbox.io/signup/829c5ce8-ed72-49de-8ddb-0e19dc2338b5

  **Error Code:**
7bf3bea079ba412fb5d7ee055e7a7c48

  </details>

  <details>
  <summary>Error Message</summary>

  ```bash
  TypeError: Cannot read property 'location' of null
  TypeError: Cannot read property 'location' of null
    at https://codesandbox.io/static/js/page-signup.b3c225761.chunk.js:1:391
    at ps (https://codesandbox.io/static/js/common.e7a97ddf5.chunk.js?_sw-precache=c00dd7bed9d861d67b93fee2a4434e77:1:1754261)
    at Cl (https://codesandbox.io/static/js/common.e7a97ddf5.chunk.js?_sw-precache=c00dd7bed9d861d67b93fee2a4434e77:1:1779074)
    at https://codesandbox.io/static/js/common.e7a97ddf5.chunk.js?_sw-precache=c00dd7bed9d861d67b93fee2a4434e77:1:1797332
    at qo (https://codesandbox.io/static/js/common.e7a97ddf5.chunk.js?_sw-precache=c00dd7bed9d861d67b93fee2a4434e77:1:1721705)
    at wl (https://codesandbox.io/static/js/common.e7a97ddf5.chunk.js?_sw-precache=c00dd7bed9d861d67b93fee2a4434e77:1:1778835)
    at https://codesandbox.io/static/js/common.e7a97ddf5.chunk.js?_sw-precache=c00dd7bed9d861d67b93fee2a4434e77:1:1778746
    at z (https://codesandbox.io/static/js/common.e7a97ddf5.chunk.js?_sw-precache=c00dd7bed9d861d67b93fee2a4434e77:1:1796713)
    at MessagePort.<anonymous> (https://codesandbox.io/static/js/common.e7a97ddf5.chunk.js?_sw-precache=c00dd7bed9d861d67b93fee2a4434e77:1:1795457)
  
    in i
    in o
    in t
    in t
    in div
    in elements__Content
    in n
    in withRouter(n)
    in div
    in elements__Container
    in Unknown
    in withRouter()
    in t
    in Unknown
    in je
    in c
    in t
  ```

  </details>

**Comment by sannek** [comment] 2020-07-29 15:38
Hi, thanks for your report. That is weird - it looks like something went wrong with completing the sign-up process. Have you since been able to sign up / sign in since, or are you still having problems? 

 I haven't been able to reproduce this error, so it's possible it was just a hiccup on the server, but please let me know if it is still happening to you, so I can investigate further!

**Comment by lrd373** [comment] 2020-07-31 14:46
Hello,

Thank you for looking into this. The issue happened while I was on
codesandbox on Google Chrome. I was only able to successfully sign in via
Github by switching to Firefox.

Recently, however, I've been able to sign in via Github while on Google
Chrome, so hopefully the issue is resolved.

Thanks again!

**Comment by sannek** [comment] 2020-08-03 09:01
Thanks for the update - I'm glad it's working again. I'll close the issue for now, but feel free to reopen if it happens again!

**Closed by sannek** 2020-08-03 09:01 UTC
