### ISSUE TITLE
KhipuCode Web

### ISSUE THREAD

**Issue by khipu-code** [codesandbox/codesandbox-client#4743] opened 2020-08-19 23:22 UTC
<h1>💥 Crash Report</h1>

  <h2>What were you trying to accomplish when the crash occurred?</h2>

  > Please use this issue template to describe what you were doing when you encountered this crash. While we are able to fill in some details automatically, it's not always enough to reproduce!

  <h3>Link to sandbox: [link]() (optional)</h3>

  <h3>Crash Details</h3>

  <details>
  <summary>Environment</summary>

  | Browser |  Version  | Operating System | CodeSandbox Version |
  | ------- | --------- | ---------------- | ------------------- |
  | firefox | 79.0.0 | Ubuntu           | 10e3e21ae          |

  **Route:**
  https://codesandbox.io/s/khipucode-web-official-27574

  **Error Code:**
f09d05d2d47449e98a80ab9e839c71f6

  </details>

  <details>
  <summary>Error Message</summary>

  ```bash
  TypeError: e['angular-config'] is undefined
  getEntries@https://codesandbox.io/static/js/default~app~embed~sandbox.4aaa7a45a.chunk.js:1:21690
i@https://codesandbox.io/static/js/app.f0c727fe2.js:306:780057
./src/app/overmind/index.ts/gu.mainModule<@https://codesandbox.io/static/js/app.f0c727fe2.js:306:631455
runScope@https://codesandbox.io/static/js/vendors~app.96f27b8f8.chunk.js:1:1054955
evaluate@https://codesandbox.io/static/js/vendors~app.96f27b8f8.chunk.js:1:1055391
onFunction@https://codesandbox.io/static/js/vendors~app.96f27b8f8.chunk.js:1:1061174
get@https://codesandbox.io/static/js/vendors~app.96f27b8f8.chunk.js:1:1169608
./src/app/pages/Sandbox/Editor/index.tsx/Fs<@https://codesandbox.io/static/js/app.f0c727fe2.js:306:1013749
ua@https://codesandbox.io/static/js/common.2ec6ed680.chunk.js:1:1772874
Ka@https://codesandbox.io/static/js/common.2ec6ed680.chunk.js:1:1781139
qa@https://codesandbox.io/static/js/common.2ec6ed680.chunk.js:1:1780958
Es@https://codesandbox.io/static/js/common.2ec6ed680.chunk.js:1:1821612
ml@https://codesandbox.io/static/js/common.2ec6ed680.chunk.js:1:1803715
hl@https://codesandbox.io/static/js/common.2ec6ed680.chunk.js:1:1803638
il@https://codesandbox.io/static/js/common.2ec6ed680.chunk.js:1:1800966
$o/<@https://codesandbox.io/static/js/common.2ec6ed680.chunk.js:1:1759149
../../node_modules/react-dom/node_modules/scheduler/cjs/scheduler.production.min.js/t.unstable_runWithPriority@https://codesandbox.io/static/js/common.2ec6ed680.chunk.js:1:1834485
qo@https://codesandbox.io/static/js/common.2ec6ed680.chunk.js:1:1758858
$o@https://codesandbox.io/static/js/common.2ec6ed680.chunk.js:1:1759096
Yo@https://codesandbox.io/static/js/common.2ec6ed680.chunk.js:1:1759029
el@https://codesandbox.io/static/js/common.2ec6ed680.chunk.js:1:1797752
Sa@https://codesandbox.io/static/js/common.2ec6ed680.chunk.js:1:1776549
.forceRerender<@https://codesandbox.io/static/js/vendors~app.96f27b8f8.chunk.js:1:1050314
d/<@https://codesandbox.io/static/js/vendors~app.96f27b8f8.chunk.js:1:1050996
track/this.callback@https://codesandbox.io/static/js/vendors~app.96f27b8f8.chunk.js:1:1172518
flush@https://codesandbox.io/static/js/vendors~app.96f27b8f8.chunk.js:1:1175348
flush@https://codesandbox.io/static/js/vendors~app.96f27b8f8.chunk.js:1:1171572
g/<@https://codesandbox.io/static/js/vendors~app.96f27b8f8.chunk.js:1:1060110
../../node_modules/overmind/es/index.js/o</e.prototype.emit@https://codesandbox.io/static/js/vendors~app.96f27b8f8.chunk.js:1:1053753
createAction/<@https://codesandbox.io/static/js/vendors~app.96f27b8f8.chunk.js:1:1062719
createContext/<.actions</<@https://codesandbox.io/static/js/vendors~app.96f27b8f8.chunk.js:1:1061762
Vd/<@https://codesandbox.io/static/js/app.f0c727fe2.js:306:685430
Vd@https://codesandbox.io/static/js/app.f0c727fe2.js:306:685382
createAction/<@https://codesandbox.io/static/js/vendors~app.96f27b8f8.chunk.js:1:1062652
createContext/<.actions</<@https://codesandbox.io/static/js/vendors~app.96f27b8f8.chunk.js:1:1061762
e/<@https://codesandbox.io/static/js/app.f0c727fe2.js:306:684023
l@https://codesandbox.io/static/js/common-sandbox.26857ffcc.chunk.js:1:255733
i/n._invoke</<@https://codesandbox.io/static/js/common-sandbox.26857ffcc.chunk.js:1:255487
_/</e[o]@https://codesandbox.io/static/js/common-sandbox.26857ffcc.chunk.js:1:256090
t@https://codesandbox.io/static/js/common-sandbox.26857ffcc.chunk.js:1:2405
i@https://codesandbox.io/static/js/common-sandbox.26857ffcc.chunk.js:1:2617

  
    in Unknown
    in div
    in Rs
    in div
    in elements__Opener
    in div
    in Unknown
    in DropTarget(Component)
    in div
    in Rs
    in div
    in elements__Opener
    in div
    in Unknown
    in DropTarget(Component)
    in div
    in Styled(styled.div)
    in section
    in Styled(styled.div)
    in Unknown
    in Files___StyledCollapsible
    in ru
    in au
    in div
    in je
    in Unknown
    in div
    in elements__Container
    in Unknown
    in WithTheme(Component)
    in div
    in t
    in div
    in t
    in div
    in div
    in styled.div
    in div
    in elements__Container
    in je
    in Unknown
    in Unknown
    in Unknown
    in t
    in t
    in div
    in elements__Content
    in n
    in withRouter(n)
    in div
    in elements__Container
    in Unknown
    in withRouter()
    in t
    in Unknown
    in je
    in c
    in t
  ```

  </details>

**Comment by SaraVieira** [comment] 2020-08-31 13:00
Hey!

Can you please provide a sandbox link? The one you used seems to be gone now :(

**Comment by SaraVieira** [comment] 2020-09-28 18:37
Closing for lack of reply and inability to reproduce

**Closed by SaraVieira** 2020-09-28 18:37 UTC
Labels: 💥 Crash Report
