### ISSUE TITLE
CodeSandbox editor interferes with history when using hashes in links.

### ISSUE THREAD

**Issue by StringEpsilon** [codesandbox/codesandbox-client#1811] opened 2019-04-24 19:48 UTC
# 🐛 bug report

## How has this issue affected you? What are you trying to accomplish?

I was diagnosing an issue for react-router when I stumbled into an inconsistency in behavior. I wrongly tried to find the bug in react-router and history, until another user pointed out that the sandboxes I wrote work fine in a separate window.

See:

https://github.com/ReactTraining/react-router/issues/6718

Please also compare the behavior in this sandbox when used in the editor:

https://codesandbox.io/s/z289k0mnmm

And the same sandbox when used in a separate window:

https://z289k0mnmm.codesandbox.io/

Just follow the steps described in the sandbox itself and keep an eye on both the location and the rendered route and the console output. Especially when clicking on the "hash" link.

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | Latest ?
| Browser | Firefox 66
| Operating System | Linux

**Comment by lbogdan** [comment] 2019-04-24 21:43
Closing this as duplicate of #1463 , please subscribe to that instead. Also please re-open if you think it's not really related.

**Closed by lbogdan** 2019-04-24 21:43 UTC
