### ISSUE TITLE
bank

### ISSUE THREAD

**Issue by Nataliia-lab-led** [codesandbox/codesandbox-client#7309] opened 2023-01-12 14:26 UTC
<h1>💥 Crash Report</h1>

  <h2>What were you trying to accomplish when the crash occurred?</h2>

  > Please use this issue template to describe what you were doing when you encountered this crash. While we are able to fill in some details automatically, it's not always enough to reproduce!

  <h3>Link to sandbox: [link]() (optional)</h3>

  <h3>Crash Details</h3>

  <details>
  <summary>Environment</summary>

  | Browser |  Version  | Operating System | CodeSandbox Version |
  | ------- | --------- | ---------------- | ------------------- |
  | chrome | 108.0.0 | Windows 10           | 5a5e5ae51          |

  **Route:**
  https://codesandbox.io/s/vigilant-fast-zv7feb

  **Error Code:**
261ceb33f7034a01b1c1e4d7eb0a8cc0

  </details>

  <details>
  <summary>Error Message</summary>

  ```bash
  NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
  Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at ys (https://codesandbox.io/static/js/common.8b1ec1d2a.chunk.js:1:1820053)
    at yl (https://codesandbox.io/static/js/common.8b1ec1d2a.chunk.js:1:1839037)
    at t.unstable_runWithPriority (https://codesandbox.io/static/js/common.8b1ec1d2a.chunk.js:1:1860569)
    at qo (https://codesandbox.io/static/js/common.8b1ec1d2a.chunk.js:1:1784942)
    at bl (https://codesandbox.io/static/js/common.8b1ec1d2a.chunk.js:1:1836922)
    at il (https://codesandbox.io/static/js/common.8b1ec1d2a.chunk.js:1:1827249)
    at https://codesandbox.io/static/js/common.8b1ec1d2a.chunk.js:1:1785233
    at t.unstable_runWithPriority (https://codesandbox.io/static/js/common.8b1ec1d2a.chunk.js:1:1860569)
    at qo (https://codesandbox.io/static/js/common.8b1ec1d2a.chunk.js:1:1784942)
    at Xo (https://codesandbox.io/static/js/common.8b1ec1d2a.chunk.js:1:1785178)
    at Yo (https://codesandbox.io/static/js/common.8b1ec1d2a.chunk.js:1:1785113)
    at se (https://codesandbox.io/static/js/common.8b1ec1d2a.chunk.js:1:1854321)
    at Sn (https://codesandbox.io/static/js/common.8b1ec1d2a.chunk.js:1:1768739)
  
    in button
    in styled.div
    in ForwardRef
    in ForkButton___StyledButton
    in div
    in Styled(styled.div)
    in ia
    in _a
    in div
    in Actions___StyledStack
    in za
    in header
    in Header___StyledStack
    in Jo
    in De
    in Unknown
    in div
    in elements__Container
    in De
    in fy
    in Unknown
    in Unknown
    in t
    in t
    in div
    in elements__Content
    in n
    in withRouter(n)
    in div
    in elements__Container
    in Unknown
    in withRouter()
    in t
    in Unknown
    in De
    in c
    in t
  ```

  </details>

**Comment by DeMoorJasper** [comment] 2023-01-16 09:14
This sandbox no longer exists, so can't reproduce it anymore, closing for now, feel free to let us know how to reproduce this issue and we'll reopen it

**Closed by DeMoorJasper** 2023-01-16 09:14 UTC
