### ISSUE TITLE
Could not find package.json

### ISSUE THREAD

**Issue by devdjdjdj** [codesandbox/codesandbox-client#4107] opened 2020-05-10 17:04 UTC
# 🐛 bug report

## Description of the problem
I am getting error message - 
Could not find package.json

## How has this issue affected you? What are you trying to accomplish?
Not able to create sandbox. The package.json file exists in the repo.

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | --
| Browser          | Chrome and Firefox |
| Operating System | Mac OS Catalina 10.15.3|

**Comment by SaraVieira** [comment] 2020-05-10 17:27
Hey!

The issue is we can't tell what is your default branch on github and we always default to master, in your case your default branch is `develop` and your master branch does not have any package.json in it so we give you an error.

It's completely possible to open the develop branch like:

https://codesandbox.io/s/github/devdjdjdj/kibana-presenter/tree/develop

When you do that all works as expected :)

Sorry for the trouble

I am gonna close the issue let me know if you find any more issues and you are welcome to re open it

**Closed by SaraVieira** 2020-05-10 17:27 UTC
