### ISSUE TITLE
Vue template fails with codesandbox-ci dependencies.

### ISSUE THREAD

**Issue by jansiegel** [codesandbox/codesandbox-client#4593] opened 2020-07-23 07:40 UTC
# 🐛 bug report

## Description of the problem
It seems like the default Vue template doesn't work with dependencies built by the Codesandbox CI. 

The `Transpiling Modules` screen goes on for some time, and it ends with this error:
```
[BABEL] /src/main.js: Unexpected token ; in JSON at position 12 (While processing: "base$0")
```

It looks like it's caused by `@vue/cli-plugin-babel` - when I remove it from the dependencies, the problem goes away.

### Link to sandbox: 
Sandboxes with 2 unrelated libraries hosted on `pkg.csb.dev`:
- https://codesandbox.io/s/elastic-sara-6tw25?file=/package.json
- https://codesandbox.io/s/magical-smoke-4w596?file=/package.json

without `@vue/cli-plugin-babel` (works alright):
- https://codesandbox.io/s/competent-sun-3u0h9?file=/package.json

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | ?
| Browser          | Tested on Chrome, Firefox and Safari
| Operating System | macOS 10.15.5

**Comment by CodeSandboxNotifications** [comment] 2020-09-28 13:33
Hello Jan,


Apologies for the late reply!! I completely missed this. Last week we released Vue 3, and with that I did some optimizations to Vue 2 as well. When checking your examples they all seem to work fast now.
Again, apologies for the late reply, please let me know if you still see sandboxes which are slow!


Ives



--- original message ---
On July 23, 2020, 9:41 AM GMT+2 notifications@github.com wrote:



🐛 bug report

Description of the problem

It seems like the default Vue template doesn't work with dependencies built by the Codesandbox CI.

The Transpiling Modules screen goes on for some time, and it ends with this error:

[BABEL] /src/main.js: Unexpected token ; in JSON at position 12 (While processing: "base$0")

It looks like it's caused by @vue/cli-plugin-babel - when I remove it from the dependencies, the problem goes away.

Link to sandbox:

Sandboxes with 2 unrelated libraries hosted on pkg.csb.dev:

https://codesandbox.io/s/elastic-sara-6tw25?file=/package.json

https://codesandbox.io/s/magical-smoke-4w596?file=/package.json


without @vue/cli-plugin-babel (works alright):

https://codesandbox.io/s/competent-sun-3u0h9?file=/package.json


Your Environment
Software Name/Version 
Сodesandbox ? 
Browser Tested on Chrome, Firefox and Safari 
Operating System macOS 10.15.5 


—

You are receiving this because you are subscribed to this thread.

Reply to this email directly, view it on GitHub, or unsubscribe.
--- end of original message ---

**Comment by SaraVieira** [comment] 2020-09-28 17:38
Closing as all seems to work now, please feel free to reopen if you are still having issues

**Closed by SaraVieira** 2020-09-28 17:38 UTC
