### ISSUE TITLE
Can't move sandbox from "My Drafts" to "All Sandboxes"

### ISSUE THREAD

**Issue by nhevia** [codesandbox/codesandbox-client#4629] opened 2020-08-02 14:28 UTC
# 🐛 bug report

## Description of the problem
When trying to move an already created sandbox inside "My Drafts" folder (which is the default behaviour when you press "Create Sandbox") to another folder in "All Sandboxes" (or said root folder), UI refreshes the change but the sandbox stays in Draft.

![example gif](https://i.imgur.com/4V7aYvg.gif)

## How has this issue affected you? What are you trying to accomplish?
All my sandboxes are inside Draft folder. I can't organize them.

### Link to sandbox: [link]() (optional)
https://codesandbox.io/s/react-router-dynamic-link-w8il9

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |
| Browser          | Chrome 84.0 & Firefox 79.0
| Operating System | Windows 10

**Comment by nolakat** [comment] 2020-08-09 15:01
I am having the same issue. 

It is effecting all of my sandboxes. I am trying to gather all of my examples into a single folder for my team, but the sandboxes remain in the 'Drafts' area no matter what I do.

Browser - Chrome 84.0
Operating System - Mojave 10.14

**Comment by CompuIves** [comment] 2020-08-11 12:28
Hey! I now see what the issue is. Because we're in the middle of an unfinished transition to workspaces, it's not possible to move sandboxes to "All Sandboxes" in your Personal workspace. It actually does work for teams. We're in the process of making the transition right now, so I'm expecting that this will be no problem soon, but in the meantime, we should disable the button. I will do that!

**Comment by siddharthkp** [comment] 2020-08-19 10:57
The PR that adds a warning is merged, which clears up the confusion :)

@sannek is already deep in the transition which will allow sandboxes in All sandboxes for personal workspaces (not just teams)

Closing this issue, keep an eye on the changelog 😉

**Closed by siddharthkp** 2020-08-19 10:57 UTC
