### ISSUE TITLE
CodeSandbox is trying to fetch JSDelivr URL with missing `version` variable

### ISSUE THREAD

**Issue by wojciechczerniak** [codesandbox/codesandbox-client#3203] opened 2019-12-13 15:17 UTC
# 🐛 bug report

## Description of the problem
CodeSandbox is trying to fetch JSDelivr URL with missing `version` variable:
`https://cdn.jsdelivr.net/npm/voc@/package.json`

![Screenshot 2019-12-13 at 16 06 14](https://user-images.githubusercontent.com/4718998/70809952-2b451f80-1dc3-11ea-8e5d-7012d851f77f.png)

Looks like a dependency version wasn't parsed correctly.

## How has this issue affected you? What are you trying to accomplish?
I'm trying to add CodeSanbox CI to Handsontable repo https://github.com/handsontable/handsontable/pull/6565

The build is successful. Looks like sandboxes are created OK. The package looks OK.

Opening the sandbox result in an error.

### Link to sandbox: 
Broken CI build:

https://codesandbox.io/s/focused-silence-pq0ed

which is forked from a working example:

https://codesandbox.io/s/github/handsontable/examples/tree/master/vanilla/basic

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | https://codesandbox.io/s/focused-silence-pq0ed
| Browser          |  70.0.1
| Operating System | OS X 10.15

**Comment by lbogdan** [comment] 2020-01-31 20:49
Hey @wojciechczerniak ,

Is this still an issue for you? I've seen that the sandboxes generated by the latest builds work fine, for example https://codesandbox.io/s/distracted-sara-rtji1 .

**Comment by wojciechczerniak** [comment] 2020-02-01 10:19
Hi @lbogdan,

We've fixed our deps. The problem and solution are explained here https://github.com/handsontable/handsontable/pull/6565#issuecomment-569257118 

It may still exist in CodeSandbox CI and will affect someone else.

**Comment by SaraVieira** [comment] 2020-09-03 13:45
I am closing this as it seems the issue is fixed.

If anyone else experiences this issue please feel free to reopen :)

**Closed by SaraVieira** 2020-09-03 13:45 UTC
Labels: CodeSandbox CI, Need Info
