### ISSUE TITLE
sandbox crashed when I tried to acess the console to see my output, now all the code I wrote is gone!

### ISSUE THREAD

**Issue by bhavya00001** [codesandbox/codesandbox-client#7715] opened 2023-07-05 15:11 UTC
<h1>💥 Crash Report</h1>

  <h2>What were you trying to accomplish when the crash occurred?</h2>

  > Please use this issue template to describe what you were doing when you encountered this crash. While we are able to fill in some details automatically, it's not always enough to reproduce!

  <h3>Link to sandbox: [link]() (optional)</h3>

  <h3>Crash Details</h3>

  <details>
  <summary>Environment</summary>

  | Browser |  Version  | Operating System | CodeSandbox Version |
  | ------- | --------- | ---------------- | ------------------- |
  | chrome | 114.0.0 | Windows 10           | 62a3c50a7          |

  **Route:**
  https://codesandbox.io/s/javascript-expressions-in-jsx-practice-forked-f9dtvj?file=/src/index.js

  **Error Code:**
34bc0832d3194216922300aeb3d6c1ae

  </details>

  <details>
  <summary>Error Message</summary>

  ```bash
  TypeError: Cannot read properties of undefined (reading 'indexOf')
  TypeError: Cannot read properties of undefined (reading 'indexOf')
    at https://codesandbox.io/static/js/common.9637ade4f.chunk.js?_sw-precache=4551204809953157d4547cf63bb60811:1:640448
    at ua (https://codesandbox.io/static/js/common.9637ade4f.chunk.js?_sw-precache=4551204809953157d4547cf63bb60811:1:1791394)
    at xs (https://codesandbox.io/static/js/common.9637ade4f.chunk.js?_sw-precache=4551204809953157d4547cf63bb60811:1:1836476)
    at ml (https://codesandbox.io/static/js/common.9637ade4f.chunk.js?_sw-precache=4551204809953157d4547cf63bb60811:1:1822080)
    at hl (https://codesandbox.io/static/js/common.9637ade4f.chunk.js?_sw-precache=4551204809953157d4547cf63bb60811:1:1822005)
    at il (https://codesandbox.io/static/js/common.9637ade4f.chunk.js?_sw-precache=4551204809953157d4547cf63bb60811:1:1819353)
    at https://codesandbox.io/static/js/common.9637ade4f.chunk.js?_sw-precache=4551204809953157d4547cf63bb60811:1:1777795
    at https://codesandbox.io/static/js/common.9637ade4f.chunk.js?_sw-precache=4551204809953157d4547cf63bb60811:1:1852777
    at qo (https://codesandbox.io/static/js/common.9637ade4f.chunk.js?_sw-precache=4551204809953157d4547cf63bb60811:1:1777504)
    at Xo (https://codesandbox.io/static/js/common.9637ade4f.chunk.js?_sw-precache=4551204809953157d4547cf63bb60811:1:1777740)
    at Yo (https://codesandbox.io/static/js/common.9637ade4f.chunk.js?_sw-precache=4551204809953157d4547cf63bb60811:1:1777675)
    at el (https://codesandbox.io/static/js/common.9637ade4f.chunk.js?_sw-precache=4551204809953157d4547cf63bb60811:1:1816142)
    at Object.enqueueSetState (https://codesandbox.io/static/js/common.9637ade4f.chunk.js?_sw-precache=4551204809953157d4547cf63bb60811:1:1782456)
    at n.setState (https://codesandbox.io/static/js/common.9637ade4f.chunk.js?_sw-precache=4551204809953157d4547cf63bb60811:1:2035462)
    at n.value (https://codesandbox.io/static/js/default~app~embed.c643de405.chunk.js?_sw-precache=c85ace3cd9ef7eb65c38e89d5988b4e8:605:33196)
    at Object.<anonymous> (https://codesandbox.io/static/js/default~app~embed.c643de405.chunk.js?_sw-precache=c85ace3cd9ef7eb65c38e89d5988b4e8:605:31616)
    at https://codesandbox.io/static/js/default~app~embed~sandbox~sandbox-startup.b2134d8a8.chunk.js:1:6731
    at Array.forEach (<anonymous>)
    at A (https://codesandbox.io/static/js/default~app~embed~sandbox~sandbox-startup.b2134d8a8.chunk.js:1:6694)
    at P (https://codesandbox.io/static/js/default~app~embed~sandbox~sandbox-startup.b2134d8a8.chunk.js:1:6903)
  
    in Unknown
    in bound 
    in div
    in li
    in Unknown
    in Unknown
    in ol
    in Unknown
    in he
    in t
    in Ie
    in div
    in Styled(div)
    in t
    in WithTheme(t)
    in t
    in WithTheme(t)
    in div
    in Styled(div)
    in div
    in Styled(div)
    in v
    in t
    in div
    in Styled(div)
    in v
    in t
    in div
    in elements__Messages
    in div
    in elements__Container
    in n
    in WithTheme(n)
    in div
    in elements__ContentContainer
    in div
    in elements__Container
    in n
    in div
    in div
    in t
    in div
    in t
    in div
    in De
    in on
    in div
    in t
    in div
    in t
    in div
    in div
    in styled.div
    in div
    in elements__Container
    in De
    in Ry
    in Unknown
    in Unknown
    in t
    in t
    in div
    in elements__Content
    in n
    in withRouter(n)
    in div
    in elements__Container
    in Unknown
    in withRouter()
    in t
    in Unknown
    in De
    in c
    in t
  ```

  </details>

**Comment by CompuIves** [comment] 2023-09-11 09:35
Hey! Thanks for reporting this, it looks like this happened because of an upgrade we did to the console-feed package. Whenever we had to print an Error without a stack-trace to the console, the component would crash. We've now reverted that update, so it should not happen again. In the upcoming weeks we're going to replace our console solution with a version that's powered by Chrome Devtools, so that will be a big upgrade when it comes to our logging experience, and will result in a more stable experience.

I'm really sorry for the inconvenience, we've now pinned the version of console-feed in the meantime to make sure this won't happen again, so the issue is fixed now.

**Closed by CompuIves** 2023-09-11 09:35 UTC
