### ISSUE TITLE
TypeError: _typeof is not a function

### ISSUE THREAD

**Issue by declan-warn** [codesandbox/codesandbox-client#5580] opened 2021-03-10 23:27 UTC
# 🐛 bug report

## Preflight Checklist

- [x] I have read the
      [Contributing Guidelines](https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md)
      for this project.
- [x] I agree to follow the
      [Code of Conduct](https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md)
      that this project adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem

Many examples are showing the following error **only on CodeSandbox**:
![image](https://user-images.githubusercontent.com/9005422/110708262-88da4d00-824e-11eb-9921-805f93999a14.png)
```
TypeError
_typeof is not a function
```

For some examples the error is always present, and for others only when interacting with the example. Fiddling around with the dependencies, sometimes by adding `@babel/runtime`, can fix these issues.

This issue could potentially be related, but has not fixed this issue: https://github.com/codesandbox/codesandbox-client/issues/5541

Further information in reproduction section.

## How has this issue affected you? What are you trying to accomplish?

The sandbox is rendered completely unusable.

#### Observations:
* clicking a toggle will crash the sandbox
* manually adding `@babel/runtime` as a dependency (latest version) fixes this
* downgrading `@atlaskit/toggle` to the previous version also fixes this, although [nothing has changed that should cause this](https://diff.intrinsic.com/@atlaskit/toggle/12.0.3/12.0.4)

#### Observations:
* the sandbox is always crashed
* removing either `@atlaskit/css-reset` or `@atlaskit/theme` will fix this
  * **neither has been updated in 4 months and this issue is only appearing within the last week or so**
* downgrading `@atlaskit/logo` to the previous version also fixes this

## Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| СodeSandbox      | latest
| Browser          | Chrome 89.0.4389.82
| Browser          | Firefox 86.0
| Operating System | MacOS Catalina 10.15.7

**Comment by declan-warn** [comment] 2021-03-12 00:44
Here is [another example](https://codesandbox.io/s/84j0g?module=/example.tsx) where manually adding `@babel/runtime` will fix the error.

Interestingly only version `^7.13.0` will fix the issue. Considering `@atlaskit` packages do not use version `^7.13.0` this definitely seems CodeSandbox specific.

**Comment by declan-warn** [comment] 2021-03-12 02:20
Adding `typescript` as a devDependency also fixes some of the issues.

**Comment by CompuIves** [comment] 2021-03-12 20:29
I've noticed this as well, seems like something broke with a recent update in @babel/runtime, looking into it...

**Comment by CompuIves** [comment] 2021-03-12 21:03
Found the problem! Just committed a fix that should be live in ~20min

**Closed** 2021-03-12 21:02 UTC

**Comment by sarah-koehler** [comment] 2021-03-18 16:46
I still have a Codesandbox with this error caused by a class component:

- It was created from a very small CRA project that is only a few weeks old.
- I updated the dependencies and recreated the Sandbox, but I still get the same error.
- I added @babel/runtime and typescript as (dev) dependencies

Here is the minimal Sandbox: https://codesandbox.io/s/typeof-is-not-a-function-minimal-5hgxz

The only way to fix it seems to be to change the class component to a function component.

**Comment by cahna** [comment] 2021-03-23 21:52
I was seeing the same as @sarah-koehler. For TypeScript, functional components work, but class components show `_typeof is not a function`.

Via trial and error, I was able to fix this by:
- moving `@testing-library/*` and all `@types/*` dependencies explicitly into `devDependencies`
- `jest` must stay in `dependencies` or other errors would occur
- Add `"exclude": ["node_modules"]` in `tsconfig.json`

I did *not* need to add `@babel/runtime`. I do not know why this worked :shrug:

**Comment by cahna** [comment] 2021-03-23 22:03
@sarah-koehler, if I remove `@testing-library/jest-dom` from your sandbox, it works, too. :man_shrugging:

**Comment by cahna** [comment] 2021-03-23 22:18
It appears that `@testing-library/jest-dom` >= `5.0.0` causes this problem. Using `4.2.4` works.

**Comment by sarah-koehler** [comment] 2021-03-24 08:13
Thank you @cahna! I can confirm that downgrading @testing-library/jest-dom to 4.2.4 works for me and fixes the issue with my sandbox.
