### ISSUE TITLE
[Bug] DependencyNotFoundError

### ISSUE THREAD

**Issue by fantasticsoul** [codesandbox/codesandbox-client#6289] opened 2021-11-17 11:51 UTC
# 🐛 bug report

## Description of the problem

DependencyNotFoundError
Could not find dependency: 'utils' relative to '/src/models/counter/reducer.js'

it seems the configs below not work( but is works before)
```
"compilerOptions": {
    "baseUrl": "src",
    "experimentalDecorators":true
  }
```

## Link
https://codesandbox.io/s/xvcej

**Comment by DeMoorJasper** [comment] 2021-11-17 11:53
duplicate of #6286

**Closed by DeMoorJasper** 2021-11-17 11:53 UTC
