### ISSUE TITLE
Jest tests not working in basic new sandbox.

### ISSUE THREAD

**Issue by Neutrino-Sunset** [codesandbox/codesandbox-client#4872] opened 2020-09-09 20:37 UTC
## Description of the problem

Jest tests do not work as described in the documentation [here](https://codesandbox.io/docs/tests)

## How has this issue affected you? What are you trying to accomplish?

I'm trying to run a test and it isn't being detected.

### To Reproduce

Create a sandbox using the official Vanilla JS template.
Add a Javascript file named <whatever>.test.js containing a test.

### Expected

The test should be detected and run.

### Actual

Nothing happens at all.

### Link to sandbox: [link]() (optional)

https://codesandbox.io/s/import-tests-ci7zc

The sandbox looks screwed up to me. I created it from the VanillaJS template but the Sandbox Info pane suggests it's come from the Node HTTP Server template, and the Server Control Panel pane suggests it's running in a server container. But the sandbox has a plain index.js that was generated by the template.

Makes no sense to me at all.

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |  Where would I get that from?
| Browser          |     Firefox 80.0.1
| Operating System |   Win 10

**Comment by Neutrino-Sunset** [comment] 2020-09-09 20:40
Here's a sandbox that does actually recognise what template it came from, same issue. No tests.

https://codesandbox.io/s/recursing-beaver-mzv32

**Comment by SaraVieira** [comment] 2020-09-09 21:15
Hey!

There seems to have been an issue with the first one since at the moment we do not support tests in node sandboxes

In the second one, you mentioned the tests do appear
![CleanShot 2020-09-09 at 23 15 37](https://user-images.githubusercontent.com/1051509/92655895-617fe300-f2f2-11ea-80f5-af4e077e49d0.png)

**Comment by SaraVieira** [comment] 2020-09-09 21:16
The first one does have nodemon as a dependency so I think we got the fact it was a node sandbox from there

**Comment by Neutrino-Sunset** [comment] 2020-09-10 09:24
The point about the first sandbox though was that I created it from the VanillaJS template. How it ended up as a Node Server with an index.html I have no idea.

Does the second sandbox work for you in Firefox? For me it works on Chrome (tests appear and run), does not work on Firefox, tested on two machines with Firefox 80.0.1 in safe mode.

![image](https://user-images.githubusercontent.com/18445931/92710508-c584c480-f34f-11ea-8cf3-a4c5dda3008a.png)

**Comment by SaraVieira** [comment] 2020-09-10 09:47
The only explanation I have is that you must have created a sandbox from node instead of vanilla since it contains all the files and dependencies of the normal node sandbox you can see here: https://codesandbox.io/s/node

About the other issue, we are aware and it's in our backlog to fix as of today the tests do not work on Firefox and you can see the explanation here: https://github.com/codesandbox/codesandbox-client/issues/4303#issuecomment-688178497

Closing this issue as it is a duplicate of the issue mentioned above, please follow that issue for updates
https://github.com/codesandbox/codesandbox-client/issues/4303

**Closed by SaraVieira** 2020-09-10 09:47 UTC
