### ISSUE TITLE
Parsing error: Unexpected token (null) eslint

### ISSUE THREAD

**Issue by tony19** [codesandbox/codesandbox-client#5275] opened 2020-12-13 07:29 UTC
# 🐛 bug report

## Preflight Checklist

- [x] I have read the
      [Contributing Guidelines](https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md)
      for this project.
- [x] I agree to follow the
      [Code of Conduct](https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md)
      that this project adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem

The editor is showing an `unexpected token` error when typing `return {}` in this code:

```js
export default {
  name: "App",
  components: {
    HelloWorld,
  },
  data() {
    return {};  // ❌ Parsing error: unexpected token } (null) eslint
  },
};
```

<img width="562" alt="Screen Shot 2020-12-13 at 1 20 12 AM" src="https://user-images.githubusercontent.com/26580/102005823-96307b80-3ce1-11eb-8dd3-333dae8c84ec.png">

## How has this issue affected you? What are you trying to accomplish?

It obfuscates actual errors in the editor, which reduces productivity.

### To Reproduce

 1. Open https://codesandbox.io/s/vue
 2. In `src/App.vue`, add:

    ```js
    data() {
      return {}
    }
    ```

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | `02ccdad34`|
| Browser          | Chrome Version 87.0.4280.88 (Official Build) (x86_64)|
| Operating System | macOS Big Sur |

**Comment by pahund** [comment] 2020-12-13 10:01
I have also observed this problem, was about to create a bug ticket of my own. 

It seems ESLint validation occurs with every keystroke, even if autosave is off. So when a statement is typed halfway, ESLint immediately complains about incorrect syntax. When I'm finished typing the statement and the syntax is now correct, the ESLint error message persists. It will only go away when closing the file and opening it again. 

I've been working with CodeSandbox every day for the last two weeks. This issue has started occurring 2-3 days ago, around 11th December.

It currently makes working with CodeSandbox very annoying, to the point that I'm considering switching to another editor. In my opinion, this is a high priority issue.

**Comment by pahund** [comment] 2020-12-13 10:07
Here is a screen recording I've made that show the issue: https://youtu.be/PZ_KIUlNTb4

**Comment by SaraVieira** [comment] 2020-12-13 16:15
Hey!

There seems to be an issue right now with our eslint, seems delayed and behaving kinda weird, we will take a look on Monday

**Comment by pahund** [comment] 2020-12-14 08:24
Thank you! Keep up the good work! 😀

**Comment by SaraVieira** [comment] 2020-12-14 11:07
Morning!

This seems to be fixed now, can I get a confirmation on that?

**Comment by pahund** [comment] 2020-12-14 11:28
@SaraVieira Yes, I can confirm that it is fixed – thank you for the quick response!

**Comment by SaraVieira** [comment] 2020-12-14 11:28
Nice! Closing 🎉

**Comment by tony19** [comment] 2020-12-15 21:53
While the issue seems resolved in Vue files, the problem still occurs in `.js` files [(demo)](https://codesandbox.io/s/using-class-instance-as-data-prop-in-vue-hk0lb?file=/src/MyClass.js).

**Comment by SaraVieira** [comment] 2020-12-16 13:37
Hey!


Do you have a sandbox you can send me?

**Comment by tony19** [comment] 2020-12-16 14:00
https://codesandbox.io/s/using-class-instance-as-data-prop-in-vue-hk0lb?file=/src/MyClass.js

**Comment by SaraVieira** [comment] 2020-12-16 14:06
You are super right, looping this back to @CompuIves

**Comment by CompuIves** [comment] 2020-12-16 14:13
This seems related to the parser of eslint, I think it might be outdated and it doesn't support parsing class instance fields with default initializers.

**Comment by tony19** [comment] 2021-01-03 23:35
I'm seeing this ESLint error in the Vue template again:

[Sandbox link](https://codesandbox.io/s/sleepy-mountain-wg0bi?file=/src/App.vue)

<img width="1288" alt="Screen Shot 2021-01-03 at 5 34 18 PM" src="https://user-images.githubusercontent.com/26580/103491494-f0f15a80-4de9-11eb-81ba-0ef5e479ee3d.png">

**Comment by pahund** [comment] 2021-02-25 14:55
The issue had been fixed, at least for me, previously, but unfortunately, it is now back with a vengeance. I have to frequently hit browser reload to get rid of the “(null) aslant” error that keeps popping up.

Example sandbox: https://codesandbox.io/s/remotion-car-slideshow-006-0y9p7?file=/src/App.tsx

https://user-images.githubusercontent.com/1639313/109171168-c97f9400-7781-11eb-9ad2-73db5a9c6f84.mov

**Comment by Rishabhk06** [comment] 2021-02-26 08:36
yes it is appearing constantly..

**Comment by pahund** [comment] 2021-02-26 14:31
@SaraVieira @CompuIves 

In my humble opinion, this is a top priority issue. Major functionality is broken. At this point, you can't edit a file in CodeSandbox without constantly getting these bogus ESLint errors.

**Comment by CompuIves** [comment] 2021-02-26 14:35
Hmm, interesting, I can repro this as well. We haven't changed anything related to eslint recently, going to take a look. I agree that this obfuscates a lot of errors.

**Comment by CompuIves** [comment] 2021-02-26 14:46
Fix should be live in 20 minutes!

**Closed** 2021-02-26 14:45 UTC

**Comment by tony19** [comment] 2021-02-26 17:30
@CompuIves Thanks for the fix. However, I can still reproduce the error in two of the links I posted originally above:

 * https://codesandbox.io/s/sleepy-mountain-wg0bi?file=/src/App.vue
 * https://codesandbox.io/s/using-class-instance-as-data-prop-in-vue-hk0lb?file=/src/MyClass.js

**Comment by pahund** [comment] 2021-03-02 09:19
I can confirm that the issue has been fixed, for me at least. Thanks!

**Comment by kumiega** [comment] 2021-03-05 13:27
I made my own sandbox where I tried to reproduce my problem with Vite and the same problem still occurs. What can I do?

**Comment by andrasbacsai** [comment] 2021-03-25 13:04
Can you please open a different issue for that with all the details? Thanks in advance!

**Comment by picasocro1** [comment] 2021-09-23 20:37
I experience this problem trying use TS types in **any Vue3 with TS repo**.

![image](https://user-images.githubusercontent.com/24699593/134580174-ee53df9f-3114-4e29-8fa7-18914e9232a5.png)

For example using this template:
https://codesandbox.io/s/vue3-ts-template-s4fff

It's really irritating :(

**Comment by kendallroth** [comment] 2021-12-01 17:11
Does this have anything to do with the VueJS docs now recomending the **Volar** extension instead of Vetur for Vue 3? At this point I was sure I had configured CodeSandbox correctly, but I keep getting this `Unexpected token: (null)` error whenever I try to use TS with Vue 3.

**Comment by tony19** [comment] 2021-12-01 20:06
@kendallroth This was an issue long before Vue 3, so I don't think that has anything to do with it. And TypeScript isn't needed to reproduce the problem.

Based on https://github.com/codesandbox/codesandbox-client/issues/5275#issuecomment-746352268, it sounds like the ESLint parser used in Codesandbox is outdated.

**Comment by may17** [comment] 2022-02-19 14:15
@CompuIves looks like there is still a problem with used eslint parser as @tony19 mentioned. Are there any plans to fix that cause this is a little bit weird. Got the problem in vue 3 projects.

**Comment by Osmon11** [comment] 2023-10-22 10:22
facing the same issue
