### ISSUE TITLE
Need to use Package.default to get the default export

### ISSUE THREAD

**Issue by nikgraf** [codesandbox/codesandbox-client#2976] opened 2019-11-04 23:39 UTC
# 🐛 bug report

## Description of the problem

I published a small package using `tsdx`. I used it inside create-react-app for verification and then wanted to create a shareable CodeSandbox example.

I noticed somehow CodeSandbox does something unexpected. I need to `GraphiQlSpark.default` to get the default export. I wonder why this is the case.

## How has this issue affected you? What are you trying to accomplish?

I'm wondering if I do something wrong or the CodeSandbox bundler. It shouldn't be needed.

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | PROD-1572624626-def377908
| Browser          | Chrome
| Operating System | OSX

**Comment by lbogdan** [comment] 2020-01-31 19:26
Hey @nikgraf ,

That's because we (still) prefer `main` (which is CJS) over `module`, and because of the CJS-ESM interop, it has the default export on `exports.default` - see the last line of https://unpkg.com/browse/graphiql-spark@0.1.0/dist/graphiql-spark.cjs.development.js :
```
[...]
exports.default = GraphiQLSpark;
```

As the root cause of this is basically a duplicate of #3305 , I'm going to close it for now, please subscribe to that one if you want to follow progress.

**Closed by lbogdan** 2020-01-31 19:26 UTC
Labels: bug?, 🎒 Bundler

**Comment by nikgraf** [comment] 2020-02-03 05:43
Thanks for the clarification
