### ISSUE TITLE
3 max big cubes animation

### ISSUE THREAD

**Issue by IPR-Kaspar** [codesandbox/codesandbox-client#2775] opened 2019-10-14 13:22 UTC
# 🐛 bug report

![image](https://user-images.githubusercontent.com/54580256/66754377-81b6e000-ee9e-11e9-9550-31379fb5a60a.png)

## Description of the problem

Does it suppose to have 3 max big cubes? Or it's a feature? :)
It happened after clicking the smaller and avoid hover over big ones.

## How has this issue affected you? What are you trying to accomplish?

Perfectionism

### Link to sandbox: [link]() (optional)

https://codesandbox.io/

### Your Environment

Windows 10 latest, Chrome latest

**Comment by lbogdan** [comment] 2019-10-18 13:16
Closing as duplicate of #452 . We're also working on a new homepage, which will hopefully be *more perfect* than the current one. 🙂

**Closed by lbogdan** 2019-10-18 13:16 UTC
