### ISSUE TITLE
CodeSandBox Favicon

### ISSUE THREAD

**Issue by lifeiscontent** [codesandbox/codesandbox-client#1775] opened 2019-04-16 04:47 UTC
# 🐛 bug report

## Description of the problem
The Favicon looks weird on Chromebooks

## How has this issue affected you? What are you trying to accomplish?
N/A

![image](https://user-images.githubusercontent.com/180963/56182633-efee1900-5fc7-11e9-8b94-3dff97540435.png)

as you can see, in the bottom right of the menu bar the icon is almost invisible.

my suggestion is we change it to the codesandbox blue color.

@CompuIves what do you think?

if you say yeah, I'll go ahead and do it.

**Comment by lbogdan** [comment] 2019-04-23 13:35
Closing as duplicate of #1644 , which was resolved in #1718 .

@lifeiscontent Please try re-adding the icon, and feel free to reopen this if you still get the wrong one.

**Closed by lbogdan** 2019-04-23 13:35 UTC
