### ISSUE TITLE
Cannot use import statement outside a module

### ISSUE THREAD

**Issue by eltorio** [codesandbox/codesandbox-client#6574] opened 2022-03-23 06:21 UTC
# 🐛 bug report

## Info

- [x] I have read the [Contributing Guidelines][contributing] for this project.
- [x] I agree to follow the [Code of Conduct][code_of_conduct] that this project
      adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem

May be the same as #5464 wich was closed by @DeMoorJasper 

## How has this issue affected you? What are you trying to accomplish?

When trying to transpile to project, codesandbox throws an error Cannot use import statement outside a module, which points to the following import
import { createApp } from "vue";
<img width="790" alt="Capture d’écran 2022-03-23 à 07 20 22" src="https://user-images.githubusercontent.com/6966689/159636126-7b71ff1a-fce1-4457-b7d2-d7b2e7af3f5b.png">

### To Reproduce

Click the refresh icon in the browser view.

### Link to sandbox: https://codesandbox.io/s/sctg-sidebar-cohelk
Go to provided sandbox link.

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | Latest |
| Browser          |  [Version 1.36.119 Chromium: 99.0.4844.83](https://brave.com/latest/)|
| Operating System | MacOS 12.3 |

[code_of_conduct]: https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md
[contributing]: https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md

**Comment by DeMoorJasper** [comment] 2022-03-23 09:43
Duplicate of https://github.com/codesandbox/codesandbox-client/issues/6194

**Closed by DeMoorJasper** 2022-03-23 09:43 UTC
