### ISSUE TITLE
Older EventListener keeps working when was deleted

### ISSUE THREAD

**Issue by Canopix** [codesandbox/codesandbox-client#2041] opened 2019-06-09 14:08 UTC
# 🐛 bug report

## Description of the problem
I think this is a bug, I added a key down event listener with a simple function that returns console.log("a"), then I deleted that one and put console.log("b") and save the change. 
If I press any button, the console shows me two lines, one with "a" and another with "b".

 
## How has this issue affected you? What are you trying to accomplish?
This is a simplification of the bug to show what is the problem.

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | Web Client
| Browser          | Chrome Lastest
| Operating System | Windows 10

**Comment by lbogdan** [comment] 2019-06-20 16:35
Hey @Canopix ,

This is because of how HMR (hot module replacement) works combined with creating global resources (timers, intervals etc.). What you can do is enabling `hardReloadOnChange` in `sandbox.config.json`, as documented in https://codesandbox.io/docs/configuration#sandbox-configuration .

Closing this, as it's expected behavior.

**Closed by lbogdan** 2019-06-20 16:35 UTC
