### ISSUE TITLE
How to exit Vim "Insert Mode" (not a joke I promise)

### ISSUE THREAD

**Issue by cedricmckinnie** [codesandbox/codesandbox-client#1860] opened 2019-05-07 19:24 UTC
# ❔ Question

I enabled Vim bindings and refreshed the page. Bindings were successfully enabled however after entered Insert Mode, hitting the Esc key to exit Insert Mode un-focuses the editor window and does not remove Insert Mode.

Is there a different "Exit Insert Mode" binding? Is there a way to disable un-focusing when pressing the Esc key?

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  |  Latest
| Browser | Chrome/Version 74.0.3729.131 (Official Build) (64-bit)
| Operating System | MacOS/Mojave 10.14.4

**Comment by cedricmckinnie** [comment] 2019-05-07 20:24
One possible solution is to remap the escape key in settings.json. I decided to go with 'jk' which is a popular option and I already see the appeal. 

**Settings.json**

`"vim.insertModeKeyBindings": [
    {
      "before": [
        "j",
        "k"
      ],
      "after": [
        "<esc>"
      ]
    }
  ]`

I'm still curious to know if this has been an issue for other vim users or if everyone has been remapping keys. In any case, thanks anyway!

**Comment by steventsao** [comment] 2019-05-11 23:21
Can you update to your link? It actually leads to this same issue rather than to a sandbox.

**Comment by calebeby** [comment] 2019-07-07 01:44
I'm also seeing this issue. Not sure what to do about it :thinking:

**Comment by kennethkoontz** [comment] 2019-09-12 03:37
I had the same issue with the Chrome Vimium plugin installed. Disabling Vimium when in code sandbox fixes it for me.

**Comment by calebeby** [comment] 2019-09-12 03:50
@kennethkoontz That fixed it for me! Thanks for figuring that out!

**Comment by danielo515** [comment] 2020-01-28 10:07
Thanks @kennethkoontz , that was my issue too!

**Comment by lbogdan** [comment] 2020-02-03 12:00
Closing this, as it seems the issue is caused by the Vimium Chrome plugin, and disabling the plugin fixes the issue.

**Closed by lbogdan** 2020-02-03 12:00 UTC
Labels: ❔ Question

**Comment by devstefancho** [comment] 2020-10-03 10:15
> 
> **Settings.json**
> 
> `"vim.insertModeKeyBindings": [ { "before": [ "j", "k" ], "after": [ "<esc>" ] } ]`
> 

If anyone who add this to settings.json but not working yet.
you need to refresh your browser to work this. 
I hope it helps
