### ISSUE TITLE
Could not fetch dependencies, please try again in a couple seconds: Something went wrong while packaging the dependency INVALID_VERSION

### ISSUE THREAD

**Issue by ptrushin** [codesandbox/codesandbox-client#1938] opened 2019-05-20 09:20 UTC
# ❔ Question

Getting Error - Could not fetch dependencies, please try again in a couple seconds: Something went wrong while packaging the dependency data-driven-ui@1.0.1: INVALID_VERSION. This happened after I tried to install my own package data-driven-ui (https://www.npmjs.com/package/data-driven-ui)

What did I do wrong?

### Link to sandbox:

https://codesandbox.io/s/datadrivenuidev-8gwxf

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | 
| Browser          |  Firefox 66.0.5
| Operating System | Windows 10

**Comment by abdullahtariq1171** [comment] 2019-05-20 09:40
looks like duplicate of https://github.com/codesandbox/codesandbox-client/issues/1892

**Comment by lbogdan** [comment] 2019-07-11 22:03
@abdullahtariq1171 is right, closing this as a duplicate of #1892 . Please follow that instead.

**Closed by lbogdan** 2019-07-11 22:03 UTC
Labels: 🖨 Duplicate
