### ISSUE TITLE
Crash keeps happening every 2 seconds 

### ISSUE THREAD

**Issue by dilliom** [codesandbox/codesandbox-client#4171] opened 2020-05-21 07:51 UTC
<h1>💥 Crash Report</h1>

  <h2>What were you trying to accomplish when the crash occurred?</h2>

  > Please use this issue template to describe what you were doing when you encountered this crash. While we are able to fill in some details automatically, it's not always enough to reproduce!

  <h3>Link to sandbox: [link]() (optional)</h3>

  <h3>Crash Details</h3>

  <details>
  <summary>Environment</summary>

  | Browser |  Version  | Operating System | CodeSandbox Version |
  | ------- | --------- | ---------------- | ------------------- |
  | safari | 13.1.0 | OS X 10.15.4           | 3c00eab7a          |

  **Route:**
  https://codesandbox.io/s/funny-wildflower-n8rzw

  </details>

  <details>
  <summary>Error Message</summary>

  ```bash
  TypeError: undefined is not an object (evaluating 'k.find((function(e){return e.id===t})).title')
  https://codesandbox.io/static/js/app.df7dee977.js?_sw-precache=1716924358f7eeb43cc5796b4c3fd205:571:1476814
ua@https://codesandbox.io/static/js/common.fb3bc5c9c.chunk.js?_sw-precache=deaec0226cce771520367190f41d8182:1:1735717
Ka@https://codesandbox.io/static/js/common.fb3bc5c9c.chunk.js?_sw-precache=deaec0226cce771520367190f41d8182:1:1743983
ml@https://codesandbox.io/static/js/common.fb3bc5c9c.chunk.js?_sw-precache=deaec0226cce771520367190f41d8182:1:1766557
pl@https://codesandbox.io/static/js/common.fb3bc5c9c.chunk.js?_sw-precache=deaec0226cce771520367190f41d8182:1:1766482
il@https://codesandbox.io/static/js/common.fb3bc5c9c.chunk.js?_sw-precache=deaec0226cce771520367190f41d8182:1:1763810
il@[native code]
https://codesandbox.io/static/js/common.fb3bc5c9c.chunk.js?_sw-precache=deaec0226cce771520367190f41d8182:1:1721992
https://codesandbox.io/static/js/common.fb3bc5c9c.chunk.js?_sw-precache=deaec0226cce771520367190f41d8182:1:1797328
Yo@https://codesandbox.io/static/js/common.fb3bc5c9c.chunk.js?_sw-precache=deaec0226cce771520367190f41d8182:1:1721938
Jo@https://codesandbox.io/static/js/common.fb3bc5c9c.chunk.js?_sw-precache=deaec0226cce771520367190f41d8182:1:1721873
el@https://codesandbox.io/static/js/common.fb3bc5c9c.chunk.js?_sw-precache=deaec0226cce771520367190f41d8182:1:1760596
Sa@https://codesandbox.io/static/js/common.fb3bc5c9c.chunk.js?_sw-precache=deaec0226cce771520367190f41d8182:1:1739391
Sa@[native code]
https://codesandbox.io/static/js/app.df7dee977.js?_sw-precache=1716924358f7eeb43cc5796b4c3fd205:571:1474386
https://codesandbox.io/static/js/vendors~app.b9449cdec.chunk.js?_sw-precache=9fc4df6078a1c4838a897ff87183053e:1:1049826
https://codesandbox.io/static/js/vendors~app.b9449cdec.chunk.js?_sw-precache=9fc4df6078a1c4838a897ff87183053e:1:1161689
flush@https://codesandbox.io/static/js/vendors~app.b9449cdec.chunk.js?_sw-precache=9fc4df6078a1c4838a897ff87183053e:1:1164609
https://codesandbox.io/static/js/vendors~app.b9449cdec.chunk.js?_sw-precache=9fc4df6078a1c4838a897ff87183053e:1:1050497
https://codesandbox.io/static/js/vendors~app.b9449cdec.chunk.js?_sw-precache=9fc4df6078a1c4838a897ff87183053e:1:1044389
server.startContainer@https://codesandbox.io/static/js/vendors~app.b9449cdec.chunk.js?_sw-precache=9fc4df6078a1c4838a897ff87183053e:1:1053106
https://codesandbox.io/static/js/app.df7dee977.js?_sw-precache=1716924358f7eeb43cc5796b4c3fd205:571:851627
l@https://codesandbox.io/static/js/common-sandbox.3e66d97f1.chunk.js?_sw-precache=dbe85ee86de38ce24cd3d84da473c5d6:1:240626
https://codesandbox.io/static/js/common-sandbox.3e66d97f1.chunk.js?_sw-precache=dbe85ee86de38ce24cd3d84da473c5d6:1:240376
r@https://codesandbox.io/static/js/common-sandbox.3e66d97f1.chunk.js?_sw-precache=dbe85ee86de38ce24cd3d84da473c5d6:1:2405
i@https://codesandbox.io/static/js/common-sandbox.3e66d97f1.chunk.js?_sw-precache=dbe85ee86de38ce24cd3d84da473c5d6:1:2617
https://codesandbox.io/static/js/common-sandbox.3e66d97f1.chunk.js?_sw-precache=dbe85ee86de38ce24cd3d84da473c5d6:1:2676
Promise@[native code]
https://codesandbox.io/static/js/common-sandbox.3e66d97f1.chunk.js?_sw-precache=dbe85ee86de38ce24cd3d84da473c5d6:1:2567
internal.setCurrentSandbox@https://codesandbox.io/static/js/vendors~app.b9449cdec.chunk.js?_sw-precache=9fc4df6078a1c4838a897ff87183053e:1:1053035
https://codesandbox.io/static/js/app.df7dee977.js?_sw-precache=1716924358f7eeb43cc5796b4c3fd205:571:1118941
l@https://codesandbox.io/static/js/common-sandbox.3e66d97f1.chunk.js?_sw-precache=dbe85ee86de38ce24cd3d84da473c5d6:1:240626
https://codesandbox.io/static/js/common-sandbox.3e66d97f1.chunk.js?_sw-precache=dbe85ee86de38ce24cd3d84da473c5d6:1:240376
r@https://codesandbox.io/static/js/common-sandbox.3e66d97f1.chunk.js?_sw-precache=dbe85ee86de38ce24cd3d84da473c5d6:1:2405
i@https://codesandbox.io/static/js/common-sandbox.3e66d97f1.chunk.js?_sw-precache=dbe85ee86de38ce24cd3d84da473c5d6:1:2617
promiseReactionJob@[native code]
  
    in Unknown
    in DropTarget(Component)
    in div
    in cl
    in div
    in t
    in elements__Opener
    in div
    in Unknown
    in DropTarget(Component)
    in div
    in t
    in Styled(styled.div)
    in section
    in t
    in Styled(styled.div)
    in Unknown
    in t
    in Files___StyledCollapsible
    in Ol
    in gc
    in div
    in t
    in Unknown
    in div
    in t
    in elements__Container
    in Unknown
    in WithTheme(Component)
    in div
    in t
    in div
    in t
    in div
    in div
    in t
    in styled.div
    in div
    in t
    in elements__Container
    in t
    in Unknown
    in Unknown
    in Unknown
    in t
    in t
    in div
    in t
    in elements__Content
    in a
    in withRouter(a)
    in div
    in t
    in elements__Container
    in Unknown
    in withRouter()
    in t
    in Unknown
    in t
    in c
    in t
  ```

  </details>

**Comment by lbogdan** [comment] 2020-06-16 10:53
Closing this as a duplicate of #4366 .

**Closed by lbogdan** 2020-06-16 10:53 UTC
Labels: 💥 Crash Report
