### ISSUE TITLE
High cpu in Safari

### ISSUE THREAD

**Issue by olegafx** [codesandbox/codesandbox-client#3987] opened 2020-04-24 23:06 UTC
# 🐛 bug report

## Description of the problem
I open any sandbox on Macbook Pro using Safari. In `Activity Monitor` I see `Safari Networking` process that starts to use a lot of CPU power.

<img width="598" alt="image" src="https://user-images.githubusercontent.com/867546/80263420-2f792780-8656-11ea-8cc8-ac06016336e4.png">

## How has this issue affected you? What are you trying to accomplish?
I'm trying to use Codesandbox in Safari. In Chrome everything is fine.

Only open sandbox cause this problem. Any other page works fine.

I tried several things:
- Safe Boot without plugins
- Close socket connection by hand in a console
- Disable Live collaboration
- Open different sandboxes

None of it helped.

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | ,9ad4b4259 |
| Browser          | Safari 13.1.1 (15609.2.3) |
| Operating System | MacOS 10.15.5 Beta (19F62f) |

**Comment by AndrewSB** [comment] 2020-05-05 21:22
this reproduces with basically any sandbox I open

**Comment by kerstenremco** [comment] 2020-06-17 21:13
Same issue with all sandboxes
<img width="870" alt="image" src="https://user-images.githubusercontent.com/55450744/84951073-2ce3fd00-b0f0-11ea-921a-0c28e5e972a6.png">

**Comment by ChujieChen** [comment] 2020-08-13 03:11
Same issue

**Comment by SaraVieira** [comment] 2020-09-01 12:56
Hey!

We tried to profile this and can't tell what is wrong, everything seems to still work fine in safari despite the warning you get.

No issues in edge, chrome, or firefox so far when it comes to this and that just made me think safari doesn't really like when heavy applications are loaded into it and we load all of VSCode that is not optimized for safari but for V8 and blink that run on Chrome and Edge.

I am closing this since this seems to be a safari issue that we can't really control when running VSCode inside of safari and I am saying since all other pages work fine

Please reopen if something doesn't work safari so we can work on it and fix it

**Closed by SaraVieira** 2020-09-01 12:56 UTC
