### ISSUE TITLE
index.html file location matters when using Parcel bundler template

### ISSUE THREAD

**Issue by wannikid** [codesandbox/codesandbox-client#2030] opened 2019-06-06 10:44 UTC
# 🐛 bug report

## Description of the problem
External CSS libraries and scripts specified in the `index.html` file do not load from their CDN URLs when the `index.html` file is not located in the root of the project.

## How has this issue affected you? What are you trying to accomplish?
For reasons of simplicity my intention was to have all my source files located in the `/src` folder including the `index.html` file. However, once I move the `index.html` file to  the `/src` folder and update the relative links in the `index.html` and `package.json` files, my linked stylesheets and CDN scripts do no longer load.

In the Codesandbox docs I saw no mention that `index.html` needs to be located in the root of the project. Maybe this would already be enough to address the issue.

### Link to sandbox: [https://codesandbox.io/s/parcel-bundler-test-ep95k]()
This sandbox has the working solution with `index.html` in the project root. Moving `index.html` to the `/src` folder will result in errors (missing Vue, css, etc.)

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | see link above
| Browser          | Chrome v74
| Operating System | Win10

**Comment by karlhorky** [comment] 2019-08-01 23:05
Ah just realized this issue looks a lot like my #2240, I have some more information over there...

**Comment by lbogdan** [comment] 2019-08-05 15:49
As the linked sandbox doesn't seem to work anymore, I'll close this as a duplicate of #2240 , please follow that one instead.

**Closed by lbogdan** 2019-08-05 15:49 UTC
Labels: enhancement, 🎒 Bundler
