### ISSUE TITLE
"Could not find module in path" error with specific dependency

### ISSUE THREAD

**Issue by panick-carousel** [codesandbox/codesandbox-client#5853] opened 2021-05-30 05:02 UTC
# 🐛 bug report

## Preflight Checklist

- [x] I have read the [Contributing Guidelines][contributing] for this project.
- [x] I agree to follow the [Code of Conduct][code_of_conduct] that this project
      adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem
The [assert module](https://github.com/browserify/commonjs-assert) fails to resolve for version 2.0.0 but works fine for 1.5.0.

What appears to be happening is that the package.json for 1.5.0 is being used to look for the module entry point in 2.0.0.  The [difference between the two versions of assert](https://github.com/browserify/commonjs-assert/compare/v1.5.0...v2.0.0) is that the path to "main" in package json changed.  I think somehow the 1.5.0 value is cached and reused in 2.0.0, which causes the error.

## How has this issue affected you? What are you trying to accomplish?
This is basic functionality that I would expect to work without error

### To Reproduce
Starting with a blank react sandbox, add a dependency on "assert" and set it to version 2.0.0, which is the latest.  Import it in App.js and observe failure to compile.  Then change the version of "assert" to 1.5.0 and observe the code working fine.

### Link to sandbox: [link]() (optional)
https://codesandbox.io/s/lucid-gates-0xgy3?file=/src/App.js

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |       latest ?       |
| Browser          |        Chrome latest      |
| Operating System |       win10 latest       |

[code_of_conduct]: https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md
[contributing]: https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md

**Comment by lbogdan** [comment] 2021-05-31 08:15
Hey @panick-carousel ,

Thanks for your report!

I can reproduce this, we'll take a look at this and get back to you.

**Comment by bietkul** [comment] 2021-06-11 04:44
@lbogdan I'm facing the similar kind of issue. Please check this codesanbox link. https://codesandbox.io/s/github/appbaseio/reactivesearch/tree/vue-maps/packages/vue/examples/reactive-google-map?file=/src/main.js
The example works fine locally.
It was working with codesandbox two days back.

**Comment by bietkul** [comment] 2021-06-11 05:05
If I define the `template`  property as `node` in `sandbox.config.json` then it works well. But I want to make it work with `vue-cli` template to avoid the eslint errors.
```js
{
	"template": "node"
}
```

**Comment by DeMoorJasper** [comment] 2021-06-15 12:43
Cannot reproduce this, does it still happen?

**Comment by bietkul** [comment] 2021-06-15 15:21
It is strange. It doesn't happen now.

**Comment by DeMoorJasper** [comment] 2021-06-15 15:31
The bundler changed a lot since this issue so it's probbaly fixed.

Gonna close this issue for now, feel free to reopen or open q new issue if it persists

**Closed by DeMoorJasper** 2021-06-15 15:31 UTC
Labels: 🎒 Bundler, 🐛 Bug
