### ISSUE TITLE
Replace React+Typescript template

### ISSUE THREAD

**Issue by vitkon** [codesandbox/codesandbox-client#1303] opened 2018-11-16 09:20 UTC
# 🌈 Replace React+Typescript template

## Current state
Currently react-scripts are used to create React+TS sandbox.  
e.g. `create-react-app my-sandbox --scripts-version=react-scripts-ts`

However, it lacks the recent features from CRA v2 (e.g. CSS modules support).  
CRA v2 also supports creating a React+TS projects now.

## Suggested solution
- remove `create-react-app my-app --scripts-version=react-scripts-ts`
- instead use `create-react-app my-sandbox --typescript` to create a new React+TS sandbox

**Comment by CompuIves** [comment] 2018-12-03 13:54
Hmm yes, I agree. We already support typescript files in the `new` template. I think it's just a matter of switching the IDs to a proper react preset.

**Comment by fabb** [comment] 2018-12-18 07:53
I noticed that in the current React + TS Preset, when I create a GitHub repo, suddenly a lot of unnecessary and confusing files pop up like `index.js`, `registerServiceWorker.js`, and also `App.tsx` since `index.tsx` defines its own `const App`.
Should I create a new issue for this, or does this fit here?

**Comment by CompuIves** [comment] 2018-12-18 09:49
Good point @fabb, it fits in here. When we replace the React+TS with just the React one with TS files we'll have a better export. I'll focus on this today.

**Comment by sw-yx** [comment] 2019-01-30 06:37
just swimming by here to comment that this doesnt seem to have been done yet - also needs to import @types/react and @types/react-dom

**Comment by CompuIves** [comment] 2019-01-30 13:33
The `react-ts` sandbox should be fixed, but I forgot to add the typing dependencies. I'll add them now!

**Comment by jimthedev** [comment] 2019-02-21 19:47
@CompuIves are you sure this is working? I am seeing no type checking in places like https://codesandbox.io/s/5kkl8v19o4 where I'd expect to see it totally yelling at me.

**Comment by CompuIves** [comment] 2019-02-21 21:36
Hey! I'm getting this:
[image: Screenshot 2019-02-21 at 22.35.52.png]

What are you getting?

**Comment by jimthedev** [comment] 2019-02-22 00:22
Weird. It looks like github didn’t pick up your screen shot. Can you
re-upload?

**Comment by SaraVieira** [comment] 2019-02-24 12:27
Hey!

The issue is that CRA doesn't seem to support tsx, by changing to TS it yells

A LOT ahha

https://codesandbox.io/s/7knpr7k55x

**Comment by sw-yx** [comment] 2019-02-24 12:40
@SaraVieira you have to rename the files to .tsx extension and it works: https://codesandbox.io/s/5yoq2pzv9n

this was an intentional typescript decision that files with jsx in it must have .tsx extension. source: https://github.com/Microsoft/TypeScript-React-Starter/issues/4

**Comment by vitkon** [comment] 2019-02-27 09:29
@fawmi Compile time type checking works well in CRA 2. It even has a nice formatter (better than TS does). The only limitation is you have to stay away from  "const enum" in your TS

**Comment by CompuIves** [comment] 2019-02-27 09:57
I was getting this @jimthedev 	

![image](https://user-images.githubusercontent.com/587016/53481936-69fd2980-3a7e-11e9-9a4f-b1857daa6566.png)

It could be that the type definitions were downloaded too late, I fixed that bug locally but haven't deployed it yet.

**Comment by lbogdan** [comment] 2019-03-22 14:34
@CompuIves swears this is now fixed 🙂 , are you folks still seeing issues?

**Comment by jimthedev** [comment] 2019-03-22 14:44
I added typescript as a dependency and everything is working now I think?

**Comment by JasonKleban** [comment] 2019-10-04 13:58
This is still open but the comments seem like it would be closed.  However, I can't get `
import styles from "./styles.scss";` or `
import styles from "./styles.less";` to work - gives ts(2307) `Cannot find module './styles.scss'.`.  Am I just doing it wrong, or is there no support for css-modules still?  Thanks!

**Comment by fawmi** [comment] 2019-10-04 14:41
@JasonKleban The module file names should be filename.module.extension
https://create-react-app.dev/docs/adding-a-css-modules-stylesheet

**Comment by SaraVieira** [comment] 2019-12-11 16:54
This issue seems to be fixed as we work with pure CRA now :)

**Closed by SaraVieira** 2019-12-11 16:54 UTC
Labels: need more info, typescript
