### ISSUE TITLE
React - useState without rendering doesn't update the state correctly

### ISSUE THREAD

**Issue by yairopro** [codesandbox/codesandbox-client#5944] opened 2021-07-04 15:15 UTC
# 🐛 bug report

## Preflight Checklist

- [x]  🤥 I have read the [Contributing Guidelines][contributing] for this project.
- [x] I agree to follow the [Code of Conduct][code_of_conduct] that this project
      adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem

**Disclaim: The bug doesn't happen in other sandboxes like [jsfiddle](https://jsfiddle.net/987coep2/) or stackoverflow, or even locally.**

In a react sandbox, when I try to edit a component's state, using useState hook, **without re-rendering the component** by returning the same state pointer, odd things happens. In my scenario, I just try to push a number to a state array like so
````javascript
setState(array => {
  array.push(array.length);
  return array;
});
````
What should have happen is just having the same array with one new number at the end.
What does happen is having 2 new numbers pushed at the end.

## How has this issue affected you? What are you trying to accomplish?
The updated state push more items than told to, making the state wrong.

### To Reproduce
````javascript
const [array, setArray] = useState([]);
setArray(array => {
  array.push(array.length);
  return array;
});

// array will have 2 new numbers on next render
````
### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |      Don't know       |
| Browser          |       Chrome 91       |
| Operating System |       MacOS big sur       |

**Comment by smhutch** [comment] 2021-08-30 10:40
Thanks for opening this issue @yairopro. I have had a look into it today, and didn't find a solution yet.

One thing I did discover is that when clicking on the `render` button, the component is rendering twice, but it should only be re-rendering once. I haven't been able to identify why that is happening so far, though I'm continuing to look into it.

**Comment by smhutch** [comment] 2021-08-30 16:50
@yairopro I looked into this some more and found that the double render is caused by the existence of a `StrictMode` wrapper inside your [Sandbox](https://codesandbox.io/s/quizzical-stallman-8v2u8), but not in the [JSFiddle](https://jsfiddle.net/987coep2/) you shared.

For comparison, I created another [JSFiddle](https://jsfiddle.net/635gwhLk/3/) that uses `StrictMode`, and the behaviour is the same.

I also tested the sandbox locally, and encountered the same behaviour. Since the behaviour seems to match other environments that use `StictMode`, I'm going to close this issue.

Unrelated to the issue you shared, in what scenario would you actually want to mutate state, without it re-rendering the component? If you want to keep track of a certain mutable value in React, I would typically recommend using a ref instead, as shown in [this Sandbox](https://codesandbox.io/s/ref-proposal-39g25).

**Closed by smhutch** 2021-08-30 16:50 UTC
Labels: 🐛 Bug, 🎒 Bundler

**Comment by yairopro** [comment] 2021-08-31 15:37
Hi @smhutch 
Thanks for the discovery about `StrictMode`.
 
About your question:

For most of cases your are right, I wish to re-render with the new state.
But sometimes 
1. I call `setState` without changing the state. This is when the edition depends on the current state like (dumb example):
````javascript
  const [state, setState] = useState(0);
  useEffect(() => 
    subscribeToSomeEvent(() => 
      setState(state => {
        if (state % 2) return state + 1;
        return state;
      })
    ),
  []);
````


2. and sometimes I need to edit a state but without rerender, because the edition, like:
````javascript
  const [state, setState] = useState(() => new Entity());
  const isTheUiFocused = useIsTheUIFocused();

  return isTheUiFocused ? <UI /> : null;
  
  // some async events later...
  setState(entity => {
    if (isTheUiFocused)
      entity = copy(entity); // change the pointer when needed to re-render
    entity.field = newValue; // edit the state
    return entity;
  });
````

Happy to discuss 😁
