### ISSUE TITLE
Exported package is incomplete

### ISSUE THREAD

**Issue by artola** [codesandbox/codesandbox-client#5402] opened 2021-01-26 06:42 UTC
# 🐛 bug report

## Preflight Checklist

- [x] I have read the
      [Contributing Guidelines](https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md)
      for this project.
- [x] I agree to follow the
      [Code of Conduct](https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md)
      that this project adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem

My React sandbox is up and running even without having as dependency `react-scripts`. I guess that you run some kind of "global" one. But when the sandbox is exported, the `package.json` does not include the version used.
If I just add the last `react-scripts` to the `devDependencies` it is not running as expected. Therefore I guess that the version is different or even it was somehow altered.

## How has this issue affected you? What are you trying to accomplish?

I would like to use a github repo and keep it in sync with the sandbox. Working directly on the sandbox or from the code in github must produce the same result, if there are limitations must be known but be consistent between this 2 ways of work.

### To Reproduce

In this sample [sandbox](https://codesandbox.io/s/react-markdown-basic-example-forked-49r7t?file=/src/App.js), I import a markdown document and show a preview. The code works in Codesandbox as written, but it does not in the exported version, because `md` files are loaded differently as long as `react-scripts` (or configuration) does not match.

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |
| Browser          |
| Operating System |

**Comment by SaraVieira** [comment] 2021-01-26 16:04
Hey

I'm sorry I am not really understanding your issue, in your example you don't have react scripts so it won't load locally, that's because that needs to be installed to work locally.

But you say when you add react scripts you get an error?

It seems to work fine when I add it manually:

https://codesandbox.io/s/react-markdown-basic-example-forked-wtgg8?file=/package.json

**Comment by artola** [comment] 2021-01-26 19:29
@SaraVieira Thank you very much for the prompt reply. Try downloading the sandbox where you added `react-scripts`, and you will see that it does not work as expected.
It seems that you added `react-scripts v4.0.1` that will be used when downloaded and run in local, but it run other version (might be a global install of react-scripts?) when run in Codesandbox.

Therefore, I run into a bunch of problems because the configuration of the sandbox is not known, I would not say that should be modifiable but at least should be transparent, and when the sandbox is exported should be included.

Using your code: https://codesandbox.io/s/react-markdown-basic-example-forked-wtgg8?file=/package.json

Output of the sandbox in Codesanbox:
![image](https://user-images.githubusercontent.com/11500763/105894630-c4111b80-6014-11eb-8f28-b0c4ffc07259.png)

Output of the downloaded sandbox:
![image](https://user-images.githubusercontent.com/11500763/105894468-988e3100-6014-11eb-8cfb-f5b0c130c64e.png)

**Comment by artola** [comment] 2021-01-26 19:37
One more thing, as I understand the client version runs in the browser, might be that compiles in a different way. I would like to have a sandbox that can be imported from Github and modified using Codesanbox.
I guess that I should setup a "container" with for example `react-scripts` and any other config, then this will work in Codesanbox as by exporting the sandbox, and cloning the repo as well.

I am not a fun of CRA but these materials will be for training and we want to make it simple to share and play with.

**Comment by lbogdan** [comment] 2021-01-26 19:40
Hey @artola ,

If you can push your app to a GitHub repo I can help you run it in a server / container sandbox.

**Comment by artola** [comment] 2021-01-26 22:07
@lbogdan Thanks for your help. Anyway, I guess that it is not a problem to create a container (I did this for the same[ example](https://codesandbox.io/s/container-app-e0wt2?file=/src/App.js)).
Probably it is the best in the long run, our idea was to setup a very simple CRA to support some coding exercises for training.
Then, using the browser version might be ok, but only if the code exposed in the sandbox match what the user can download (exporting the sandbox or cloning the Github repo).

**Comment by SaraVieira** [comment] 2021-01-27 19:15
Hey

I figured out the issue, the code you wrote doesn't work on CRA that's the main issue but it works on our bundler, It does not have to do with the version of react scripts, the issue is that create react app does not support importing markdown files. Making it a container would for that reason not work since there we actually run react scripts

The issue is that our bundler does support you importing anything and just interprets it as a string. I think here you end up with two choices:

* You can make the code a JS file like so: https://codesandbox.io/s/react-markdown-basic-example-forked-wtgg8?file=/src/App.js
* Or use something like gatsby in a container that does support it.


Our only fix would be to remove that ability to import markdown files and maybe that would be a good idea but it wouldn't really fix the problem. CRA is very limited in importing things.

We do add react-scripts if you don't have it so that you run it locally but that's not what+'s causing the issues.

If you wanna read about our bundler you can do here: https://github.com/codesandbox/codesandbox-client/tree/master/standalone-packages/sandpack

Let me know if this makes sense and with this what you think could be done on our side.

**Comment by artola** [comment] 2021-01-28 07:06
@SaraVieira Thanks for the info, now I have a more clear idea of what was happening and it is related to the difference between the bundlers: `sandpack` (running in browser) and `react-scripts` on local.

**Comment by SaraVieira** [comment] 2021-01-28 18:43
Yeah, we need to make this more explicit.

I also spoke to @CompuIves and we decided to remove support for importing markdown files as create react app does not support and we want to keep parity with them.

Mind me closing this issue and create one for: "Markdown imports work in codesandbox and not locally"?

Again, thank you for your understanding

**Comment by artola** [comment] 2021-01-28 21:28
@SaraVieira Thanks again. Super great support.

**Comment by SaraVieira** [comment] 2021-01-29 18:06
You are super welcome!

I am gonna close this one and you can follow the new issue here that explains better the issue: https://github.com/codesandbox/codesandbox-client/issues/5424

Have a great weekend

**Closed by SaraVieira** 2021-01-29 18:06 UTC
