### ISSUE TITLE
Indentation (style?) issue

### ISSUE THREAD

**Issue by mindplay-dk** [codesandbox/codesandbox-client#1595] opened 2019-03-12 18:14 UTC
Count with me here: there are precisely 8 spaces of indentation on both lines.

![weird-indentation](https://user-images.githubusercontent.com/103348/54224697-529c5280-44fa-11e9-88ec-1113e52d76f4.gif)

Too fast for you?

I can copy/paste this into (say) a gist, and you can see the spaces are even:

![image](https://user-images.githubusercontent.com/103348/54224878-b6bf1680-44fa-11e9-90a5-db67e2c8b36d.png)

I can press "prettify", and it still doesn't align.

I'm guessing it's a style issue?

Something to do with using more than one font in the editor styles, and one font has a different character width than the other maybe?

**Comment by AndrianMauricio** [comment] 2019-03-17 15:42
+1
It's even worse for me:
![Screenshot from 2019-03-17 12-34-06](https://user-images.githubusercontent.com/4183134/54493645-1b8ac000-48b1-11e9-9081-1a739b6274e0.png)

After copy pasting to VS Code:
![Screenshot from 2019-03-17 12-36-35](https://user-images.githubusercontent.com/4183134/54493670-5b51a780-48b1-11e9-9af1-e718533d08c9.png)

It makes it unusable.

When I saw it for the first time, I just had installed Droid Sans Fallback. I've installed Droid Sans Mono, but the problem persisted.
I'm using Google Chrome in Ubuntu 18.10. It looks good on Firefox Developer Edition.

**Comment by lbogdan** [comment] 2019-03-22 09:14
Hey @mindplay-dk , @AndrianMauricio ,

With the recent [switch to VSCode as the default editor](https://hackernoon.com/announcing-codesandbox-v3-4febbaba1963), I think this shouldn't be an issue any more. Can you please confirm, and if so, close this issue? Thanks!

**Comment by mindplay-dk** [comment] 2019-03-23 14:15
It's much better, but it's still not 100%.

![image](https://user-images.githubusercontent.com/103348/54867242-4e83f680-4d7e-11e9-8677-8d7dd7df7d34.png)

That `return` statement is still off by half a character, which is enough to be distracting.

I'm not sure those two fonts play nice together?

(that cursive font is cute, but perhaps not very practical anyhow...)

**Comment by lbogdan** [comment] 2019-03-23 14:21
@mindplay-dk What OS / browser are you using? Have you tried using other fonts?

**Comment by mindplay-dk** [comment] 2019-03-23 15:12
Win 10/Pro, latest Chrome.

Not sure what you mean by "using other fonts"? (I'd assume the editor defines which fonts it uses?)

It might not be just a font issue though - look at this:

![indetation-fudge](https://user-images.githubusercontent.com/103348/54867898-429c3280-4d86-11e9-831b-7c44d473f0d5.gif)

It looks like the vertical alignment is off for the whole editor, even if you're just editing one line...?

**Comment by lbogdan** [comment] 2019-03-23 15:16
As we recently switched to VSCode as the default editor, you can change the font exactly the same way you would in the native VSCode application.

**Comment by lbogdan** [comment] 2019-03-23 15:20
Looking at your image, it just occurred to me that the default font we're using, Dank Mono, might have different character widths at different font weights, and the syntax highlighting is using different weights for different syntactic units.

**Comment by lbogdan** [comment] 2019-03-23 15:25
Sorry, I'm on my phone and I somehow managed to delete the previous comment. As I was saying, we recently switched to VSCode as the default editor, so you can change the font (family) exactly the same way you would in the native VSCode application.

**Comment by mindplay-dk** [comment] 2019-03-24 14:34
> Looking at your image, it just occurred to me that the default font we're using, Dank Mono, might have different character widths at different font weights, and the syntax highlighting is using different weights for different syntactic units.

Probable.

I changed it to just `Courier New` and the problem vanished.

I use `Courier New` in other desktop tools - unfortunately, it renders terribly in browsers 😐

> As I was saying, we recently switched to VSCode as the default editor, so you can change the font (family) exactly the same way you would in the native VSCode application.

I shouldn't need to though, right? You still consider this a bug?

I mean, the default font/theme ought to work with a standard, out-of-the-box Win 10/Pro, right?

**Comment by lbogdan** [comment] 2019-03-24 20:24
Pinging @kitten (the creator of Dank Mono), as a font expert, can you please take a look at this? Thanks!

**Comment by kitten** [comment] 2019-03-24 20:35
Oh I've noticed this issue myself and character weights are a perfect guess!

Dank Mono does not have different weights yet so I suppose when the browser interpolates the weight it also scales each character width.

I'd guess this can only be resolved by me actually finishing the bold weight at last 😅

**Comment by lbogdan** [comment] 2019-03-24 20:44
Ok, I'll leave this open until then, please ping us with updates!

**Comment by kentcdodds** [comment] 2019-03-28 17:50
@kitten 👋 That would be fabulous! I actually notice this slightly in VSCode as well, so I'm guessing fixing that would fix it everywhere <3

**Comment by karlhorky** [comment] 2019-05-27 13:36
I've also seen this with the VS Code editor (with embedded JS expressions in curly braces in JSX). Everything aligned to the left except for the embedded expressions, which are slightly indented to the right:

<img width="158" alt="Screen Shot 2019-05-27 at 15 33 26" src="https://user-images.githubusercontent.com/1935696/58423277-f971a300-8094-11e9-93d9-caf891134073.png">

https://codesandbox.io/s/crazy-ritchie-v9lnd

**Comment by karlhorky** [comment] 2019-05-28 15:08
I've also seen this with the VS Code editor (with embedded JS expressions in curly braces in JSX). Everything aligned to the left except for the embedded expressions, which are slightly indented to the right:

<img width="158" alt="Screen Shot 2019-05-27 at 15 33 26" src="https://user-images.githubusercontent.com/1935696/58423277-f971a300-8094-11e9-93d9-caf891134073.png">

The deeper you go, the less aligned it gets:

<img width="284" alt="Screen Shot 2019-05-28 at 17 07 20" src="https://user-images.githubusercontent.com/1935696/58489245-285a4880-816b-11e9-9d9f-d5d63a1fa5fb.png">

https://codesandbox.io/s/crazy-ritchie-v9lnd

**Comment by mindplay-dk** [comment] 2019-06-25 11:57
Might want to consider changing the default font-family setting to something that works for now?

If or when the font gets fixed, you can always switch back - but it's a pretty bad experience right now.

**Comment by lbogdan** [comment] 2019-07-14 17:57
@kitten Any update on this?

**Comment by NordlingDev** [comment] 2019-11-13 18:35
Any update??

**Comment by esr360** [comment] 2019-11-16 22:57
<img width="211" alt="Screenshot 2019-11-16 at 22 57 29" src="https://user-images.githubusercontent.com/3431882/69000246-7eab7700-08c4-11ea-880e-496d20fe92e8.png">

Still an issue - really bugs me :/

**Comment by jarrodwhitley** [comment] 2020-01-24 17:25
@kitten an update? Indentation is still messed up.

**Comment by kentcdodds** [comment] 2020-09-04 13:49
Bump

**Comment by mindplay-dk** [comment] 2020-09-06 14:30
A year and a half later, and the font hasn't been fixed.

At this point, can we just switch to a different font?

You can switch back again if the font you wanted gets fixed.

In the mean time, just pick a font that works?

**Comment by kitten** [comment] 2020-09-06 15:29
I do have a new version that could be tested here to see whether that fixes the issue

**Comment by karlhorky** [comment] 2020-12-06 10:34
Oh stalebot

**Comment by SaraVieira** [comment] 2020-12-08 18:33
Hey

You can always change the font in the editor settings if you have that font installed on your computer, right now we just don't allow the upload of fonts but besides that, I use codesanbdox with MonoLisa because I set it in the editor and I have it installed in my computer
![CleanShot 2020-12-08 at 19 32 19](https://user-images.githubusercontent.com/1051509/101525818-19716a80-398c-11eb-89a3-4099fc158c7a.png)
![CleanShot 2020-12-08 at 19 32 14](https://user-images.githubusercontent.com/1051509/101525820-1aa29780-398c-11eb-81ed-f9cfbf90e584.png)

We will allow the upload of features, it's something we want to work on but anything you have installed on your computer will work on CodeSandbox

**Comment by karlhorky** [comment] 2020-12-08 18:38
I think the issue is that the default font, Dank Mono from @kitten, has some issues with indentation.

It seems like [there's a new version](https://github.com/codesandbox/codesandbox-client/issues/1595#issuecomment-687820194) that could be tested with CodeSandbox though! 🙌

**Comment by SaraVieira** [comment] 2020-12-08 18:42
I know, we will change the font mostly because it has issues with stuff other than latin characters 

I can also install the new one, I was answering the question of can we switch to a new font 

It's completely possible to change it on your settings

**Comment by karlhorky** [comment] 2020-12-08 18:46
> we will change the font mostly because it has issues with stuff other than latin characters

Ah ok, wasn't aware of that. So I guess the new default font stack will be `Menlo, Monaco, 'Courier New', monospace`?

**Comment by SaraVieira** [comment] 2020-12-08 18:49
Naa, working with @DannyRuchtie to see what font to use as the default, we have a bunch of options here:

https://coding-fonts.css-tricks.com/

It would be cool to see what everyone's pick would be

**Comment by karlhorky** [comment] 2020-12-08 20:19
Ah, interesting. I guess because of my work with beginners, I would suggest something that is familiar and not too crazy / fancy (eg. no ligatures or cursive or anything by default - maybe with a setting to turn it on).

Readability and knowing what each character of the code actually is is a critical accessibility issue for beginner learners.

**Comment by SaraVieira** [comment] 2020-12-08 20:19
I just deployed a new version of dank but I could never reproduce this issue 

Can someone please tell me if this upgrade fixed it?

**Comment by SaraVieira** [comment] 2020-12-08 20:20
We do have liggatures off by default, it's a setting so we are already half way there 😀

**Comment by karlhorky** [comment] 2020-12-08 20:21
> Can someone please tell me if this upgrade fixed it?

Seems like [my sandbox](https://codesandbox.io/s/crazy-ritchie-v9lnd) from [my comment above](https://github.com/codesandbox/codesandbox-client/issues/1595#issuecomment-496558445) is working now!! 🎉

![Screen Shot 2020-12-08 at 21 20 18](https://user-images.githubusercontent.com/1935696/101537177-55f89280-399b-11eb-8d27-4e982dce1aa7.png)

**Comment by SaraVieira** [comment] 2020-12-08 20:31
Awesome! Will then close this and I am still subscribed so if anyone is still experiencing the issue I will reopen it 👍

**Closed by SaraVieira** 2020-12-08 20:31 UTC
Labels: 🤔 Improvement
