### ISSUE TITLE
Github related crash

### ISSUE THREAD

**Issue by rosalie337** [codesandbox/codesandbox-client#5497] opened 2021-02-20 08:26 UTC
<h1>💥 Crash Report</h1>

  <h2>What were you trying to accomplish when the crash occurred?</h2>

  > Please use this issue template to describe what you were doing when you encountered this crash. While we are able to fill in some details automatically, it's not always enough to reproduce!

  <h3>Link to sandbox: [link]() (optional)</h3>

  <h3>Crash Details</h3>

  <details>
  <summary>Environment</summary>

  | Browser |  Version  | Operating System | CodeSandbox Version |
  | ------- | --------- | ---------------- | ------------------- |
  | chrome | 88.0.4324 | OS X 11.1.0           | fb32368e7          |

  **Route:**
  https://codesandbox.io/dashboard/repositories?workspace=95c39926-3389-4d02-ad1b-790f99bd31b1

  **Error Code:**
dd4de542d8254b6284045f5ab9adc999

  </details>

  <details>
  <summary>Error Message</summary>

  ```bash
  TypeError: Cannot read property 'type' of undefined
  TypeError: Cannot read property 'type' of undefined
    at Qd (https://codesandbox.io/static/js/app.65ff96008.js?_sw-precache=9793f6afbc332ae3ba4cbde88e575db0:266:286904)
    at ua (https://codesandbox.io/static/js/common.b65abcb54.chunk.js?_sw-precache=8d318c83632cd21b54d38d2cfaa75b1d:1:1780850)
    at Ka (https://codesandbox.io/static/js/common.b65abcb54.chunk.js?_sw-precache=8d318c83632cd21b54d38d2cfaa75b1d:1:1789115)
    at xs (https://codesandbox.io/static/js/common.b65abcb54.chunk.js?_sw-precache=8d318c83632cd21b54d38d2cfaa75b1d:1:1827303)
    at ml (https://codesandbox.io/static/js/common.b65abcb54.chunk.js?_sw-precache=8d318c83632cd21b54d38d2cfaa75b1d:1:1811689)
    at hl (https://codesandbox.io/static/js/common.b65abcb54.chunk.js?_sw-precache=8d318c83632cd21b54d38d2cfaa75b1d:1:1811614)
    at il (https://codesandbox.io/static/js/common.b65abcb54.chunk.js?_sw-precache=8d318c83632cd21b54d38d2cfaa75b1d:1:1808942)
    at https://codesandbox.io/static/js/common.b65abcb54.chunk.js?_sw-precache=8d318c83632cd21b54d38d2cfaa75b1d:1:1767125
    at https://codesandbox.io/static/js/common.b65abcb54.chunk.js?_sw-precache=8d318c83632cd21b54d38d2cfaa75b1d:1:1842461
    at qo (https://codesandbox.io/static/js/common.b65abcb54.chunk.js?_sw-precache=8d318c83632cd21b54d38d2cfaa75b1d:1:1766834)
    at Xo (https://codesandbox.io/static/js/common.b65abcb54.chunk.js?_sw-precache=8d318c83632cd21b54d38d2cfaa75b1d:1:1767070)
    at Yo (https://codesandbox.io/static/js/common.b65abcb54.chunk.js?_sw-precache=8d318c83632cd21b54d38d2cfaa75b1d:1:1767005)
    at se (https://codesandbox.io/static/js/common.b65abcb54.chunk.js?_sw-precache=8d318c83632cd21b54d38d2cfaa75b1d:1:1836213)
    at Sn (https://codesandbox.io/static/js/common.b65abcb54.chunk.js?_sw-precache=8d318c83632cd21b54d38d2cfaa75b1d:1:1750631)
  
    in Qd
    in sf
    in Unknown
    in t
    in t
    in div
    in Content___StyledElement
    in Unknown
    in withRouter()
    in main
    in Dashboard___StyledElement2
    in div
    in Dashboard___StyledStack2
    in div
    in Dashboard___StyledStack
    in Unknown
    in De
    in Unknown
    in Gv
    in t
    in t
    in div
    in elements__Content
    in n
    in withRouter(n)
    in div
    in elements__Container
    in Unknown
    in withRouter()
    in t
    in Unknown
    in De
    in c
    in t
  ```

  </details>

**Comment by lbogdan** [comment] 2021-05-26 16:14
Closing as duplicate of #5816 .

**Closed by lbogdan** 2021-05-26 16:14 UTC
Labels: 💥 Crash Report
