### ISSUE TITLE
File search filters reset when switching between files

### ISSUE THREAD

**Issue by garethx** [codesandbox/codesandbox-client#3550] opened 2020-02-19 12:43 UTC
# 🐛 bug report

## Description of the problem
When using the file search within the editor, every time you change file the search options reset to on. If you switch them off they only stay switched off until you change file, or refresh the page.

![Screenshot 2020-02-19 at 12 34 54 PM](https://user-images.githubusercontent.com/1830035/74835498-6446c680-5315-11ea-8a2d-d42e9d3f190d.png)

## How has this issue affected you? What are you trying to accomplish?
Makes searching across multiple files more time-consuming.

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | Latest
| Browser          | Chrome
| Operating System | Mac OS X + Windows

**Comment by andrasbacsai** [comment] 2020-09-03 19:59
I cannot reproduce this one. Probably it's already corrected. Closing for now.

**Closed by andrasbacsai** 2020-09-03 19:59 UTC
