### ISSUE TITLE
crash after add dependency 'express'

### ISSUE THREAD

**Issue by jenac** [codesandbox/codesandbox-client#2754] opened 2019-10-12 17:32 UTC
<h1>💥 Crash Report</h1>

  <h2>What were you trying to accomplish when the crash occurred?</h2>

  > Please use this issue template to describe what you were doing when you encountered this crash. While we are able to fill in some details automatically, it's not always enough to reproduce!

  <h3>Link to sandbox: [link]() (optional)</h3>

  <h3>Crash Details</h3>

  <details>
  <summary>Environment</summary>

  | Browser |  Version  | Operating System |
  | ------- | --------- | ---------------- |
  | chrome | 77.0.3865 | Linux x86_64           |

  **Route:**
  https://codesandbox.io/s/peaceful-shaw-ywio5

  </details>

  <details>
  <summary>Error Message</summary>

  ```bash
  TypeError: Cannot read property 'template' of undefined
  TypeError: Cannot read property 'template' of undefined
    at n.value (https://codesandbox.io/static/js/app.7b7fc602.js:438:433874)
    at https://codesandbox.io/static/js/default~app~embed.959d3548.chunk.js:276:354493
    at f.trackScope (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:1468208)
    at n.<anonymous> (https://codesandbox.io/static/js/default~app~embed.959d3548.chunk.js:276:354462)
    at vs (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2063034)
    at ms (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2062827)
    at Ka (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2097223)
    at Fa (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2081589)
    at Na (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2078609)
    at Ra (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2077169)
    at https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2039070
    at https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2113916
    at co (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2038799)
    at po (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2039016)
    at ho (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2038951)
    at Oa (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2076160)
    at Object.enqueueSetState (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2043805)
    at r.setState (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2335969)
    at https://codesandbox.io/static/js/default~app~embed.959d3548.chunk.js:276:354880
    at https://codesandbox.io/static/js/common.19be7978.chunk.js:1:1467884
    at h.flush (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:1470729)
    at d.flush (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:1467029)
    at Object.cb (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:1355213)
    at e.emit (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:1351588)
    at server.onSSEMessage (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:1357380)
    at https://codesandbox.io/static/js/common.19be7978.chunk.js:1:1356480
    at h.<anonymous> (https://codesandbox.io/static/js/default~app~embed.959d3548.chunk.js:276:234236)
    at h.<anonymous> (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:660685)
    at h.emit (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2401585)
    at h.onconnect (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2403452)
    at h.onpacket (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2402608)
    at h.<anonymous> (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:659603)
    at h.emit (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:660685)
    at h.ondecoded (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2397496)
    at d.<anonymous> (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:659603)
    at d.emit (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:660685)
    at d.add (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2413465)
    at h.ondata (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2397449)
    at u.<anonymous> (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:659603)
    at u.emit (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:660685)
    at u.onPacket (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:832421)
    at f.<anonymous> (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:830033)
    at f.emit (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:660685)
    at f.onPacket (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:837013)
    at f.onData (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:836962)
    at WebSocket.<anonymous> (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:849625)
  
    in n
    in r
    in div
    in t
    in div
    in t
    in div
    in div
    in t
    in styled.div
    in div
    in t
    in elements__Container
    in t
    in n
    in r
    in n
    in r
    in t
    in t
    in div
    in t
    in elements__Content
    in n
    in t
    in withRouter(n)
    in div
    in t
    in elements__Container
    in Unknown
    in t
    in withRouter()
    in DragDropContext(withRouter())
    in t
    in t
    in l
    in t
  ```

  </details>

**Comment by lbogdan** [comment] 2019-10-18 13:18
Closing as duplicate of #2770 , please follow that instead.

**Closed by lbogdan** 2019-10-18 13:18 UTC
