### ISSUE TITLE
Wrong console output

### ISSUE THREAD

**Issue by krutilov** [codesandbox/codesandbox-client#1879] opened 2019-05-10 03:00 UTC
# 🐛 bug report

## How has this issue affected you? What are you trying to accomplish?

I played with arrays and noticed that when I'm modifying an array, the original one modifies in console output too. As you can see on a screenshot, this doesn't happen in a Chrome console.

![error](https://user-images.githubusercontent.com/3627740/57499554-ed17d880-7294-11e9-9108-2e024f05a22a.jpg)

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | 
| Browser | Chrome (Latest)
| Operating System | macOS 10.14.4

**Comment by abdullahtariq1171** [comment] 2019-05-10 09:14
Looks like the issue comes from [console-feed](https://github.com/samdenty/console-feed ) package

See example using console-feed https://codesandbox.io/s/24qp2pz6mr

**Comment by lbogdan** [comment] 2019-05-11 16:43
Closing, as duplicate of #1043 , please subscribe to that for updates.

**Closed by lbogdan** 2019-05-11 16:43 UTC
