### ISSUE TITLE
Can't save files - Network request never completes

### ISSUE THREAD

**Issue by d3dc** [codesandbox/codesandbox-client#1042] opened 2018-08-15 18:58 UTC
# 🐛 bug report

## Description of the problem
I add a new file and put content in it. I cannot save. The dot won't go away, there are no errors. Reloading loses the file.

## How has this issue affected you? What are you trying to accomplish?

I can't save my code to run it.

### Your Environment
| Software         | Name/Version|
| ---------------- | ---------- |
| Сodesandbox  | PROD-1533293248-4a97495
| Browser | Chrome 69.0.3497.32 
| Operating System | Mac OS 10.13.6

**Comment by d3dc** [comment] 2018-08-15 19:00
I reloaded several times without change to the problem. Now it just works with the same content and everything

I don't think Codesandbox had a caching issue, as its still: PROD-1533293248-4a97495

**Comment by CompuIves** [comment] 2018-08-15 19:00
Hey! Do you get any notification in the bottom right when you save? What does your Chrome Developer Tools say in the network tab?

**Comment by d3dc** [comment] 2018-08-15 19:09
Aaand its happening again...

@CompuIves There is no feedback at all when the issue occurs. The network tab does show a pending request that just sits.

```
Request URL: https://codesandbox.io/api/v1/sandboxes/p76ynlqrm0/modules/y3og
Referrer Policy: no-referrer-when-downgrade
Provisional headers are shown
Accept: application/json
Authorization: Bearer 
zoop
Content-Type: application/json; charset=UTF-8
DNT: 1
Origin: https://codesandbox.io
Referer: https://codesandbox.io/s/p76ynlqrm0
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.32 Safari/537.36
{module: {,…}}
--



```

**Comment by CompuIves** [comment] 2018-08-15 20:48
Hmm, that's very weird. I cannot reproduce the problem and our API is responsive (https://updown.io/pqhf), what kind of network (mobile/wifi/ethernet) are you on?

**Comment by d3dc** [comment] 2018-08-15 21:42
I'm on a pretty reliable wifi connection to a cable landline, no proxies. I've been posting here in-between trying to save.

It does seem to work if I just open a new tab with the URL and so far the file recovery feature is now working.

**Comment by CompuIves** [comment] 2018-08-16 13:15
Hmm, that's really weird. Maybe this could be related to Google, from which country are you opening CodeSandbox?

**Comment by deadcoder0904** [comment] 2018-09-14 14:31
@CompuIves same error now. Can't save at all. I'm from India bdw :)

**Comment by deadcoder0904** [comment] 2018-09-14 14:32
And also using Safari

**Comment by skirankumar7** [comment] 2018-10-09 14:07
**I also have same error**

**Comment by skirankumar7** [comment] 2018-10-09 14:20
this error due to **"I am not robot" verification**,
above is not asking in code sandbox,
go to network tab in dev tools,
there select the **first failled response** , and in right side select **preview** you will see  "I am not robot" verification, c**opy that corresponding url** and paste in new tab and complete verification
After that **refresh** your codesandbox.

**Comment by bluedusk** [comment] 2018-11-13 11:38
I got same issue with chrome.
Have you managed to solve this ?

**Comment by deadcoder0904** [comment] 2018-11-14 10:30
I didn't use this for long but I came back again to try it. The worst thing is now happening. It overwrites my one file with other files contents & it happened to me at least 5 times. Makes me not use Sandbox now. Sad but I have to use local environment now as I have to press CMD+Z all the time after saving :(

**Comment by d3dc** [comment] 2018-11-14 11:53
@skirankumar7 Are captcha responses sent through codesandboxes API? I would think these network requests would complete with an authorization error. 

@deadcoder0904 I'm not sure that's the same issue. That sounds like your network requests are completing.

**Comment by CompuIves** [comment] 2018-11-14 12:07
@deadcoder0904 could you specify which editor you're using? I've been seeing some race conditions for the vscode editor.

We do have some verification by Cloudflare against DDOS attacks and other kind of attacks, I lower the sensitivity to see if that improves anything.

**Comment by deadcoder0904** [comment] 2018-11-14 12:15
@CompuIves I'm using VSCode. Should I Switch then?

The thing that happens is if I change some other file, it overwrites the content on my `index.js` file

**Comment by CompuIves** [comment] 2018-11-14 12:17
Yeah that's a bug in VSCode, VSCode is more experimental than Monaco currently, so in Monaco this shouldn't happen. I'm looking into VSCode today.

**Comment by deadcoder0904** [comment] 2018-11-14 12:19
Confirmed, doesn't happen in Monaco. Thanks :)

**Comment by SaraVieira** [comment] 2020-09-02 12:43
Hey!

From when this was posted to now a lot has been fixed in VSCode and it's way more stable so this shouldn't happen anymore

**Closed by SaraVieira** 2020-09-02 12:43 UTC
Labels: API
