### ISSUE TITLE
Code sandbox crashes then "node with that id is already in the Store"

### ISSUE THREAD

**Issue by pixelass** [codesandbox/codesandbox-client#3519] opened 2020-02-14 11:54 UTC
# 🐛 bug report

## Description of the problem
I keep getting this error:

```
frontend.js:10187 Uncaught Error: Cannot add node 1 because a node with that id is already in the Store.
```

## How has this issue affected you? What are you trying to accomplish?
 I can't use my sandbox since it crashes

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | not sure where this is declared (this maybe? PROD-1581626805-0394eb371) |
| Browser          |  Chrome 80.0.3987.106 (Official Build) (64-bit)| 
| Operating System | OS X  10.14.6 (18G3020)|

**Comment by pixelass** [comment] 2020-02-14 12:12
my best effort to work around this issue is turning off auto preview, then saving and reloading.

This show up every time:

<img width="589" alt="Screen Shot 2020-02-14 at 13 10 33" src="https://user-images.githubusercontent.com/1148334/74530855-6d0d5600-4f2b-11ea-9295-aea03ffd9737.png">

After another reload I am able to make try my changes. After every change I have to save and repeat the process described above.

**Comment by iamandrewluca** [comment] 2020-05-20 15:13
Related #3485

**Comment by andrasbacsai** [comment] 2020-09-03 20:29
I cannot reproduce this issue with your sandbox.

Closing now. If you have any question, let us know!

**Closed by andrasbacsai** 2020-09-03 20:29 UTC
