### ISSUE TITLE
Menu dropdown cuts off in "Recent Sandboxes" view

### ISSUE THREAD

**Issue by ovieokeh** [codesandbox/codesandbox-client#3395] opened 2020-01-24 15:53 UTC
# 🐛 bug report

## Description of the problem
When in the "Recent Sandboxes" view, clicking on the dropdown menu on a sandbox close to the bottom results in the bottom half of the menu being cut off with no way to scroll to reveal the cut-off parts.

A GIF would explain this better.

![codesandbox_bug](https://user-images.githubusercontent.com/36507972/73082382-ab35cd80-3ec9-11ea-8a52-6f3d30760016.gif)

## How has this issue affected you? What are you trying to accomplish?
I was trying to delete a sandbox but was unable to because of the bug.

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |
| Browser          | Google Chrome v79.0
| Operating System | Mac OS Catalina

**Comment by garethx** [comment] 2020-01-24 15:55
Thanks for reporting. Closing this specific issue as it's a duplicate of  https://github.com/codesandbox/codesandbox-client/issues/3274

**Closed by garethx** 2020-01-24 15:55 UTC
Labels: 🖨 Duplicate
