### ISSUE TITLE
NextJS sandboxes do not seem to update contents on save

### ISSUE THREAD

**Issue by Rulikkk** [codesandbox/codesandbox-client#4780] opened 2020-08-27 15:53 UTC
# 🐛 bug report

## Description of the problem
Create NextJS sandbox from the official template.
Edit index.js, save changes.
Expected: preview is auto-updated.
Actual: preview is not updated. Manual refresh is required to update.
Note: console says "compiled", so next notices changes.

## How has this issue affected you? What are you trying to accomplish?
Build some new website using NextJS. I remember, this feature used to work.

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | Last, tried hard reload, etc
| Browser          | Mac & Edge
| Operating System | macOS (last)

**Comment by SaraVieira** [comment] 2020-08-31 12:40
Closing as duplicate of #4684

**Closed by SaraVieira** 2020-08-31 12:40 UTC
Labels: SSE
