### ISSUE TITLE
Crashes every time try to create new sandbox - Has happened for over 1 month now

### ISSUE THREAD

**Issue by PapiPeppers** [codesandbox/codesandbox-client#6721] opened 2022-05-28 18:18 UTC
<h1>💥 Crash Report</h1>

  <h2>What were you trying to accomplish when the crash occurred?</h2>

Create a new sandbox

  <h3>Link to sandbox: [link]() (optional)</h3>

  <h3>Crash Details</h3>

  <details>
  <summary>Environment</summary>

  | Browser |  Version  | Operating System | CodeSandbox Version |
  | ------- | --------- | ---------------- | ------------------- |
  | firefox | 102.0.0 | OS X 10.15           | 1db0af43f          |

  **Route:**
  https://codesandbox.io/dashboard/home?workspace=25853048-a7ba-457d-b74f-b26dcc8521ea

 
  </details>

  <details>
  <summary>Error Message</summary>

  ```bash
  TypeError: (destructured parameter) is null
  ../common/lib/utils/get-sandbox-name.js/t.getSandboxName@https://codesandbox.io/static/js/default~app~embed.b0f63c6e2.chunk.js:378:335
./src/app/components/CreateNewSandbox/CreateSandbox/CreateSandbox.tsx/$e/</<@https://codesandbox.io/static/js/app.71c35c901.js:66:377569
./src/app/components/CreateNewSandbox/CreateSandbox/CreateSandbox.tsx/$e/<@https://codesandbox.io/static/js/app.71c35c901.js:66:377220
$e@https://codesandbox.io/static/js/app.71c35c901.js:66:376956
ua@https://codesandbox.io/static/js/common.d909eae2e.chunk.js:1:1789558
xs@https://codesandbox.io/static/js/common.d909eae2e.chunk.js:1:1834821
ml@https://codesandbox.io/static/js/common.d909eae2e.chunk.js:1:1820399
hl@https://codesandbox.io/static/js/common.d909eae2e.chunk.js:1:1820322
il@https://codesandbox.io/static/js/common.d909eae2e.chunk.js:1:1817650
../../node_modules/react-dom/cjs/react-dom.production.min.js/Xo/<@https://codesandbox.io/static/js/common.d909eae2e.chunk.js:1:1775833
../../node_modules/react-dom/node_modules/scheduler/cjs/scheduler.production.min.js/t.unstable_runWithPriority@https://codesandbox.io/static/js/common.d909eae2e.chunk.js:1:1851169
qo@https://codesandbox.io/static/js/common.d909eae2e.chunk.js:1:1775542
Xo@https://codesandbox.io/static/js/common.d909eae2e.chunk.js:1:1775780
Yo@https://codesandbox.io/static/js/common.d909eae2e.chunk.js:1:1775713
se@https://codesandbox.io/static/js/common.d909eae2e.chunk.js:1:1844921
Sn@https://codesandbox.io/static/js/common.d909eae2e.chunk.js:1:1759341

  
    in $e
    in t
    in Ye
    in Je
    in div
    in span
    in styled.span
    in span
    in styled.span
    in div
    in n
    in Styled(n)
    in Unknown
    in st
    in div
    in ForwardRef(p)
    in ForwardRef(p)
    in elements__TabContent
    in div
    in elements__Container
    in De
    in Unknown
    in $n
    in div
    in div
    in div
    in div
    in t
    in t
    in Modal___StyledModal
    in n
    in De
    in Unknown
    in Y
    in n
    in withRouter(n)
    in div
    in elements__Container
    in Unknown
    in withRouter()
    in t
    in Unknown
    in De
    in c
    in t
  ```

  </details>

**Comment by JamesACS** [comment] 2022-06-09 05:13
Duplicate of #6591

**Closed by JamesACS** 2022-06-09 05:13 UTC
