### ISSUE TITLE
Could not find module in path: '@babel/runtime [...]

### ISSUE THREAD

**Issue by justanotheranonymoususer** [codesandbox/codesandbox-client#5589] opened 2021-03-15 19:06 UTC
# 🐛 bug report

## Preflight Checklist

- [x] I have read the
      [Contributing Guidelines](https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md)
      for this project.
- [x] I agree to follow the
      [Code of Conduct](https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md)
      that this project adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem

I created a sandbox, but I see an error when I open it in another tab.

## How has this issue affected you? What are you trying to accomplish?

Share code snippet.

### To Reproduce

See this link where I have this bug, you'll see the error message:
https://i.imgur.com/Hj9KsiC.png

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | Web/latest
| Browser          | Chrome
| Operating System | Win10

**Comment by andrasbacsai** [comment] 2021-03-24 10:14
Unfortunately, I cannot reproduce the issue. Can you please check if it persists on your side? Thanks in advance.

**Comment by justanotheranonymoususer** [comment] 2021-03-24 11:00
Try this link:
https://codesandbox.io/s/confident-bhabha-sense?file=/src/App.js

**Comment by DeMoorJasper** [comment] 2021-04-23 12:28
Issue seems to be the same as fixed by #5690 so once that one's merged this should be resolved

**Closed** 2021-04-30 14:35 UTC
Labels: 🎒 Bundler, 🐛 Bug
