### ISSUE TITLE
all console.logs shows the same value of the last object modification

### ISSUE THREAD

**Issue by Jhonatangiraldo** [codesandbox/codesandbox-client#3160] opened 2019-12-10 14:29 UTC
# 🐛 bug report

## Description of the problem
If I want to do console.logs while editing an object, the logs show the last object information. So let's say I'm incrementing a property of an object, every time I increment the value I do a console.logs. In the sandbox logs, it shows all the logs as the final value of the object property.
This happens with arrays and objects.

![Screenshot from 2019-12-10 09-24-54](https://user-images.githubusercontent.com/6934447/70537856-2405e380-1b2f-11ea-9304-20e7c2297c16.png)

## How has this issue affected you? What are you trying to accomplish?
When I try to do some exercises and I want to see how the object/array is changing, the values displayed in the sandbox console are wrong and don't help me to see the data changes

### Your Environment

All the sandbox no matter what version/template I create

**Comment by lbogdan** [comment] 2019-12-10 14:34
Closing as duplicate of #1043. @Jhonatangiraldo Please subscribe to / comment on that one instead. Thanks!

**Closed by lbogdan** 2019-12-10 14:34 UTC

**Comment by Jhonatangiraldo** [comment] 2019-12-10 15:20
Thank you @lbogdan
