### ISSUE TITLE
Error: Cannot add node 1 because a node with that id is already in the Store

### ISSUE THREAD

**Issue by tariqporter** [codesandbox/codesandbox-client#3485] opened 2020-02-07 20:52 UTC
# 🐛 bug report

## Description of the problem

Creating the default react app immediately causes this issue

`Error: Cannot add node 1 because a node with that id is already in the Store`

![image](https://user-images.githubusercontent.com/8306435/74066308-e0134b80-49c4-11ea-8e9e-f807057f00ec.png)

Clicking on the error, I am shown:

![image](https://user-images.githubusercontent.com/8306435/74064807-73e31880-49c1-11ea-974e-4e585f1f879a.png)

## How has this issue affected you? What are you trying to accomplish?

The application seems to work, but sometimes this results in thousands of errors per second, meaning the console becomes useless.

Refreshing the entire page will stop this from happening until the next time a change is made, then this issue will resume.

### Link to sandbox: [https://codesandbox.io/s/pensive-morning-sewzf](https://codesandbox.io/s/pensive-morning-sewzf)

**Comment by iamandrewluca** [comment] 2020-05-20 15:12
Related #3519

**Comment by andrasbacsai** [comment] 2020-09-03 20:29
I cannot reproduce this issue with your sandbox.

Closing now. If you have any question, let us know!

**Closed by andrasbacsai** 2020-09-03 20:29 UTC

**Comment by McGern** [comment] 2020-09-18 09:43
Hi @andrasbacsai 

I am having the same issue with my sandbox so ended up here from Google.

Tried the linked sandbox in this issue and I can replicate the bug reported by @tariqporter 

![image](https://user-images.githubusercontent.com/2475102/93583202-6d773f00-f99b-11ea-9749-aeb8c2a19f1e.png)

Windows 10
Chrome version 85.0.4183.102 (Official Build) (64-bit)

**Comment by sandrosc** [comment] 2020-11-11 14:33
I just got a similar error message from the react debugger. Perhaps you can disable that plugin and try again?

**Comment by lucksp** [comment] 2020-11-24 20:36
I see this also if I open actual browser DevTools
https://codesandbox.io/s/apollo-rest-route-xpwe9?file=/src/index.js

**Comment by lucksp** [comment] 2020-11-25 18:01
This error happens immediately upon creating a new sandbox from the "React" template for me:  
Untouched sandbox: [https://codesandbox.io/s/nervous-forest-d31s7](https://codesandbox.io/s/nervous-forest-d31s7)

I also have this error in [my WIP sandbox](https://codesandbox.io/s/apollo-rest-route-xpwe9?file=/src/App.js).  However, it seems to be some sort of caching or local storage related issue 🤷‍♂️  The reason I believe this is that if I go to incognito as a visitor (not signed in), I do not see the error.
If I reload chrome it kind of resolves the error.

However, the moment I make **any** new changes while logged in, the original error returns.

The error comes from the `codesandbox-client` "frontend.js" file, inside a switch:
![image](https://user-images.githubusercontent.com/15162169/100151134-f9a35800-2e5d-11eb-8b8d-e0b44ea06d81.png)


Here is a video: https://recordit.co/3ikIo6UVNh

**Comment by nikhil-varma** [comment] 2021-01-29 09:44
I am facing the same issue with the same error in a React Sandbox. Am I missing anything or can someone help me direct to the issue? Thanks in advance! 

![image](https://user-images.githubusercontent.com/8639235/106258794-53504600-6244-11eb-9798-b7ed68ca1319.png)

**Comment by SaraVieira** [comment] 2021-01-29 11:27
@nikhil-varma I can reproduce what you are showing but I downloaded it and it still does not work, I cannot understand why and it seems like a nivo issue but it's not a codesandbox issue :(

**Comment by SaraVieira** [comment] 2021-01-29 11:32
Please keep me updated, I am still checking, I am super curious 🤔

**Comment by nikhil-varma** [comment] 2021-01-29 11:33
@SaraVieira sure thing! Will check out and let you know! :)

**Comment by nikhil-varma** [comment] 2021-01-29 11:51
@SaraVieira I think I may have found the culprit. So the problem was pointing to the html file in the public folder. I had to remove the `<!DOCTYPE html>` line and it start working. 
https://codesandbox.io/s/nivo-sample-line-graph-59i1u

I tried commenting the `<!DOCTYPE html>` line which seems to have it working
![image](https://user-images.githubusercontent.com/8639235/106271815-18570e00-6256-11eb-9a33-255201c9bee2.png)


Do we need to add a specific `manifest.json` file? I thought we generally don't need it either in CSB or even in a create-react-app project? Please correct me if I am wrong. Thanks!

**Comment by SaraVieira** [comment] 2021-01-29 17:56
Interesting, was that all you changed? I just added it back and it still works: https://codesandbox.io/s/nivo-sample-line-graph-forked-eozvg?file=/public/index.html

This is such a mystery ahah

> Do we need to add a specific manifest.json file?

No, we don't use it and CRA mostly uses it for PWA so it's a choice :)

**Comment by nikhil-varma** [comment] 2021-01-29 18:02
@SaraVieira Yep that is all what I have changed. It doesn't seem to work with that line though. Just checked your forked CSB as well. 

Here's a demo:
https://www.loom.com/share/052ac00fb7954eeb86be506154206c08

> No, we don't use it and CRA mostly uses it for PWA so it's a choice :)

Gotcha

**Comment by SaraVieira** [comment] 2021-02-01 17:12
This is so weird, I would say to make an issue in the nivo repo, they may know what is happening

It's very weird because that tag just sets the HTML as HTML5

**Comment by nikhil-varma** [comment] 2021-02-01 17:37
@SaraVieira Makes sense! Will do!

**Comment by y-nk** [comment] 2021-04-26 10:44
I also have this bug :) ... i tried remove the doctype definition ; did not help.

**Comment by ewawiktor** [comment] 2021-05-06 13:34
@y-nk restarting node server helped in my case

**Comment by alexya** [comment] 2021-06-25 00:45
I meet the same issue. any update on it?

**Comment by AstewayYiheyis** [comment] 2021-12-26 01:19
I have the same issue while trying to fetch a data using fetch Api.

**Comment by adarshrathi246** [comment] 2022-01-26 09:33
thanks <a href="https://www.codeexampler.com/php-switch">switch case PHP</a>

**Comment by aliduzdar** [comment] 2022-03-07 15:37
I get this error when using React Native Bugger. Thank you for your help.
Uncaught Error: Cannot add node "1" because a node with that id is already in the Store.

**Comment by JamesACS** [comment] 2022-03-09 15:19
@aliduzdar - Have you tried the restarting node server fix above?
