### ISSUE TITLE
Creating a sandbox from a template does not fork if the template is owned by the same user account

### ISSUE THREAD

**Issue by jsejcksn** [codesandbox/codesandbox-client#2146] opened 2019-07-08 18:10 UTC
# 🐛 bug report

## Description of the problem

1. Create a new sandbox:

![create](https://user-images.githubusercontent.com/868251/60831981-76a63280-a180-11e9-9415-0a5c22f16280.png)
 _(By the way, are these two options the same? The size of the resulting dialog is different depending on which one is selected. I think the **+** button always creates a sandbox for the current signed in user, and is view-agnostic.)_

2. Select a custom template from the dialog that is owned by the same account:

![template-select](https://user-images.githubusercontent.com/868251/60832121-c38a0900-a180-11e9-99e1-7ed4715d2132.png)

3. The resulting view is not a new sandbox, forked from that template, but the template itself:

![sandbox](https://user-images.githubusercontent.com/868251/60832162-d8669c80-a180-11e9-9269-5fd2e0081080.png)

This is an issue if the template is owned by the same user as the one creating the new sandbox. It is not an issue if the user who owns the template is also a member of a team and creates the new sandbox from the team view.

## How has this issue affected you? What are you trying to accomplish?

I want to **create a new sandbox** from a template, and I only want to open the template when I navigate to the template and open it directly.

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | 
| Browser          | Chrome 75.0.3770.100
| Operating System | macOS 10.14.5

**Comment by jsejcksn** [comment] 2020-09-04 12:59
Not stale

**Comment by jsejcksn** [comment] 2020-12-21 02:39
Not stale

**Comment by jsejcksn** [comment] 2021-03-25 04:29
Not stale

**Comment by lbogdan** [comment] 2021-05-28 12:54
Hey @jsejcksn ,

Thanks for your report, and sorry for the quite large delay!

We refactored the UI/UX quite a bit since you opened the issue, and haven't been able to reproduce this on our side. Can you please check and let us know if this is still an issue for you?

**Comment by jsejcksn** [comment] 2021-05-28 13:51
@lbogdan Why did it take 2 years to respond to my issue?

**Comment by CompuIves** [comment] 2021-05-28 14:02
Hey @jsejcksn, that's our fault and something went wrong on our side in responding on this issue, apologies for that. With the new iteration of the template modal we have taken your feedback into account, and when you click on a template now, we will automatically fork it for you. I'll close the issue, as it's now resolved.

**Closed by CompuIves** 2021-05-28 14:02 UTC
Labels: Need Info, UX, 🤔 Improvement

**Comment by CompuIves** [comment] 2021-05-28 14:56
Well, nothing happened (that's the problem), this issue was reported to us and we incorporated the feedback, but we forgot to loop back and mark this issue as closed. We now are more clear on who reports back, but this issue unfortunately was from a time where we didn't have that structure.
