### ISSUE TITLE
Live session editing inserting double HTML tags

### ISSUE THREAD

**Issue by TylerSmall19** [codesandbox/codesandbox-client#2156] opened 2019-07-12 16:19 UTC
# 🐛 bug report

## Description of the problem
When I open a live session on a codesandbox and both of the editors are on the same page (I've only ever tried this with 2 editors in a session), the auto-insertion of closing tags also inserts at the view's cursor. 

The editor presses tab for an auto-insertion, and both the editor and viewer have their cursors moved to that insertion point, and the closing tag for the HTML element is inserted twice. The editor then has to remove the tag and continue working after each closing tag insertion (p tag is the most frequent culprit; I haven't tested other tags)

### Note on work around
I discovered today (which prompted the issue) that a workaround does exist: If both editors are not currently looking at the same file (I.E their cursors are in different files at time of tag auto-insertion) the bug does not appear. This has me thinking it's related to the logic of tag insertion, and I'm assuming the logic is a "forEach" cursor or something of the like, or maybe each cursor is being affected as a side-effect to something.

## How has this issue affected you? What are you trying to accomplish?
We do front-end code interviews with this tool, so the live collab is pretty critical. This issue prevents us from having a great UX when we're in live interviews, which can affect the interview outcome itself.

### Contribution Note
I really like codesandbox.io and would be willing to put some time into a PR for this fix, but I'm not sure where to look for the affected areas, so I thought I'd start with an issue. I would appreciate a quick note with any code areas that might be affecting this for me to start my search.

### Link to sandbox: N/A
This has happened across every live session I've tried to open recently.

### Your Environment
React App Template sandbox base, live collaboration

| Browser          | Chrome, Version 75.0.3770.100,
| Operating System | Windows 10 Professional, 64 Bit

**Comment by dejay-at-work** [comment] 2019-07-24 18:33
I've seen a number of related behaviors when multiple editors simultaneously edit the same file.  I suspect that one of the user's local sync state is becoming invalid, and that then seems to mess up anyone else editing at the same time.

Once, a user was editing a file during a Live session, and started having problems with the syntax highlighting and autocompletion not working properly.  I was merely observing the same file, using my own user account via Live session.  In an attempt to see if I could "unstick" the user's corrupted state, I started typing a few characters.  When I did, various parts of the code, near where I was typing, started being inserted in an inconsistent way not related to the specific characters I was typing.

**Comment by TylerSmall19** [comment] 2019-07-26 05:15
@dejay-at-work 

Did the above workaround (not looking into the same file at the same time) work for this issue? It could be a legitimate work around, though inconvenient.

> I discovered today (which prompted the issue) that a workaround does exist: If both editors are not currently looking at the same file (I.E their cursors are in different files at time of tag auto-insertion) the bug does not appear. This has me thinking it's related to the logic of tag insertion, and I'm assuming the logic is a "forEach" cursor or something of the like, or maybe each cursor is being affected as a side-effect to something.

**Comment by dejay-at-work** [comment] 2019-07-26 13:04
@TylerSmall19 since I use CodeSandBox for remote interviews, not observing the file isn't that viable for me.

I've filed the following issue, hopefully the fixes associated with it will resolve all the issues I witnessed.

https://github.com/codesandbox/codesandbox-client/issues/2208

**Comment by CompuIves** [comment] 2019-07-26 16:00
Yep, I noticed the issue as well. After my fixes it only happens when both cursors are at the same position (so both cursors are at eg. `<h2>`) for me. Do others experience it this way as well?

**Comment by jeroenvisser101** [comment] 2019-08-05 12:34
@CompuIves are these fixes live? If so, we still experience this to this day.

**Comment by jayenashar** [comment] 2019-11-23 23:13
@oddswop and i are still experiencing this issue.

**Comment by namibj** [comment] 2020-01-30 22:16
I can confirm this is (still?) broken. We were editing different sections of a simple static HTML file, and the closing-tag autocomplete doubled up, resulting in two closing tags getting inserted, and the collaborator's cursor getting moved to my position, mangling it up even worse if we are both actually typing simultaneously.

**Comment by iongion** [comment] 2020-05-31 19:23
:( sadly this is still happening, was teaching a friend yesterday some d3 and when she moved to her own screen (a computer resuming from sleep at a past version of my shared sandbox), my original sandbox (which had diffs of course)  suddenly inserted lots of lines in the html.

It also inserts weird unrelated / old lines in any file, js or css

**Comment by CompuIves** [comment] 2020-06-01 08:52
A fix for this should be live now, I think that the issue you mentioned @iongion might be a different one, where a lot of old messages where queued up on the PC and were sent. We should add more validation there, to make sure that no stale messages are sent. I can close this one and open a new issue for the last one!

**Closed by CompuIves** 2020-06-01 08:52 UTC
Labels: 🐛 Bug
