### ISSUE TITLE
Codesandbox loads slow if external resource (CSS) is not found

### ISSUE THREAD

**Issue by deadcoder0904** [codesandbox/codesandbox-client#4284] opened 2020-06-02 09:58 UTC
# 🐛 bug report

## Description of the problem

Currently, https://newcss.net/lite.css is down & I am using it in my `External Resources`. This makes my Codesandbox really slow.

## How has this issue affected you? What are you trying to accomplish?

It takes ~30 seconds to 1 minute for Codesandbox to load which makes me question if my code is wrong or the issue is with codesandbox thanks to slower feedback loops.

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | Latest
| Browser          | Version 83.0.4103.61 (Official Build) (64-bit)
| Operating System | Windows 10 Pro

**Comment by CodeSandboxNotifications** [comment] 2020-06-02 11:50
Hello Akshay!


I see that the service is up and running again so not able to immediately reproduce the issue. Before I try to reproduce in other ways, could you please explain in more detail what you mean by slow? Does it take a long time to load the sandbox, is the preview slow or is something else experienced as slow?


If the preview is slow it is because <link /> tags are blocking. Meaning that if the service was not responding it would block your whole page. This is not really a Codesandbox related issue, but a general issue with the web and blocking <link /> elements.


Glad that is seems to be working now!

—
Christian Alfoni

--- original message ---
On June 2, 2020, 11:58 AM GMT+2 notifications@github.com wrote:



🐛 bug report

Description of the problem

Currently, https://newcss.net/lite.css is down & I am using it in my External Resources. This makes my Codesandbox really slow.

How has this issue affected you? What are you trying to accomplish?

Link to sandbox: link (optional) demo

Your Environment
Software Name/Version 
Сodesandbox Latest 
Browser Version 83.0.4103.61 (Official Build) (64-bit) 
Operating System Windows 10 Pro 


—

You are receiving this because you are subscribed to this thread.

Reply to this email directly, view it on GitHub, or unsubscribe.
--- end of original message ---

**Comment by deadcoder0904** [comment] 2020-06-02 13:30
The preview was slow.

> <link /> tags are blocking

Yep I know that one so I closed the issue once but it was happening again & again so I opened it finally haha.

Close this if this isn't fixable on your end :)

**Comment by deadcoder0904** [comment] 2020-06-02 13:31
But the site is still down for me at least https://newcss.net/lite.css

**Comment by lbogdan** [comment] 2020-06-02 15:45
Closing this, as https://newcss.net/lite.css also works for me. I'd suggest to put the CSS in a file inside the sandbox, as you can't access it, I'll paste the contents here:
```
:root{--nc-font-sans:Inter,-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Oxygen,Ubuntu,Cantarell,'Open Sans','Helvetica Neue',sans-serif,"Apple Color Emoji","Segoe UI Emoji","Segoe UI Symbol";--nc-font-mono:Consolas,monaco,'Ubuntu Mono','Liberation Mono','Courier New',Courier,monospace;--nc-tx-1:#000;--nc-tx-2:#1A1A1A;--nc-bg-1:#FFF;--nc-bg-2:#F6F8FA;--nc-bg-3:#E5E7EB;--nc-lk-1:#0070F3;--nc-lk-2:#0366D6;--nc-lk-tx:#FFF;--nc-ac-1:#79FFE1;--nc-ac-tx:#0C4047}@media (prefers-color-scheme: dark){:root{--nc-tx-1:#fff;--nc-tx-2:#eee;--nc-bg-1:#000;--nc-bg-2:#111;--nc-bg-3:#222;--nc-lk-1:#3291FF;--nc-lk-2:#0070F3;--nc-lk-tx:#FFF;--nc-ac-1:#7928CA;--nc-ac-tx:#FFF}}*{margin:0;padding:0}address,area,article,aside,audio,blockquote,datalist,details,dl,fieldset,figure,form,input,iframe,img,meter,nav,ol,optgroup,option,output,p,pre,progress,ruby,section,table,textarea,ul,video{margin-bottom:1rem}html,input,select,button{font-family:var(--nc-font-sans)}body{margin:0 auto;max-width:750px;padding:2rem;border-radius:6px;overflow-x:hidden;word-break:break-word;overflow-wrap:break-word;background:var(--nc-bg-1);color:var(--nc-tx-2);font-size:1.03rem;line-height:1.5}::selection{background:var(--nc-ac-1);color:var(--nc-ac-tx)}p{margin-bottom:1rem}h1,h2,h3,h4,h5,h6{line-height:1;color:var(--nc-tx-1);padding-top:.875rem}h1,h2,h3{color:var(--nc-tx-1);padding-bottom:2px;margin-bottom:8px;border-bottom:1px solid var(--nc-bg-2)}h4,h5,h6{margin-bottom:.3rem}h1{font-size:2.25rem}h2{font-size:1.85rem}h3{font-size:1.55rem}h4{font-size:1.25rem}h5{font-size:1rem}h6{font-size:.875rem}a{color:var(--nc-lk-1)}a:hover{color:var(--nc-lk-2)}abbr:hover{cursor:help}blockquote{padding:1.5rem;background:var(--nc-bg-2);border-left:5px solid var(--nc-bg-3)}abbr{cursor:help}blockquote :last-child{padding-bottom:0;margin-bottom:0}header{background:var(--nc-bg-2);border-bottom:1px solid var(--nc-bg-3);padding:2rem 1.5rem;margin:-2rem calc(0px - (50vw - 50%)) 2rem;padding-left:calc(50vw - 50%);padding-right:calc(50vw - 50%)}header h1,header h2,header h3{padding-bottom:0;border-bottom:0}header > :first-child{margin-top:0;padding-top:0}header > :last-child{margin-bottom:0}a button,button,input[type="submit"],input[type="reset"],input[type="button"]{font-size:1rem;display:inline-block;padding:6px 12px;text-align:center;text-decoration:none;white-space:nowrap;background:var(--nc-lk-1);color:var(--nc-lk-tx);border:0;border-radius:4px;box-sizing:border-box;cursor:pointer;color:var(--nc-lk-tx)}a button[disabled],button[disabled],input[type="submit"][disabled],input[type="reset"][disabled],input[type="button"][disabled]{cursor:default;opacity:.5;cursor:not-allowed}a button:focus,a button:hover,button:focus,button:hover,input[type="submit"]:focus,input[type="submit"]:hover,input[type="reset"]:focus,input[type="reset"]:hover,input[type="button"]:focus,input[type="button"]:hover{background:var(--nc-lk-2)}code,pre,kbd,samp{font-family:var(--nc-font-mono)}code,samp,kbd,pre{background:var(--nc-bg-2);border:1px solid var(--nc-bg-3);border-radius:4px;padding:3px 6px;font-size:.9rem}kbd{border-bottom:3px solid var(--nc-bg-3)}pre{padding:1rem 1.4rem;max-width:100%;overflow:auto}pre code{background:inherit;font-size:inherit;color:inherit;border:0;padding:0;margin:0}code pre{display:inline;background:inherit;font-size:inherit;color:inherit;border:0;padding:0;margin:0}details{padding:.6rem 1rem;background:var(--nc-bg-2);border:1px solid var(--nc-bg-3);border-radius:4px}summary{cursor:pointer;font-weight:700}details[open]{padding-bottom:.75rem}details[open] summary{margin-bottom:6px}details[open]>:last-child{margin-bottom:0}dt{font-weight:700}dd::before{content:'→ '}hr{border:0;border-bottom:1px solid var(--nc-bg-3);margin:1rem auto}fieldset{margin-top:1rem;padding:2rem;border:1px solid var(--nc-bg-3);border-radius:4px}legend{padding:auto .5rem}table{border-collapse:collapse;width:100%}td,th{border:1px solid var(--nc-bg-3);text-align:left;padding:.5rem}th{background:var(--nc-bg-2)}tr:nth-child(even){background:var(--nc-bg-2)}table caption{font-weight:700;margin-bottom:.5rem}textarea{max-width:100%}ol,ul{padding-left:2rem}li{margin-top:.4rem}ul ul,ol ul,ul ol,ol ol{margin-bottom:0}mark{padding:3px 6px;background:var(--nc-ac-1);color:var(--nc-ac-tx)}textarea,select,input{padding:6px 12px;margin-bottom:.5rem;background:var(--nc-bg-2);color:var(--nc-tx-2);border:1px solid var(--nc-bg-2);border-radius:4px;box-shadow:none;box-sizing:border-box}textarea:focus,select:focus,input[type]:focus{border:1px solid var(--nc-bg-3);outline:0}img{max-width:100%}
```

**Closed by lbogdan** 2020-06-02 15:45 UTC

**Comment by deadcoder0904** [comment] 2020-06-02 16:31
Ah thanks @lbogdan, I can apparently access it via a VPN (UK) as I need `night.css` as well :)
