### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by brownsf** [codesandbox/codesandbox-client#2637] opened 2019-10-04 01:06 UTC
<h1>💥 Crash Report</h1>

  <h2>What were you trying to accomplish when the crash occurred?</h2>

  > Please use this issue template to describe what you were doing when you encountered this crash. While we are able to fill in some details automatically, it's not always enough to reproduce!

  <h3>Link to sandbox: [link]() (optional)</h3>

  <h3>Crash Details</h3>

  <details>
  <summary>Environment</summary>

  | Browser |  Version  | Operating System |
  | ------- | --------- | ---------------- |
  | chrome | 77.0.3865 | OS X 10.14.4           |

  **Route:**
  https://codesandbox.io/dashboard/recent

  </details>

  <details>
  <summary>Error Message</summary>

  ```bash
  TypeError: Cannot read property 'collections' of undefined
  TypeError: Cannot read property 'collections' of undefined
    at Object.children (https://codesandbox.io/static/js/app.e345c11d.js:438:277408)
    at n (https://codesandbox.io/static/js/vendors~app.ab650e77.chunk.js:1:753765)
    at t.render (https://codesandbox.io/static/js/vendors~app.ab650e77.chunk.js:1:753863)
    at vs (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2063034)
    at ms (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2062827)
    at Ka (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2097223)
    at Fa (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2081589)
    at Na (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2078609)
    at Ra (https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2077169)
    at https://codesandbox.io/static/js/common.19be7978.chunk.js:1:2039070
  
    in t
    in div
    in t
    in t
    in n
    in div
    in n
    in t
    in withRouter(n)
    in DropTarget(withRouter(n))
    in div
    in t
    in elements__Items
    in Unknown
    in r
    in t
    in aside
    in t
    in elements__SidebarStyled
    in n
    in r
    in t
    in withRouter(r)
    in div
    in t
    in elements__Sidebar
    in div
    in div
    in t
    in elements__Container
    in n
    in r
    in t
    in withRouter(r)
    in t
    in t
    in div
    in t
    in elements__Content
    in n
    in t
    in withRouter(n)
    in div
    in t
    in elements__Container
    in Unknown
    in r
    in t
    in withRouter(r)
    in DragDropContext(withRouter(r))
    in t
    in t
    in l
    in t
  ```

  </details>

**Comment by lbogdan** [comment] 2019-10-18 14:51
Closing as duplicate of #2792 , please follow that instead.

**Closed by lbogdan** 2019-10-18 14:51 UTC
