### ISSUE TITLE
CodeSandBox not loading in Google Chrome 83. Works in Edge 83 with imported chrome settings without issue.

### ISSUE THREAD

**Issue by vurghus-minar** [codesandbox/codesandbox-client#4369] opened 2020-06-15 07:50 UTC
# 🐛  <---- (| Bug report

## Description of the problem

Sandboxes are not loading in Google Chrome Version 83.0.4103.97 (Official Build) (64-bit)
Same machine, Edge Version 83.0.478.45 (Official build) (64-bit) loads fine.

Similarly behavior observed if installed app locally.

Apps hangs, refer to screenshots:
[Screenshot](https://prnt.sc/szwd53)
![csb app](https://user-images.githubusercontent.com/32111718/84636734-f480cb00-af05-11ea-81cc-ed0a8a9dd9b6.png)

## How has this issue affected you? What are you trying to accomplish?

I am unable to use the application on Chrome.

### Link to sandbox: [link]() (optional)
This is an example but as it stands nothing works on my Chrome.
https://codesandbox.io/s/happy-babbage-jqjjz

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |  PROD-1592074315-26943d313
| Browser          | Google Chrome Version 83.0.4103.97 (Official Build) (64-bit)
| Operating System | Windows 10 v1909

**Comment by lbogdan** [comment] 2020-06-15 11:39
Hey @vurghus-minar ,

The `csb.app` domain is currently suspended by Google, you can read more about this here: #3751 . That shouldn't break sandboxes though, as we have an automatic fallback to `codesandbox.io`. I'll try to replicate this and get back to you soon.

**Comment by lbogdan** [comment] 2020-06-15 11:47
Unfortunately I can't reproduce it, with exactly the same versions of Chrome and Windows. Have you tried opening CodeSandbox in an incognito window?

**Comment by NawarA** [comment] 2020-06-15 19:26
I'm having the same issue

![image](https://user-images.githubusercontent.com/2067616/84697712-78858380-af03-11ea-9771-8df74f2cbb0b.png)

**Comment by lbogdan** [comment] 2020-06-16 09:25
@NawarA No, that should definitely be `codesandbox.io`; we're using CodeSandbox ourselves extensively, and we've never seen that weird URL, so I'd say it wasn't a bug or anything on our side.

In the meanwhile the main sandboxes domain `csb.app` was unblocked, so everything should be back to normal. Can you both confirm this is no longer an issue? Thanks!

**Comment by vurghus-minar** [comment] 2020-06-16 11:10
> Unfortunately I can't reproduce it on my side, with exactly the same versions of Chrome and Windows. Have you tried opening CodeSandbox in an incognito window?

@lbogdan @NawarA 
Oddly enough, the following works both in normal browsing and incognito mode.
https://g9b11.codesandbox.io/
https://g9b11.csb.app/

But https://codesandbox.io/s/recursing-bardeen-g9b11 loads only in incognito mode.

My initial thought was perhaps a conflict with my extensions but (a) Edge has the exact same extensions installed, (b) everything loads fine in Edge, (c) disabling all extensions did not have any effect.

The Google Chrome version is Google Chrome Version 83.0.4103.97 (Official Build) (64-bit).

A strange issue indeed...For now, I am resorting to using Edge Version 83.0.478.45 (Official build) (64-bit) but with two Chromes open, the resource drain is making me cry :(

@NawarA
Unfortunately, I cannot confirm what you are describing.

**Comment by vurghus-minar** [comment] 2020-06-16 11:19
@NawarA @lbogdan 

I managed to fix the issue by clearing the application storage in Google Chrome.

Worth noting that I previously, in vain, cleared the browser data, cookies, and history in an attempt to solve this.

![csb app 2](https://user-images.githubusercontent.com/32111718/84768082-a8f11e80-afe4-11ea-92bc-d33dc8782515.png)

**Comment by NawarA** [comment] 2020-06-16 17:47
I think what I observed was an issue in the release two builds ago. Its no longer an issue on my end

**Comment by SaraVieira** [comment] 2020-06-17 15:57
Glad it was fixed, thank you for making the issue 

Gonna close since it has been fixed with releases

Feel free to open again :)

**Closed by SaraVieira** 2020-06-17 15:57 UTC
Labels: Need Info
