### ISSUE TITLE
Not all sandboxes in `ci.json` are built during PR reviewing

### ISSUE THREAD

**Issue by joshuaellis** [codesandbox/codesandbox-client#5872] opened 2021-06-04 18:14 UTC
# 🐛 bug report

## Preflight Checklist

- [x] I have read the [Contributing Guidelines][contributing] for this project.
- [x] I agree to follow the [Code of Conduct][code_of_conduct] that this project
      adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem
Our complete list of sandboxes in [`react-spring`](https://github.com/pmndrs/react-spring) is about [20](https://github.com/pmndrs/react-spring/blob/master/.codesandbox/ci.json). But only 10 seem to be built from the configuration, as seen in a recent [PR](https://ci.codesandbox.io/status/pmndrs/react-spring/pr/1475) but sometimes when there are more sandboxes in the issue or PR they are still built as can be seen in this [PR](https://ci.codesandbox.io/status/pmndrs/react-spring/pr/1444). 

Maybe i've done something wrong? Or maybe there's a maximum and it needs documenting?

## How has this issue affected you? What are you trying to accomplish?

I'm unable to actually test against all the demo sandboxes we have.

### To Reproduce

Make a PR in `react-spring` and you'll see.

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |              |
| Browser          |              |
| Operating System |              |

[code_of_conduct]: https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md
[contributing]: https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md

**Comment by DeMoorJasper** [comment] 2021-06-07 14:10
Thanks for the bug report, @lbogdan do you know why this is happening?

**Comment by joshuaellis** [comment] 2021-06-29 17:32
Hey, Is there any update on this? It's a slight hinderance having to check each PRs sandboxes manually by pulling their branch 😞

**Comment by lbogdan** [comment] 2021-07-12 10:43
Hey @joshuaellis ,

Sorry for the delay, I'll take a look at it this week!

**Comment by lbogdan** [comment] 2021-07-12 10:57
@joshuaellis Indeed, we have a limit of 10 forked sandboxes per build, mostly as an anti-abuse measure.

I went over this with @CompuIves and decided to increase it to 25. I'll let you know when it's deployed.

**Comment by joshuaellis** [comment] 2021-07-12 11:02
Ah I didn't know there was a limit, makes sense! Are the docs website OS? I don't mind making a PR to include this (or maybe it's already there and I missed it?)

**Comment by lbogdan** [comment] 2021-07-12 11:22
It doesn't seem to be documented, the CodeSandbox CI documentation source part of this repository, at https://github.com/codesandbox/codesandbox-client/blob/master/packages/homepage/content/docs/8-ci.md .

**Comment by lbogdan** [comment] 2021-07-12 12:57
We just deployed the new limit of 25, I triggered a build on an open PR, you can check the result here: https://ci.codesandbox.io/status/pmndrs/react-spring/pr/1597/builds/149193 . 

I also noticed what seems to be a typo here: https://github.com/pmndrs/react-spring/blob/aac4adaf2e948d165566bdae283b540135ec133e/.codesandbox/ci.json#L18 - looking at https://github.com/pmndrs/react-spring/tree/master/demo/src/sandboxes it seems like that should be `trail` instead of `train`.

**Comment by joshuaellis** [comment] 2021-07-15 21:19
Ah great catch. Thank you for that. I'm submitting a PR for the doc updates this evening. Thanks for applying that update! ⭐

**Comment by joshuaellis** [comment] 2022-05-05 20:53
Sorry to res this again, but this issue has cropped up again, barely any of the sandboxes are being made from the PR, see:

* https://ci.codesandbox.io/status/pmndrs/react-spring/pr/1886
* https://github.com/pmndrs/react-spring/pull/1886

**Comment by lbogdan** [comment] 2022-07-21 15:40
Hey @joshuaellis ,

Just saw your tweet. Sorry, we completely missed your latest comment (in hindsight, we should've closed this back when we solved it).

Right now the `pmndrs/react-spring` triggers a repository size limit in our GitHub importer, most probably caused by the growth of the repository.

We're looking at ways to increase this limit and will get back to you shortly!

**Comment by joshuaellis** [comment] 2022-07-21 15:51
> Hey @joshuaellis ,
> 
> 
> 
> Just saw your tweet. Sorry, we completely missed your latest comment (in hindsight, we should've closed this back when we solved it).
> 
> 
> 
> Right now the `pmndrs/react-spring` triggers a repository size limit in our GitHub importer, most probably caused by the growth of the repository.
> 
> 
> 
> We're looking at ways to increase this limit and will get back to you shortly!

Thanks for getting back to me! No worries on the delay, it happens. 

When you talk about size limit, is this around the size of the repo of the amount of sandboxes? 

I'm just wondering if perhaps there's anything I can do in the meantime as a workaround?? 

If I'm honest, it's mainly when it builds the sandbox referenced in the issue that's most helpful for me. If it is about limitations on the amount of sandboxes I have added, I could reduce that.

**Comment by lbogdan** [comment] 2022-07-21 16:22
It's about the size of the repository archive that we download using the [Download a repository archive (zip)](https://docs.github.com/en/rest/repos/contents#download-a-repository-archive-zip) GitHub API endpoint. Right now we have an 128MB limit for that, and `pmndrs/react-spring` is ~205MB.

**Comment by joshuaellis** [comment] 2022-07-21 16:57
Thanks for clarifying. Not sure there's much I can do on that for now. But I'll certainly investigate.

**Comment by lbogdan** [comment] 2022-07-21 17:41
Looking inside the archive, indeed, `/.yarn` folder is ~216MB, which is ~98% of the total size.

**Comment by joshuaellis** [comment] 2022-07-22 17:43
Yep, to confirm, this did solve my issue, however maybe this should be kept open until a. the PR #5968 is merged & b. maybe the size is increased to accommodate repos using plug & play yarn3?

**Comment by aj-foster** [comment] 2022-07-25 17:57
Just merged — thank you 🙂

**Closed by aj-foster** 2022-07-25 17:57 UTC
Labels: 🐛 Bug, CodeSandbox CI
