### ISSUE TITLE
crash log

### ISSUE THREAD

**Issue by lich-yoo** [codesandbox/codesandbox-client#2824] opened 2019-10-17 06:21 UTC
<h1>💥 Crash Report</h1>

  <h2>What were you trying to accomplish when the crash occurred?</h2>

  > Please use this issue template to describe what you were doing when you encountered this crash. While we are able to fill in some details automatically, it's not always enough to reproduce!

  <h3>Link to sandbox: [link]() (optional)</h3>

  <h3>Crash Details</h3>

  <details>
  <summary>Environment</summary>

  | Browser |  Version  | Operating System |
  | ------- | --------- | ---------------- |
  | chrome | 77.0.3865 | Windows Server 2008 R2 / 7           |

  **Route:**
  https://codesandbox.io/s/hungry-wildflower-rzo8i

  </details>

  <details>
  <summary>Error Message</summary>

  ```bash
  TypeError: Cannot read property 'template' of undefined
  TypeError: Cannot read property 'template' of undefined
    at n.value (https://codesandbox.io/static/js/app.339c82d8.js:438:320855)
    at https://codesandbox.io/static/js/default~app~embed.5b5df316.chunk.js:276:345435
    at h.trackScope (https://codesandbox.io/static/js/common.d3482b2c.chunk.js:1:1468692)
    at n.<anonymous> (https://codesandbox.io/static/js/default~app~embed.5b5df316.chunk.js:276:345404)
    at vs (https://codesandbox.io/static/js/common.d3482b2c.chunk.js:1:2063518)
    at ms (https://codesandbox.io/static/js/common.d3482b2c.chunk.js:1:2063311)
    at Ka (https://codesandbox.io/static/js/common.d3482b2c.chunk.js:1:2097707)
    at Fa (https://codesandbox.io/static/js/common.d3482b2c.chunk.js:1:2082073)
    at Na (https://codesandbox.io/static/js/common.d3482b2c.chunk.js:1:2079093)
    at Ra (https://codesandbox.io/static/js/common.d3482b2c.chunk.js:1:2077653)
    at https://codesandbox.io/static/js/common.d3482b2c.chunk.js:1:2039554
    at https://codesandbox.io/static/js/common.d3482b2c.chunk.js:1:2114400
    at co (https://codesandbox.io/static/js/common.d3482b2c.chunk.js:1:2039283)
    at po (https://codesandbox.io/static/js/common.d3482b2c.chunk.js:1:2039500)
    at ho (https://codesandbox.io/static/js/common.d3482b2c.chunk.js:1:2039435)
    at Oa (https://codesandbox.io/static/js/common.d3482b2c.chunk.js:1:2076644)
    at Object.enqueueSetState (https://codesandbox.io/static/js/common.d3482b2c.chunk.js:1:2044289)
    at r.setState (https://codesandbox.io/static/js/common.d3482b2c.chunk.js:1:2336453)
    at https://codesandbox.io/static/js/default~app~embed.5b5df316.chunk.js:276:345815
    at https://codesandbox.io/static/js/common.d3482b2c.chunk.js:1:1468368
    at p.flush (https://codesandbox.io/static/js/common.d3482b2c.chunk.js:1:1471213)
    at flush (https://codesandbox.io/static/js/common.d3482b2c.chunk.js:1:1467513)
    at Object.cb (https://codesandbox.io/static/js/common.d3482b2c.chunk.js:1:1355651)
    at e.emit (https://codesandbox.io/static/js/common.d3482b2c.chunk.js:1:1351965)
    at internal.updateCurrentSandbox (https://codesandbox.io/static/js/common.d3482b2c.chunk.js:1:1357818)
    at Proxy.<anonymous> (https://codesandbox.io/static/js/common.d3482b2c.chunk.js:1:1356918)
    at https://codesandbox.io/static/js/default~app~embed.5b5df316.chunk.js:276:269296
    at a (https://codesandbox.io/static/js/common-sandbox.f352477c.chunk.js:1:14585)
    at Generator._invoke (https://codesandbox.io/static/js/common-sandbox.f352477c.chunk.js:1:14373)
    at Generator.e.<computed> [as next] (https://codesandbox.io/static/js/common-sandbox.f352477c.chunk.js:1:15007)
    at t (https://codesandbox.io/static/js/common-sandbox.f352477c.chunk.js:1:8537)
    at u (https://codesandbox.io/static/js/common-sandbox.f352477c.chunk.js:1:8747)
  
    in n
    in r
    in div
    in t
    in div
    in t
    in div
    in div
    in t
    in styled.div
    in div
    in t
    in elements__Container
    in t
    in n
    in r
    in n
    in r
    in t
    in t
    in div
    in t
    in elements__Content
    in n
    in t
    in withRouter(n)
    in div
    in t
    in elements__Container
    in Unknown
    in t
    in withRouter()
    in DragDropContext(withRouter())
    in t
    in t
    in l
    in t
  ```

  </details>

**Comment by lbogdan** [comment] 2019-10-18 12:58
Closing as duplicate of #2770 .

**Closed by lbogdan** 2019-10-18 12:58 UTC
