### ISSUE TITLE
"Something went wrong" for https://codesandbox.io/s/vue-3

### ISSUE THREAD

**Issue by tony19** [codesandbox/codesandbox-client#5075] opened 2020-11-02 03:54 UTC
# 🐛 bug report

## Preflight Checklist

- [x] I have read the
      [Contributing Guidelines](https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md)
      for this project.
- [x] I agree to follow the
      [Code of Conduct](https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md)
      that this project adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem

The official Vue 3 sandbox is erroring out with "Something went wrong" (404).

<img width="792" alt="Screen Shot 2020-11-01 at 9 50 22 PM" src="https://user-images.githubusercontent.com/26580/97828445-b9045480-1c8c-11eb-8d78-02b7208e77e8.png">

## How has this issue affected you? What are you trying to accomplish?

I'm unable to create a sandbox of the official Vue 3 template.

### To Reproduce

Go to https://codesandbox.io/s/vue-3 (or https://v3.vue.new)

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | `0306f6b9e`
| Browser          | Chrome Version 86.0.4240.111 (Official Build) (x86_64) |
| Operating System | macOS Catalina 10.15.7 |

**Comment by CodeSandboxTeam** [comment] 2020-11-02 10:02
Thanks for your report! It indeed seems to be , and am going to restore (or replace) it. I'll comment here and close the issue when it's back!



--- original message ---
On November 2, 2020, 4:54 AM GMT+1 notifications@github.com wrote:



🐛 bug report

Preflight Checklist

I have read the

Contributing Guidelines

for this project.

I agree to follow the

Code of Conduct

that this project adheres to.

I have searched the issue tracker for an issue that matches the one I want

to file, without success.


Description of the problem

The official Vue 3 sandbox is erroring out with "Something went wrong" (404).


How has this issue affected you? What are you trying to accomplish?

To Reproduce

Go to https://codesandbox.io/s/vue-3 (or https://v3.vue.new)

Link to sandbox: link

Your Environment
Software Name/Version 
Сodesandbox 0306f6b9e 
Browser Chrome Version 86.0.4240.111 (Official Build) (x86_64) 
Operating System macOS Catalina 10.15.7 


—

You are receiving this because you are subscribed to this thread.

Reply to this email directly, view it on GitHub, or unsubscribe.
--- end of original message ---

**Comment by SaraVieira** [comment] 2020-11-13 15:48
The sandbox has been restored, we forgot to come back to the issue

Thank you for your report!

**Closed by SaraVieira** 2020-11-13 15:48 UTC
