### ISSUE TITLE
💥 Crash Report: <Please Add a Short Description of Crash Circumstances>

### ISSUE THREAD

**Issue by ridhamz** [codesandbox/codesandbox-client#2506] opened 2019-09-24 16:51 UTC
<h1>💥 Crash Report</h1>

<h2>What were you trying to accomplish when the crash occurred?</h2>

> Please use this issue template to describe what you were doing when you encountered this crash. While we are able to fill in some details automatically, it's not always enough to reproduce!

<h3>Link to sandbox: [link]() (optional)</h3>

<h3>Crash Details</h3>

<details>
<summary>Environment</summary>

| Browser |  Version  | Operating System |
| ------- | --------- | ---------------- |
| chrome | 76.0.3809 | Windows 10           |

**Route:**
https://codesandbox.io/s/reactshoppingcart-122vv

</details>

<details>
<summary>Error Message</summary>

```bash
NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at zs (https://codesandbox.io/static/js/common.8fd6ed86.chunk.js:1:2071605)
    at Is (https://codesandbox.io/static/js/common.8fd6ed86.chunk.js:1:2069800)
    at Ps (https://codesandbox.io/static/js/common.8fd6ed86.chunk.js:1:2069843)
    at zs (https://codesandbox.io/static/js/common.8fd6ed86.chunk.js:1:2071527)
    at https://codesandbox.io/static/js/common.8fd6ed86.chunk.js:1:2090358
    at t.unstable_runWithPriority (https://codesandbox.io/static/js/common.8fd6ed86.chunk.js:1:2113545)
    at co (https://codesandbox.io/static/js/common.8fd6ed86.chunk.js:1:2038428)
    at Ua (https://codesandbox.io/static/js/common.8fd6ed86.chunk.js:1:2088161)
    at Ra (https://codesandbox.io/static/js/common.8fd6ed86.chunk.js:1:2076798)
    at https://codesandbox.io/static/js/common.8fd6ed86.chunk.js:1:2038699
    at t.unstable_runWithPriority (https://codesandbox.io/static/js/common.8fd6ed86.chunk.js:1:2113545)
    at co (https://codesandbox.io/static/js/common.8fd6ed86.chunk.js:1:2038428)
    at po (https://codesandbox.io/static/js/common.8fd6ed86.chunk.js:1:2038645)
    at ho (https://codesandbox.io/static/js/common.8fd6ed86.chunk.js:1:2038580)
    at Ie (https://codesandbox.io/static/js/common.8fd6ed86.chunk.js:1:2106622)
    at Pn (https://codesandbox.io/static/js/common.8fd6ed86.chunk.js:1:2028538)
    at https://codesandbox.io/static/js/common.8fd6ed86.chunk.js:1:2028148
    at HTMLDocument.r (https://codesandbox.io/static/js/common.8fd6ed86.chunk.js:1:122867)

    in elements__Container
    in div
    in Fr
    in div
    in t
    in elements__Right
    in div
    in t
    in elements__EntryContainer
    in div
    in t
    in div
    in n
    in DragSource(n)
    in div
    in t
    in elements__EntryContainer
    in div
    in n
    in r
    in DropTarget(r)
    in div
    in n
    in r
    in div
    in t
    in elements__Opener
    in div
    in n
    in r
    in DropTarget(r)
    in div
    in n
    in r
    in div
    in t
    in elements__Opener
    in div
    in n
    in r
    in DropTarget(r)
    in n
    in r
    in div
    in files
    in div
    in div
    in t
    in elements__Container
    in Unknown
    in r
    in div
    in t
    in div
    in t
    in div
    in div
    in t
    in styled.div
    in div
    in t
    in elements__Container
    in t
    in n
    in r
    in n
    in r
    in t
    in t
    in div
    in t
    in elements__Content
    in n
    in t
    in withRouter(n)
    in div
    in t
    in elements__Container
    in Unknown
    in r
    in t
    in withRouter(r)
    in DragDropContext(withRouter(r))
    in t
    in t
    in l
    in t
```

</details>

**Comment by ridhamz** [comment] 2019-09-24 16:52
i have a problem

**Comment by lbogdan** [comment] 2020-06-16 12:33
Closing this as duplicate of #4374 .

**Closed by lbogdan** 2020-06-16 12:33 UTC
Labels: 💥 Crash Report
