### ISSUE TITLE
openweathermap API not returning data. 

### ISSUE THREAD

**Issue by pragyes31** [codesandbox/codesandbox-client#1916] opened 2019-05-15 15:36 UTC
# 🐛 bug report

## Description of the problem : 
OpenWeatherMap API is not returning the data using fetch, Axios or any other AJAX method.
## How has this issue affected you? What are you trying to accomplish?
Trying to get weather info using fetch. I am able to get the data when I run the same code on my local machine.

### Link to sandbox: [link]() (optional)
https://github.com/pragyes31/Weather-app-React

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | React
| Browser          | Firefox/Chrome
| Operating System | Linus/MacOS

**Comment by jmagrippis** [comment] 2019-05-16 16:19
Hello 👋 

It looks like this is your sandbox:
https://codesandbox.io/s/github/pragyes31/Weather-app-React

Uncommenting your commented lines seem to just work, the data is logged to the console, so I am unable to reproduce. Any thoughts?

**Comment by lbogdan** [comment] 2019-05-16 16:41
Hey @pragyes31 ,

That's because the OpenWeather API URL is `http`, not `https`, and the request is blocked because of browser security restrictions:

![image](https://user-images.githubusercontent.com/2083930/57871622-63c35180-7812-11e9-9c91-e91f8d0a0ec0.png)

Closing this, as it's expected behavior.

**Closed by lbogdan** 2019-05-16 16:41 UTC

**Comment by pragyes31** [comment] 2019-05-18 11:12
Hi @lbogdan,

Thanks for the clarification. I did not get this error in codesandbox and since it was working on my local machine,I thought of raising .the issue
