### ISSUE TITLE
Cannot find module 'xxx' or its corresponding type declarations.

### ISSUE THREAD

**Issue by Jannchie** [codesandbox/codesandbox-client#5502] opened 2021-02-20 19:22 UTC
# 🐛 bug report

## Preflight Checklist

- [x] I have read the
      [Contributing Guidelines](https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md)
      for this project.
- [x] I agree to follow the
      [Code of Conduct](https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md)
      that this project adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem

I'm using typescript, It basically works, but it doesn't load the type declarations.

> Cannot find module 'xxx' or its corresponding type declarations.

In the package.json file of the library, the location of the type declarations is defined. In the local environment (with vscode), it can correctly find the type definition, but not in the CodeSandBox.

## How has this issue affected you? What are you trying to accomplish?

I can use this library on CodeSandBox in a JavaScript environment, but I want to be able to take advantage of TypeScript's type inference capabilities.

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | Latest?
| Browser          | Chrome
| Operating System | Win 10

**Comment by 07akioni** [comment] 2021-02-22 02:02
I've met exactly the same issue. Reprod link https://codesandbox.io/s/boring-wescoff-uxd0z?file=/src/App.tsx

![image](https://user-images.githubusercontent.com/18677354/108647995-0551f980-74f5-11eb-8ff4-5332d9ff88c2.png)

**Comment by Jannchie** [comment] 2021-02-23 12:02
@07akioni 
I think I have fixed this problem by update my build config just now.
I just edited my `tsconfig.json`.

``` json
{
    "allowSyntheticDefaultImports": true, // It is likely that this option should be set to true.
    "resolveJsonModule": true
}
```

I still think it might be a bug of code sandbox. Because in local it works fine.

**Comment by gadicc** [comment] 2021-02-25 08:15
Hey @SaraVieira, looking at #5191 and #5452 you wanted a ping on similar issues.

3rd reproduction link at https://codesandbox.io/s/yahoo-finance2-312x2?file=/src/index.ts.  The code runs fine (and generates output in the browser window, clearly finding/using the module) but in the code editor it says `Cannot find module 'xxx' or its corresponding type declarations` and the types don't work.

**Comment by jmyrland** [comment] 2021-02-27 10:57
Same issue here, regarding the `easy-peasy` module: https://codesandbox.io/s/naughty-voice-62zy6?file=/src/App.tsx

**Comment by fantasticsoul** [comment] 2021-02-27 23:53
Same issue, link here: https://codesandbox.io/s/cra-template-concent-ts-2x347?file=/src/configs/runConcent.ts
it works in local vsc ide, but not work in codesandbox.

**Comment by anuoua** [comment] 2021-03-22 03:37
Same issue, https://codesandbox.io/s/immer-rdx-codesandbox-bug-vb890, it works in local vscode。

**Comment by lbogdan** [comment] 2021-05-28 12:33
I'm trying to reproduce this, below is the list of all sandboxes linked in the issue description and comments:

- [x] https://codesandbox.io/s/gdp-2020-g6gcu?file=/src/index.ts - provided by @Jannchie in the issue description
- [ ] https://codesandbox.io/s/boring-wescoff-uxd0z?file=/src/App.tsx - provided by @07akioni
- [x] https://codesandbox.io/s/yahoo-finance2-312x2?file=/src/index.ts - provided by @gadicc
- [x] https://codesandbox.io/s/naughty-voice-62zy6?file=/src/App.tsx - provided by @jmyrland
- [x] https://codesandbox.io/s/cra-template-concent-ts-2x347?file=/src/configs/runConcent.ts - provided by @fantasticsoul 
- [x] https://codesandbox.io/s/immer-rdx-codesandbox-bug-vb890?file=/src/index.tsx - provided by @anuoua

So the only one not working currently is the second one. We'll take a better look at this and update the issue.

**Comment by cefn** [comment] 2021-06-27 08:59
I believe I am also experiencing this issue and it is unsolved in today's version of codesandbox.io  

For example if I import the app from https://github.com/cefn/lauf/tree/b72aca2a5ffb649c867cd9d7991d1efad3c04d53/apps/counter it compiles from Typescript and runs fine. It is able to pick up types for `react` and `react-dom` but not for `@lauf/store` for v0.2.3.

![image](https://user-images.githubusercontent.com/159819/123538477-ff7f5580-d72c-11eb-9c74-e346b46b01e5.png)

However, the types for the package dependency `@lauf/store` at v0.2.3  are readable by VSCode as shown...

![image](https://user-images.githubusercontent.com/159819/123538544-5d13a200-d72d-11eb-9e3f-d7e427ea08df.png)

Could it be to do with the structure of the generated types files? As you can see they mirror the library file structure with a re-export. Perhaps VSCode can handle this structure but CodeSandbox can't interpret it? 

![image](https://user-images.githubusercontent.com/159819/123538706-13778700-d72e-11eb-9878-16ea85479a10.png)

**Comment by cefn** [comment] 2021-06-28 08:02
I can't explain what's changed but this error has gone away since I originally posted it. The counter application now correctly resolves typings for the `@lauf/store` and `@lauf/store-react` modules at 0.2.3. They were recently-published versions at the time, so I don't know if some worker needed to catch up a backlog of npm publishing. 

![image](https://user-images.githubusercontent.com/159819/123601423-91e82d80-d7ef-11eb-981f-8a758c58faa2.png)

**Comment by sbinlondon** [comment] 2021-07-02 11:04
@cefn That's good to hear!

@Jannchie @jmyrland @fantasticsoul @anuoua @07akioni your sandboxes seem to be working now too 🎉  I think like @lbogdan it takes a long time to parse and find the modules in some sandboxes? 🤔 

I'm interested in why @gadicc is still having the problem, seems to do with relative paths. @DeMoorJasper is this something you can look at or should I tag someone else?

**Comment by gadicc** [comment] 2021-07-02 11:12
@sbinlondon, thanks so much for checking in.  This was actually working previously, I should have reported back earlier.  Not sure when it broke again.  And actually the error was different now.  We recently switched over to an ESM module, maybe it had something to do with that.  Anyways, I just updated to the latest version of our package and everything is working again now flawlessly.  So thanks so much and have a great weekend!  (cc: @DeMoorJasper - nothing for you to do ;))

**Comment by DeMoorJasper** [comment] 2021-07-02 11:22
We've refactored the resolution logic quite a lot since this issue has been reported, so I'll assume this is fixed as it's no longer reproducible. Gonna close this for now, feel free to open this again (or open a new issue) if it happens again

**Closed by DeMoorJasper** 2021-07-02 11:22 UTC
Labels: Needs More Info, VS Code

**Comment by jamime** [comment] 2021-09-23 12:04
👋  @DeMoorJasper looks like there has been a regression. The examples above are failing again.

Here is an additional example: https://codesandbox.io/s/carbon-react-typescript-template-kq7zh

**Comment by anatoliygatt** [comment] 2022-02-16 18:08
I face the same issue with a newly published package. https://codesandbox.io/s/demo-for-anatoliygatt-heart-switch-cds5p, it works fine locally in both VSCode and WebStorm.

**Comment by shenghan97** [comment] 2022-04-18 04:55
Just found this package suffering from the same issue as well `@react-three/drei`, and it's only versions 9.3.6-9.4.3 are affected.

https://prod-packager-packages.codesandbox.io/v1/typings/@react-three/drei/9.4.3.json

**Comment by comp615** [comment] 2022-10-20 16:02
Also seeing this in our private repo. Works in VSCode, compiles and runs fine, but editor gives red lines everywhere. Potentially due to npm workspace usage? Not sure what else it could be

**Comment by lizy0329-biubiubiu** [comment] 2024-05-31 01:48
I think the team developer of codesendbox did not even use what they created.

Official Vue-ts tempalte

[demo](https://codesandbox.io/p/devbox/auto-import-3tr2wh?file=%2Fsrc%2FApp.vue%3A19%2C15)

![image](https://github.com/codesandbox/codesandbox-client/assets/103976180/b9ab5622-705f-4029-88a1-5acf91666a38)
