### ISSUE TITLE
changing value of a object, console log bug

### ISSUE THREAD

**Issue by xianjiezh** [codesandbox/codesandbox-client#1978] opened 2019-05-27 07:03 UTC
# 🐛 bug report

## changing value of a object, console log bug

this is my code 

```
let x = {
  a: 1
}

console.log(x.a)
console.log(x)

x.a = 2

console.log(x)

```
this is the console output
![image](https://user-images.githubusercontent.com/23073197/58401483-8d8d3b80-8090-11e9-903b-d6fcf569d40c.png)

**Comment by halitogunc** [comment] 2019-06-04 09:55
Codesandbox is using [console-feed](https://github.com/samdenty/console-feed) library to display console logs. See https://github.com/samdenty/console-feed/issues/23#issuecomment-496943400.

**Comment by lbogdan** [comment] 2019-10-24 11:28
Closing as duplicate of #1043 , please see the workaround there and subscribe to it for updates.

**Closed by lbogdan** 2019-10-24 11:28 UTC
Labels: bug?
