### ISSUE TITLE
BrowserFS writeFileSync error

### ISSUE THREAD

**Issue by hkngoc** [codesandbox/codesandbox-client#5893] opened 2021-06-10 02:34 UTC
I am using [xlsx](https://www.npmjs.com/package/xlsx) to export data.

It's call method writeFileSync of file system. When use codesandbox or sanpack-client, it throw error relate to browserfs of sandpack.

Live demo:
- [direct use xlsx in codesandbox](https://codesandbox.io/s/beautiful-dream-jd5fw)
- [use xlsx in sanpack-client over codesandbox](https://codesandbox.io/s/silly-keller-r0g1v)

In my local project, it work nomaly and open download dialog to save file.

Error log:
`
"Error
    at new n (https://0-0-6-sandpack.codesandbox.io/static/browserfs12/browserfs.min.js:7:48490)
    at n.rt.unlinkSync (https://0-0-6-sandpack.codesandbox.io/static/browserfs12/browserfs.min.js:7:80653)
    at n.rt.openSync (https://0-0-6-sandpack.codesandbox.io/static/browserfs12/browserfs.min.js:7:80408)
    at n.rt.writeFileSync (https://0-0-6-sandpack.codesandbox.io/static/browserfs12/browserfs.min.js:7:82779)
    at L.writeFileSync (https://0-0-6-sandpack.codesandbox.io/static/browserfs12/browserfs.min.js:7:61190)
    at Object.D.<computed>.P.<computed> [as writeFileSync] (https://0-0-6-sandpack.codesandbox.io/static/browserfs12/browserfs.min.js:7:70299)
    at write_dl (https://0-0-6-sandpack.codesandbox.io/node_modules/xlsx/xlsx.js:2696:112)
    at write_zip_type (https://0-0-6-sandpack.codesandbox.io/node_modules/xlsx/xlsx.js:21077:31)
    at writeSync (https://0-0-6-sandpack.codesandbox.io/node_modules/xlsx/xlsx.js:21165:22)
    at Object.writeFileSync (https://0-0-6-sandpack.codesandbox.io/node_modules/xlsx/xlsx.js:21188:9)
    at onClick (https://0-0-6-sandpack.codesandbox.io/src/App.js:32:19)
    at HTMLUnknownElement.callCallback (https://0-0-6-sandpack.codesandbox.io/node_modules/react-dom/cjs/react-dom.development.js:2746:18)
    at Object.invokeGuardedCallbackDev (https://0-0-6-sandpack.codesandbox.io/node_modules/react-dom/cjs/react-dom.development.js:2770:20)
    at invokeGuardedCallback (https://0-0-6-sandpack.codesandbox.io/node_modules/react-dom/cjs/react-dom.development.js:2804:35)
    at invokeGuardedCallbackAndCatchFirstError (https://0-0-6-sandpack.codesandbox.io/node_modules/react-dom/cjs/react-dom.development.js:2807:29)
    at executeDispatch (https://0-0-6-sandpack.codesandbox.io/node_modules/react-dom/cjs/react-dom.development.js:5339:7)
    at processDispatchQueueItemsInOrder (https://0-0-6-sandpack.codesandbox.io/node_modules/react-dom/cjs/react-dom.development.js:5359:11)
    at processDispatchQueue (https://0-0-6-sandpack.codesandbox.io/node_modules/react-dom/cjs/react-dom.development.js:5368:9)
    at dispatchEventsForPlugins (https://0-0-6-sandpack.codesandbox.io/node_modules/react-dom/cjs/react-dom.development.js:5376:7)
    at eval (https://0-0-6-sandpack.codesandbox.io/node_modules/react-dom/cjs/react-dom.development.js:5499:16)
    at batchedEventUpdates$1 (https://0-0-6-sandpack.codesandbox.io/node_modules/react-dom/cjs/react-dom.development.js:15075:16)
    at batchedEventUpdates (https://0-0-6-sandpack.codesandbox.io/node_modules/react-dom/cjs/react-dom.development.js:2626:16)
    at dispatchEventForPluginEventSystem (https://0-0-6-sandpack.codesandbox.io/node_modules/react-dom/cjs/react-dom.development.js:5498:7)
    at attemptToDispatchEvent (https://0-0-6-sandpack.codesandbox.io/node_modules/react-dom/cjs/react-dom.development.js:4051:7)
    at dispatchEvent (https://0-0-6-sandpack.codesandbox.io/node_modules/react-dom/cjs/react-dom.development.js:4006:23)
    at unstable_runWithPriority (https://0-0-6-sandpack.codesandbox.io/node_modules/scheduler/cjs/scheduler.development.js:468:12)
    at runWithPriority$1 (https://0-0-6-sandpack.codesandbox.io/node_modules/react-dom/cjs/react-dom.development.js:7417:14)
    at discreteUpdates$1 (https://0-0-6-sandpack.codesandbox.io/node_modules/react-dom/cjs/react-dom.development.js:15089:18)
    at discreteUpdates (https://0-0-6-sandpack.codesandbox.io/node_modules/react-dom/cjs/react-dom.development.js:2636:16)
    at dispatchDiscreteEvent (https://0-0-6-sandpack.codesandbox.io/node_modules/react-dom/cjs/react-dom.development.js:3987:7)"
`

![image](https://user-images.githubusercontent.com/6461137/121455806-494b0a80-c9cf-11eb-9cb0-319798895f42.png)

**Comment by alexnm** [comment] 2021-06-11 14:53
transferring to the main codesandbox repo, as the bundler work is done here

**Comment by DeMoorJasper** [comment] 2021-06-15 12:42
I cannot reproduce this anymore, can you check if this is working as expected?

**Comment by hkngoc** [comment] 2021-06-17 04:43
Hi @DeMoorJasper,

Can you access 2 demo above?
I just check againt and that error still occur in codesandbox and sanpack.

**Comment by DeMoorJasper** [comment] 2021-06-17 06:59
So I've just been able to reproduce it and it's due to us mocking the filesystem, there's quite a bit of work to refactor our code so we don't do so much magic to mock the Node environment.

So the current workaround is forcing the xlsx library to download the file instead of trying to save it to our mocked filesystem, you can see how that would work here: https://codesandbox.io/s/tender-poitras-xnfhi?file=/src/App.js

**Closed** 2021-06-17 07:02 UTC
Labels: 🎒 Bundler, 🐛 Bug
