### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by mariana077** [codesandbox/codesandbox-client#4096] opened 2020-05-07 13:35 UTC
<h1>💥 Crash Report</h1>

  <h2>What were you trying to accomplish when the crash occurred?</h2>

  > Please use this issue template to describe what you were doing when you encountered this crash. While we are able to fill in some details automatically, it's not always enough to reproduce!

  <h3>Link to sandbox: [link]() (optional)</h3>

  <h3>Crash Details</h3>

  <details>
  <summary>Environment</summary>

  | Browser |  Version  | Operating System | CodeSandbox Version |
  | ------- | --------- | ---------------- | ------------------- |
  | chrome | 81.0.4044 | OS X 10.14.6           | 1bfd7722f          |

  **Route:**
  https://codesandbox.io/s/quirky-agnesi-evvnh?file=/Rotas/produto.js

  </details>

  <details>
  <summary>Error Message</summary>

  ```bash
  NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
  Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at ys (https://codesandbox.io/static/js/common.3a10fb2cc.chunk.js?_sw-precache=14cffbc4480a523d1df061bde2f8e2df:1:1734535)
    at ms (https://codesandbox.io/static/js/common.3a10fb2cc.chunk.js?_sw-precache=14cffbc4480a523d1df061bde2f8e2df:1:1732536)
    at ys (https://codesandbox.io/static/js/common.3a10fb2cc.chunk.js?_sw-precache=14cffbc4480a523d1df061bde2f8e2df:1:1734272)
    at yl (https://codesandbox.io/static/js/common.3a10fb2cc.chunk.js?_sw-precache=14cffbc4480a523d1df061bde2f8e2df:1:1753537)
    at https://codesandbox.io/static/js/common.3a10fb2cc.chunk.js?_sw-precache=14cffbc4480a523d1df061bde2f8e2df:1:1775069
    at qo (https://codesandbox.io/static/js/common.3a10fb2cc.chunk.js?_sw-precache=14cffbc4480a523d1df061bde2f8e2df:1:1699442)
    at vl (https://codesandbox.io/static/js/common.3a10fb2cc.chunk.js?_sw-precache=14cffbc4480a523d1df061bde2f8e2df:1:1751422)
    at il (https://codesandbox.io/static/js/common.3a10fb2cc.chunk.js?_sw-precache=14cffbc4480a523d1df061bde2f8e2df:1:1741749)
    at https://codesandbox.io/static/js/common.3a10fb2cc.chunk.js?_sw-precache=14cffbc4480a523d1df061bde2f8e2df:1:1699733
    at https://codesandbox.io/static/js/common.3a10fb2cc.chunk.js?_sw-precache=14cffbc4480a523d1df061bde2f8e2df:1:1775069
    at qo (https://codesandbox.io/static/js/common.3a10fb2cc.chunk.js?_sw-precache=14cffbc4480a523d1df061bde2f8e2df:1:1699442)
    at Yo (https://codesandbox.io/static/js/common.3a10fb2cc.chunk.js?_sw-precache=14cffbc4480a523d1df061bde2f8e2df:1:1699678)
    at Jo (https://codesandbox.io/static/js/common.3a10fb2cc.chunk.js?_sw-precache=14cffbc4480a523d1df061bde2f8e2df:1:1699613)
    at ce (https://codesandbox.io/static/js/common.3a10fb2cc.chunk.js?_sw-precache=14cffbc4480a523d1df061bde2f8e2df:1:1769024)
    at On (https://codesandbox.io/static/js/common.3a10fb2cc.chunk.js?_sw-precache=14cffbc4480a523d1df061bde2f8e2df:1:1683571)
    at Bn (https://codesandbox.io/static/js/common.3a10fb2cc.chunk.js?_sw-precache=14cffbc4480a523d1df061bde2f8e2df:1:1684528)
    at Tn (https://codesandbox.io/static/js/common.3a10fb2cc.chunk.js?_sw-precache=14cffbc4480a523d1df061bde2f8e2df:1:1683816)
    at https://codesandbox.io/static/js/common.3a10fb2cc.chunk.js?_sw-precache=14cffbc4480a523d1df061bde2f8e2df:1:1775069
    at jn (https://codesandbox.io/static/js/common.3a10fb2cc.chunk.js?_sw-precache=14cffbc4480a523d1df061bde2f8e2df:1:1683292)
  
    in elements__Container
    in div
    in xi
    in div
    in t
    in Styled(styled.div)
    in li
    in t
    in Entry___StyledListAction
    in div
    in o
    in div
    in Unknown
    in DragSource(Component)
    in div
    in t
    in elements__EntryContainer
    in div
    in Unknown
    in DropTarget(Component)
    in div
    in cs
    in div
    in t
    in elements__Opener
    in div
    in Unknown
    in DropTarget(Component)
    in div
    in t
    in Styled(styled.div)
    in section
    in t
    in Styled(styled.div)
    in Unknown
    in t
    in Files___StyledCollapsible
    in js
    in hc
    in div
    in t
    in Unknown
    in div
    in t
    in elements__Container
    in Unknown
    in WithTheme(Component)
    in div
    in t
    in div
    in t
    in div
    in div
    in t
    in styled.div
    in div
    in t
    in elements__Container
    in t
    in Unknown
    in Unknown
    in Unknown
    in t
    in t
    in div
    in t
    in elements__Content
    in r
    in withRouter(r)
    in div
    in t
    in elements__Container
    in Unknown
    in withRouter()
    in t
    in Unknown
    in t
    in l
    in t
  ```

  </details>

**Comment by lbogdan** [comment] 2020-06-16 12:30
Closing this as duplicate of #4374 .

**Closed by lbogdan** 2020-06-16 12:30 UTC
Labels: 💥 Crash Report
