### ISSUE TITLE
Can't add new files: "Title cannot contain special characters"

### ISSUE THREAD

**Issue by p45mark** [codesandbox/codesandbox-client#3250] opened 2020-01-02 20:37 UTC
# 🐛 bug report

## Description of the problem
Unable to add new file with a file extension.

## How has this issue affected you? What are you trying to accomplish?
Just trying to add a new `.js` file

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |
| Browser          |
Chrome
| Operating System |
iOS

 I tried adding `Test.js` to the `src` directory and received the error "Title cannot have special characters." Also tried in Chrome incognito, same error shows

![image](https://user-images.githubusercontent.com/48729903/71691332-f1c95980-2d5b-11ea-9854-5b3473d0f225.png)

The error shows when I enter the period in the file name
![image](https://user-images.githubusercontent.com/48729903/71691377-16bdcc80-2d5c-11ea-8c48-45aa7c3a43d8.png)

**Comment by nerrad** [comment] 2020-01-02 21:23
I'm reproducing this with this client build version: `PROD-1577995418-15915ff60`

**Comment by SaraVieira** [comment] 2020-01-02 21:27
A PR just got merged that fixes this 

I'm sorry for the issues

**Comment by SaraVieira** [comment] 2020-01-02 21:42
Turns out this is actually a new issue, I just made a fix, pinging to get a deployment done

Sorry again

**Comment by SaraVieira** [comment] 2020-01-02 21:59
Just published a fix and it is live

**Closed by SaraVieira** 2020-01-02 21:59 UTC

**Comment by bytrangle** [comment] 2021-08-10 08:41
Hi @SaraVieira  If I name my file like this {MarkdownRemark.frontmatter__slug}.js (this is used in Gatsby to indicate that the file is a template for creating pages programmatically), i got the error above.
