### ISSUE TITLE
💥 Crash Report: <Please Add a Short Description of Crash Circumstances>

### ISSUE THREAD

**Issue by ilyasidorchik** [codesandbox/codesandbox-client#2582] opened 2019-09-29 11:36 UTC
<h1>💥 Crash Report</h1>

<h2>What were you trying to accomplish when the crash occurred?</h2>

> Please use this issue template to describe what you were doing when you encountered this crash. While we are able to fill in some details automatically, it's not always enough to reproduce!

<h3>Link to sandbox: [link]() (optional)</h3>

<h3>Crash Details</h3>

<details>
<summary>Environment</summary>

| Browser |  Version  | Operating System |
| ------- | --------- | ---------------- |
| safari | 12.1.2 | OS X 10.14.6           |

**Route:**
https://codesandbox.io/s/react-enzyme-form-test-2yqdr

</details>

<details>
<summary>Error Message</summary>

```bash
TypeError: undefined is not an object (evaluating 'e.files[d.path].tests')
https://codesandbox.io/static/js/default~app~embed.e9bc0e97.chunk.js:276:333912
produce@https://codesandbox.io/static/js/common.8fd6ed86.chunk.js:1:1098250
[native code]
Io@https://codesandbox.io/static/js/common.8fd6ed86.chunk.js:1:2041531
Po@https://codesandbox.io/static/js/common.8fd6ed86.chunk.js:1:2041790
ms@https://codesandbox.io/static/js/common.8fd6ed86.chunk.js:1:2061424
Fa@https://codesandbox.io/static/js/common.8fd6ed86.chunk.js:1:2081220
Na@https://codesandbox.io/static/js/common.8fd6ed86.chunk.js:1:2078240
Na@[native code]
Ra@https://codesandbox.io/static/js/common.8fd6ed86.chunk.js:1:2076799
Ra@[native code]
https://codesandbox.io/static/js/common.8fd6ed86.chunk.js:1:2038700
unstable_runWithPriority@https://codesandbox.io/static/js/common.8fd6ed86.chunk.js:1:2113546
po@https://codesandbox.io/static/js/common.8fd6ed86.chunk.js:1:2038647
ho@https://codesandbox.io/static/js/common.8fd6ed86.chunk.js:1:2038582
Oa@https://codesandbox.io/static/js/common.8fd6ed86.chunk.js:1:2075791
enqueueSetState@https://codesandbox.io/static/js/common.8fd6ed86.chunk.js:1:2043436
setState@https://codesandbox.io/static/js/common.8fd6ed86.chunk.js:1:2335613
https://codesandbox.io/static/js/default~app~embed.e9bc0e97.chunk.js:276:333844
https://codesandbox.io/static/js/default~app~embed~sandbox.a852bcbc.chunk.js:1:6473
forEach@[native code]
_@https://codesandbox.io/static/js/default~app~embed~sandbox.a852bcbc.chunk.js:1:6450
k@https://codesandbox.io/static/js/default~app~embed~sandbox.a852bcbc.chunk.js:1:6553

    in t
    in div
    in t
    in elements__ContentContainer
    in div
    in t
    in elements__Container
    in t
    in div
    in div
    in t
    in div
    in t
    in div
    in t
    in n
    in r
    in div
    in t
    in div
    in t
    in div
    in div
    in t
    in styled.div
    in div
    in t
    in elements__Container
    in t
    in n
    in r
    in n
    in r
    in t
    in t
    in div
    in t
    in elements__Content
    in n
    in t
    in withRouter(n)
    in div
    in t
    in elements__Container
    in Unknown
    in r
    in t
    in withRouter(r)
    in DragDropContext(withRouter(r))
    in t
    in t
    in l
    in t
```

</details>

**Comment by oskarabc** [comment] 2019-10-03 13:07
Hi @ilyasidorchik, i can't reproduce this issue, can you please try again or describe what happened? Thanks.

**Comment by lbogdan** [comment] 2020-06-16 12:11
Closing this, it should be fixed by https://github.com/codesandbox/codesandbox-client/commit/fc10d12cc8c8be2105ea6be397c4c70a54ca23bb .

**Closed by lbogdan** 2020-06-16 12:11 UTC
Labels: 💥 Crash Report
