### ISSUE TITLE
Zip export is empty folder of 0kb

### ISSUE THREAD

**Issue by painotpi** [codesandbox/codesandbox-client#3252] opened 2020-01-03 05:15 UTC
# 🐛 bug report

## Description of the problem
Created a basic vue.js sandbox, tried exporting it to zip for a local copy, the download is a 0kb file.

## How has this issue affected you? What are you trying to accomplish?
Not able to get a local copy of the code.

### Link to sandbox: [link]() (optional)
https://codesandbox.io/s/eloquent-rgb-7p3gb

### Your Environment

OS: Windows 10
Browser: Firefox

**Comment by garethx** [comment] 2020-01-24 12:07
Works on Chrome, but can reproduce in Firefox on Mac. See the following error on export:
Error: app.19d7f9dd.js:1:3358
Error received from starting extension host common.f8b8b2fa.chunk.js:1:124972
    _instrumentConsole https://codesandbox.io/static/js/common.f8b8b2fa.chunk.js:1
    _extensionHostProcessProxy https://codesandbox.io/public/vscode26/vs/editor/codesandbox.editor.main.js:1

**Comment by arthurdenner** [comment] 2020-05-06 03:50
@painotpi and @garethx, is this still happening to you? I couldn't reproduce on Firefox 75.0 (64-bit) on Mac 10.14.6. If it is, can you please add more info about your environment? If it isn't, can you please close the issue? Thanks!

**Comment by garethx** [comment] 2020-05-08 15:46
Working for me now, will close. Can re-open if we get other experiences.

**Closed by garethx** 2020-05-08 15:46 UTC
Labels: 🐛 Bug, 🦊 Firefox
