### ISSUE TITLE
Code Sandbox Crash

### ISSUE THREAD

**Issue by hoangIT1** [codesandbox/codesandbox-client#7010] opened 2022-10-10 14:36 UTC
<h1>💥 Crash Report</h1>

  <h2>What were you trying to accomplish when the crash occurred?</h2>

  > Please use this issue template to describe what you were doing when you encountered this crash. While we are able to fill in some details automatically, it's not always enough to reproduce!

  <h3>Link to sandbox: [link]() (optional)</h3>

  <h3>Crash Details</h3>

  <details>
  <summary>Environment</summary>

  | Browser |  Version  | Operating System | CodeSandbox Version |
  | ------- | --------- | ---------------- | ------------------- |
  | chrome | 105.0.0 | Windows 10           | 565c14b86          |

  **Route:**
  https://codesandbox.io/s/

  **Error Code:**
ee9dd1c7f2b44cb89d37eef90200aee3

  </details>

  <details>
  <summary>Error Message</summary>

  ```bash
  TypeError: Cannot read properties of null (reading 'name')
  TypeError: Cannot read properties of null (reading 'name')
    at kn (https://codesandbox.io/static/js/app.04f370e3b.js:9:404351)
    at ua (https://codesandbox.io/static/js/common.05c171ff1.chunk.js:1:1788854)
    at Ka (https://codesandbox.io/static/js/common.05c171ff1.chunk.js:1:1797119)
    at xs (https://codesandbox.io/static/js/common.05c171ff1.chunk.js:1:1835307)
    at ml (https://codesandbox.io/static/js/common.05c171ff1.chunk.js:1:1819693)
    at hl (https://codesandbox.io/static/js/common.05c171ff1.chunk.js:1:1819618)
    at il (https://codesandbox.io/static/js/common.05c171ff1.chunk.js:1:1816946)
    at https://codesandbox.io/static/js/common.05c171ff1.chunk.js:1:1775129
    at t.unstable_runWithPriority (https://codesandbox.io/static/js/common.05c171ff1.chunk.js:1:1850465)
    at qo (https://codesandbox.io/static/js/common.05c171ff1.chunk.js:1:1774838)
    at Xo (https://codesandbox.io/static/js/common.05c171ff1.chunk.js:1:1775074)
    at Yo (https://codesandbox.io/static/js/common.05c171ff1.chunk.js:1:1775009)
    at el (https://codesandbox.io/static/js/common.05c171ff1.chunk.js:1:1813732)
    at Sa (https://codesandbox.io/static/js/common.05c171ff1.chunk.js:1:1792527)
    at https://codesandbox.io/static/js/vendors~app.81e90e3c2.chunk.js:1:1007219
    at e.callback (https://codesandbox.io/static/js/vendors~app.81e90e3c2.chunk.js:1:1142068)
    at m.flush (https://codesandbox.io/static/js/vendors~app.81e90e3c2.chunk.js:1:1144955)
    at p.flush (https://codesandbox.io/static/js/vendors~app.81e90e3c2.chunk.js:1:1141122)
    at Object.cb (https://codesandbox.io/static/js/vendors~app.81e90e3c2.chunk.js:1:1014182)
    at e.emit (https://codesandbox.io/static/js/vendors~app.81e90e3c2.chunk.js:1:426117)
    at https://codesandbox.io/static/js/vendors~app.81e90e3c2.chunk.js:1:1018104
    at Proxy.<anonymous> (https://codesandbox.io/static/js/vendors~app.81e90e3c2.chunk.js:1:1016618)
    at https://codesandbox.io/static/js/app.04f370e3b.js:9:1005665
    at c (https://codesandbox.io/static/js/vendors~app~embed~sandbox~sandbox-startup.036d91db5.chunk.js:1:4333)
    at Generator._invoke (https://codesandbox.io/static/js/vendors~app~embed~sandbox~sandbox-startup.036d91db5.chunk.js:1:4086)
    at forEach.t.<computed> [as next] (https://codesandbox.io/static/js/vendors~app~embed~sandbox~sandbox-startup.036d91db5.chunk.js:1:4690)
    at e (https://codesandbox.io/static/js/vendors~app~embed~sandbox~sandbox-startup.036d91db5.chunk.js:1:206)
    at a (https://codesandbox.io/static/js/vendors~app~embed~sandbox~sandbox-startup.036d91db5.chunk.js:1:417)
    at https://codesandbox.io/static/js/vendors~app~embed~sandbox~sandbox-startup.036d91db5.chunk.js:1:476
    at new Promise (<anonymous>)
    at https://codesandbox.io/static/js/vendors~app~embed~sandbox~sandbox-startup.036d91db5.chunk.js:1:357
    at https://codesandbox.io/static/js/app.04f370e3b.js:9:1005855
    at https://codesandbox.io/static/js/vendors~app.81e90e3c2.chunk.js:1:1018054
    at Proxy.<anonymous> (https://codesandbox.io/static/js/vendors~app.81e90e3c2.chunk.js:1:1016618)
    at https://codesandbox.io/static/js/app.04f370e3b.js:9:1021888
    at c (https://codesandbox.io/static/js/vendors~app~embed~sandbox~sandbox-startup.036d91db5.chunk.js:1:4333)
    at Generator._invoke (https://codesandbox.io/static/js/vendors~app~embed~sandbox~sandbox-startup.036d91db5.chunk.js:1:4086)
    at forEach.t.<computed> [as next] (https://codesandbox.io/static/js/vendors~app~embed~sandbox~sandbox-startup.036d91db5.chunk.js:1:4690)
    at e (https://codesandbox.io/static/js/vendors~app~embed~sandbox~sandbox-startup.036d91db5.chunk.js:1:206)
    at a (https://codesandbox.io/static/js/vendors~app~embed~sandbox~sandbox-startup.036d91db5.chunk.js:1:417)
    at https://codesandbox.io/static/js/vendors~app~embed~sandbox~sandbox-startup.036d91db5.chunk.js:1:476
    at new Promise (<anonymous>)
    at https://codesandbox.io/static/js/vendors~app~embed~sandbox~sandbox-startup.036d91db5.chunk.js:1:357
    at https://codesandbox.io/static/js/app.04f370e3b.js:9:1022246
    at https://codesandbox.io/static/js/vendors~app.81e90e3c2.chunk.js:1:1018054
    at Proxy.<anonymous> (https://codesandbox.io/static/js/vendors~app.81e90e3c2.chunk.js:1:1016618)
    at https://codesandbox.io/static/js/app.04f370e3b.js:9:995912
    at c (https://codesandbox.io/static/js/vendors~app~embed~sandbox~sandbox-startup.036d91db5.chunk.js:1:4333)
    at Generator._invoke (https://codesandbox.io/static/js/vendors~app~embed~sandbox~sandbox-startup.036d91db5.chunk.js:1:4086)
    at forEach.t.<computed> [as next] (https://codesandbox.io/static/js/vendors~app~embed~sandbox~sandbox-startup.036d91db5.chunk.js:1:4690)
  
    in kn
    in div
    in Editor___StyledElement3
    in div
    in Styled(styled.div)
    in div
    in styled.div
    in div
    in styled.div
    in div
    in Editor___StyledElement
    in De
    in Unknown
    in div
    in div
    in styled.div
    in div
    in elements__Container
    in De
    in gy
    in Unknown
    in Unknown
    in component
    in t
    in t
    in div
    in elements__Content
    in n
    in withRouter(n)
    in div
    in elements__Container
    in Unknown
    in withRouter()
    in t
    in Unknown
    in De
    in c
    in t
  ```

  </details>

**Comment by tristandubbeld** [comment] 2022-10-10 14:46
Hey @hoangIT1, thanks for reporting! This looks like a duplicate of #7003 and #7005. We've just merged a potential fix for this with #7008. I'm closing this issue for now, but please let us know if the same error occurs again after the update is live.

**Closed by tristandubbeld** 2022-10-10 14:46 UTC
