### ISSUE TITLE
Unable to start my React sandbox today - Error message : "A sandbox error occurred, you can refresh the page to restart the container."

### ISSUE THREAD

**Issue by mbuyukkalender** [codesandbox/codesandbox-client#6737] opened 2022-06-06 14:08 UTC
# 🐛 bug report

## Preflight Checklist

- [x] I have read the [Contributing Guidelines][contributing] for this project.
- [x] I agree to follow the [Code of Conduct][code_of_conduct] that this project
      adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem
Since this morning, I can't start my sandbox which was working until the end of last week.

## How has this issue affected you? What are you trying to accomplish?
This is a sandbox I need to use for external labs with partners of our company

### To Reproduce
Access the sandbox and the error will be displayed automatically ...

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |              |
| Browser          |       Chrome Version 102.0.5005.61       |
| Operating System |   Mac Os X           |

[code_of_conduct]: https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md
[contributing]: https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md

**Comment by elliot-at-looker** [comment] 2022-06-06 19:31
+1

**Comment by jueungrace** [comment] 2022-06-06 20:54
Same here!

**Comment by ddenev** [comment] 2022-06-07 07:57
Same here with Quasar framework template

**Comment by mbuyukkalender** [comment] 2022-06-07 08:01
Tried with Chrome, Safari & Firefox but I still having this issue. 

I also created a new template from scratch yesterday night and this morning I'm facing the same issue ...

**Comment by gtala** [comment] 2022-06-07 10:53
Same here with Node.js server tempate

**Comment by ddenev** [comment] 2022-06-07 13:49
yes, I confirm it works now

thank you, @mbuyukkalender , for informing us and thanks to the codesandbox team for fixing the issue!

**Comment by gtala** [comment] 2022-06-07 13:51
Hi! Yes, it's fixed now!

**Comment by jueungrace** [comment] 2022-06-07 14:14
Yes, it's working for me now as well!

**Comment by elliot-at-looker** [comment] 2022-06-07 15:36
Seems to be working for me

**Comment by mohdashraf010897** [comment] 2022-06-08 05:03
I can reproduce it here https://codesandbox.io/s/github/appbaseio-apps/svelte-search-app/tree/main/steps/6-tuned-using-appbase-dashboard

#6260

**Comment by JamesACS** [comment] 2022-06-09 05:11
Thank you for confirming this has been fixed all!

**Closed by JamesACS** 2022-06-09 05:11 UTC

**Comment by tarcisioMateus** [comment] 2023-10-30 20:05
the same problem again 

Error: Error: (500) - URL: https://codesandbox.io/api/beta/sandboxes/branches/fcnyrg/instance
- DATA: {"error":"UNKNOWN_ERROR - ","code":"UNKNOWN_ERROR","message":null} 
- ERROR: Error: (500) 
UNKNOWN_ERROR - 

Version: 0.0.53
Environment: production
Event: Initial connect to Pitcher
State: ERROR
Branch: fcnyrg

**Comment by erenyildirimmm** [comment] 2024-02-01 12:18
same problem again for me :/

**Comment by hacthe-codelink** [comment] 2024-03-13 07:09
same problem again for today :/

**Comment by JamesACS** [comment] 2024-03-13 10:41
If you're experiencing this issue, please contact us using our support form: https://codesandbox.io/support

We can then troubleshoot any issues with you directly

**Comment by serranoarevalo** [comment] 2024-05-07 07:26
This keeps happening, now even if I own the sandbox I can't click 'Restart microVM'.

https://codesandbox.io/p/devbox/user-account-forked-4gqkh

![Screenshot 2024-05-07 at 16 26 28](https://github.com/codesandbox/codesandbox-client/assets/3612017/b7c3283a-06fe-47a2-ac2a-1c35e821d1d4)

**Comment by CompuIves** [comment] 2024-05-07 10:32
Pushed a fix for this as well! Should be resolved.
