### ISSUE TITLE
Just opened a new Vanilla JS sandbox 

### ISSUE THREAD

**Issue by dtassone** [codesandbox/codesandbox-client#4338] opened 2020-06-09 12:52 UTC
<h1>💥 Crash Report</h1>

  <h2>What were you trying to accomplish when the crash occurred?</h2>

  > Please use this issue template to describe what you were doing when you encountered this crash. While we are able to fill in some details automatically, it's not always enough to reproduce!

  <h3>Link to sandbox: [link]() (optional)</h3>

  <h3>Crash Details</h3>

  <details>
  <summary>Environment</summary>

  | Browser |  Version  | Operating System | CodeSandbox Version |
  | ------- | --------- | ---------------- | ------------------- |
  | chrome | 83.0.4103 | OS X 10.14.6           | 3688631f9          |

  **Route:**
  https://codesandbox.io/s/condescending-leftpad-hthq4

  </details>

  <details>
  <summary>Error Message</summary>

  ```bash
  TypeError: Cannot read property 'title' of undefined
  TypeError: Cannot read property 'title' of undefined
    at https://codesandbox.io/static/js/app.f4183700d.js?_sw-precache=f9f2af5761a8bf97ef86b6b817337a70:571:912516
    at ua (https://codesandbox.io/static/js/common.92a9f0a9c.chunk.js?_sw-precache=afd2ac8c20f60e4ac636224943a7c80c:1:1733563)
    at Ka (https://codesandbox.io/static/js/common.92a9f0a9c.chunk.js?_sw-precache=afd2ac8c20f60e4ac636224943a7c80c:1:1741828)
    at qa (https://codesandbox.io/static/js/common.92a9f0a9c.chunk.js?_sw-precache=afd2ac8c20f60e4ac636224943a7c80c:1:1741647)
    at Es (https://codesandbox.io/static/js/common.92a9f0a9c.chunk.js?_sw-precache=afd2ac8c20f60e4ac636224943a7c80c:1:1782301)
    at ml (https://codesandbox.io/static/js/common.92a9f0a9c.chunk.js?_sw-precache=afd2ac8c20f60e4ac636224943a7c80c:1:1764402)
    at hl (https://codesandbox.io/static/js/common.92a9f0a9c.chunk.js?_sw-precache=afd2ac8c20f60e4ac636224943a7c80c:1:1764327)
    at il (https://codesandbox.io/static/js/common.92a9f0a9c.chunk.js?_sw-precache=afd2ac8c20f60e4ac636224943a7c80c:1:1761655)
    at https://codesandbox.io/static/js/common.92a9f0a9c.chunk.js?_sw-precache=afd2ac8c20f60e4ac636224943a7c80c:1:1719838
    at https://codesandbox.io/static/js/common.92a9f0a9c.chunk.js?_sw-precache=afd2ac8c20f60e4ac636224943a7c80c:1:1795174
  
    in Unknown
    in DropTarget(Component)
    in div
    in dc
    in div
    in elements__Opener
    in div
    in Unknown
    in DropTarget(Component)
    in div
    in Styled(styled.div)
    in section
    in Styled(styled.div)
    in Unknown
    in Files___StyledCollapsible
    in Ic
    in yl
    in div
    in je
    in Unknown
    in div
    in elements__Container
    in Unknown
    in WithTheme(Component)
    in div
    in t
    in div
    in t
    in div
    in div
    in styled.div
    in div
    in elements__Container
    in je
    in Unknown
    in Unknown
    in Unknown
    in t
    in t
    in div
    in elements__Content
    in n
    in withRouter(n)
    in div
    in elements__Container
    in Unknown
    in withRouter()
    in t
    in Unknown
    in je
    in c
    in t
  ```

  </details>

**Comment by lbogdan** [comment] 2020-06-16 10:40
Closing this as a duplicate of #4366 .

**Closed by lbogdan** 2020-06-16 10:40 UTC
Labels: 💥 Crash Report
