### ISSUE TITLE
Internal Server Error with empty package.json

### ISSUE THREAD

**Issue by tkrotoff** [codesandbox/codesandbox-client#753] opened 2018-04-23 23:44 UTC
In this codesandbox: https://codesandbox.io/s/qk0zro1qm4, there is a package.json that when logged in I cannot delete ("Cannot delete package.json") nor edit and save ("Internal Server Error"). The package.json is empty.

When not logged, the empty package.json fails to be parsed: "Cannot read property 'parsed' of undefined"

**Comment by CompuIves** [comment] 2018-04-25 09:56
Good one! I added a commit that will fix the `Cannot read property` error. Will then check why the server is throwing.

**Comment by tkrotoff** [comment] 2018-05-14 21:32
@CompuIves any news on this?

**Comment by tkrotoff** [comment] 2018-07-03 20:15
Ping @CompuIves I've advertised this sandbox URL a lot :/

**Comment by arthurdenner** [comment] 2019-11-25 15:02
@tkrotoff, I see that you've updated the codesandbox. Can you confirm if this behavior is still happening? If so, could you provide a new sanbox? If it's not, can you close the issue, please?

**Comment by tkrotoff** [comment] 2019-11-29 11:55
Cannot do anything: AFK up to mid december

**Comment by SaraVieira** [comment] 2019-12-11 16:50
Hey!

I am doing some spring cleaning, and as you seem to not be available and we cannot reproduce I will close this issue, if it is stil happening when you are back please reopen with a sandbox URL

**Closed by SaraVieira** 2019-12-11 16:50 UTC
Labels: need more info, 🐛 Bug
