### ISSUE TITLE
Crash during drag-n-drop sandbox item from drafts to folder

### ISSUE THREAD

**Issue by bfunc** [codesandbox/codesandbox-client#4985] opened 2020-10-07 13:39 UTC
<h1>💥 Crash Report</h1>

  <h2>What were you trying to accomplish when the crash occurred?</h2>

  > Please use this issue template to describe what you were doing when you encountered this crash. While we are able to fill in some details automatically, it's not always enough to reproduce!

  <h3>Link to sandbox: [link]() (optional)</h3>

  <h3>Crash Details</h3>

  <details>
  <summary>Environment</summary>

  | Browser |  Version  | Operating System | CodeSandbox Version |
  | ------- | --------- | ---------------- | ------------------- |
  | chrome | 84.0.4147 | Windows 10           | 55385e381          |

  **Route:**
  https://codesandbox.io/dashboard/drafts?workspace=ebce30aa-ef8b-40d2-97b3-722ff5c14875

  

  </details>

  <details>
  <summary>Error Message</summary>

  ```bash
  TypeError: Cannot read property 'type' of undefined
  TypeError: Cannot read property 'type' of undefined
    at $s (https://codesandbox.io/static/js/app.5947ec3dc.js?_sw-precache=dbbe37f3a41b5ce4aa76116b5067aff6:272:240057)
    at ua (https://codesandbox.io/static/js/common.9250c8dbd.chunk.js?_sw-precache=e45ee64e378870e67e06b836344fbc51:1:1769943)
    at Ka (https://codesandbox.io/static/js/common.9250c8dbd.chunk.js?_sw-precache=e45ee64e378870e67e06b836344fbc51:1:1778208)
    at Es (https://codesandbox.io/static/js/common.9250c8dbd.chunk.js?_sw-precache=e45ee64e378870e67e06b836344fbc51:1:1816396)
    at ml (https://codesandbox.io/static/js/common.9250c8dbd.chunk.js?_sw-precache=e45ee64e378870e67e06b836344fbc51:1:1800782)
    at hl (https://codesandbox.io/static/js/common.9250c8dbd.chunk.js?_sw-precache=e45ee64e378870e67e06b836344fbc51:1:1800707)
    at il (https://codesandbox.io/static/js/common.9250c8dbd.chunk.js?_sw-precache=e45ee64e378870e67e06b836344fbc51:1:1798035)
    at https://codesandbox.io/static/js/common.9250c8dbd.chunk.js?_sw-precache=e45ee64e378870e67e06b836344fbc51:1:1756218
    at https://codesandbox.io/static/js/common.9250c8dbd.chunk.js?_sw-precache=e45ee64e378870e67e06b836344fbc51:1:1831554
    at qo (https://codesandbox.io/static/js/common.9250c8dbd.chunk.js?_sw-precache=e45ee64e378870e67e06b836344fbc51:1:1755927)
  
    in $s
    in nu
    in Vd
    in t
    in t
    in div
    in Content___StyledElement
    in Unknown
    in withRouter()
    in main
    in Dashboard___StyledElement2
    in div
    in Dashboard___StyledStack2
    in div
    in Dashboard___StyledStack
    in Unknown
    in De
    in Unknown
    in lp
    in t
    in t
    in div
    in elements__Content
    in n
    in withRouter(n)
    in div
    in elements__Container
    in Unknown
    in withRouter()
    in t
    in Unknown
    in De
    in c
    in t
  ```

  </details>

**Comment by sannek** [comment] 2020-10-12 09:07
Hi, thanks for your report. I've looked into this issue but I have been unable to reproduce it or figure out what might have caused your issue. I'm going to close it for now, but please reopen if this error occurs again. Thank you!

**Closed by sannek** 2020-10-12 09:07 UTC
