### ISSUE TITLE
Cloudflare cache has a long time -> old font is served

### ISSUE THREAD

**Issue by bebraw** [codesandbox/codesandbox-client#5444] opened 2021-02-03 16:36 UTC
# 🐛 bug report

## Preflight Checklist

- [x] I have read the
      [Contributing Guidelines](https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md)
      for this project.
- [x] I agree to follow the
      [Code of Conduct](https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md)
      that this project adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem

When I use https://codesandbox.io/s/lucid-lumiere-bk11m, it's still giving me an old version of MonoLisa font (fixed in https://github.com/codesandbox/codesandbox-client/pull/5337). I've included a screenshot from the network tab below:

<img width="469" alt="monolisa-cache" src="https://user-images.githubusercontent.com/166921/106777983-c80cf100-6645-11eb-8d52-68365cc10307.png">

As you can see, the cached version is from a date before the PR I linked to was merged and deployed and as a result it's serving me an older version of the font (possible to see from the "i" character).

## How has this issue affected you? What are you trying to accomplish?

Although the issue doesn't impact me directly, I believe it can impact users on low resolution displays where the fix would be useful.

I imagine the fix may have something to do with CloudFlare cache. I've solved similar issues by purging their cache carefully depending on the changes made.

### To Reproduce

This one is potentially difficult to reproduce as it depends on the machine cache contents and what's being served from CloudFlare.

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      | 03-02-2021 (from this date)
| Browser          | Chromium 88.0.4324.96
| Operating System | MacOS (Big Sur 11.2)

**Comment by CompuIves** [comment] 2021-02-04 11:22
Ohhhh yes this is a good point. When we update the font we need to rename it too, because we have some heavy caching on the resources.

**Comment by karlhorky** [comment] 2021-04-16 13:59
Is this resolved? Loading CodeSandbox in an incognito tab, I see the new version of the MonoLisa font with the proper `i` character.

**Comment by lbogdan** [comment] 2021-05-25 11:01
Closing, as it seems the Cloudflare cache updated in the meanwhile - I can confirm that what's served from `https://codesandbox.io/static/fonts/monolisa.css` is the same as `packages/app/static/fonts/monolisa.css` from `master`.

Be aware that Cloudflare applies some minifying on the CSS, so at a first glance the two seem different.

**Closed by lbogdan** 2021-05-25 11:01 UTC
