### ISSUE TITLE
Serious problem of Javascript' console.log

### ISSUE THREAD

**Issue by RickyWong33** [codesandbox/codesandbox-client#2920] opened 2019-10-24 11:24 UTC
# 🐛 bug report

## Description of the problem
run this javascript below
```
const A = {
   text: "hello"
};

console.log(A);
A.text = "";
```

## How has this issue affected you? What are you trying to accomplish?
The console should show `{text:'hello'}` but show `{text:''}`

### Link to sandbox: [link]() (optional)
https://codesandbox.io/s/static-hhehm?fontsize=14

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |current online product |
| Browser          |chrome 77 stable |
| Operating System |ubuntu 18.04|

**Comment by lbogdan** [comment] 2019-10-24 11:28
Closing as duplicate of #1043 , please see the workaround there and subscribe to it for updates.

**Closed by lbogdan** 2019-10-24 11:28 UTC
