### ISSUE TITLE
The content of master doesn't reflect what's actually in production: why?

### ISSUE THREAD

**Issue by nuragic** [codesandbox/codesandbox-client#2814] opened 2019-10-16 13:58 UTC
Hello!

I've found 2 issues today and I was planning to fix them, but it seems that they've been already fixed on master... cool, but then... the problem here is that those changes doesn't appear to be deployed in production! At least from me... I've checked by visiting the affected pages in incognito mode, so, not a cache problem on my side I guess.

Why is so? Is it the intended behaviour? How can external contributors help if the source code deployed is different from master? 😕 

Thanks!

**Comment by nuragic** [comment] 2019-10-16 14:03
First issue: wrong date format on https://codesandbox.io/patron
![Screen Shot 2019-10-16 at 10 10 41](https://user-images.githubusercontent.com/1586378/66926318-1bf95e00-f02e-11e9-9ca0-2ae6025f901a.png)

Second issue: empty section on https://codesandbox.io/legal/terms
![Screen Shot 2019-10-16 at 15 58 49](https://user-images.githubusercontent.com/1586378/66926328-2156a880-f02e-11e9-961f-4afc891b0ce9.png)

I've forked the repo and they seems to be both fixed on `master` 🤷‍♂

**Comment by lbogdan** [comment] 2019-10-18 13:06
Hey @nuragic ,

Thanks for the feedback! Currently this is intended behavior, yes, but we're working towers a workflow that will ensure that `master` is always deployed to production. You can see the latest deployed commit at the bottom of the sidebar, for example now it's

![image](https://user-images.githubusercontent.com/2083930/67096497-09635e00-f1c1-11e9-81f5-48454fac47e5.png)

which means the latest deployed commit is https://github.com/codesandbox/codesandbox-client/commit/a19d42751 .

Closing this, as there is no other actionable here. If you have further questions / suggestions / feedback, you can also find us on [Spectrum](https://spectrum.chat/codesandbox).

**Closed by lbogdan** 2019-10-18 13:06 UTC

**Comment by nuragic** [comment] 2019-10-18 15:17
Ookk gotcha thanks for clarifying!
