### ISSUE TITLE
Unresolving of absolute imports (typescript)

### ISSUE THREAD

**Issue by azinit** [codesandbox/codesandbox-client#6286] opened 2021-11-16 21:07 UTC
# 🐛 bug report

## Preflight Checklist

- [x] I have read the [Contributing Guidelines][contributing] for this project.
- [x] I agree to follow the [Code of Conduct][code_of_conduct] that this project
      adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want
      to file, without success.

## Description of the problem

At November 15 I had noticed, that my existing codesandbox projects had been crashed - because of unresolving of absolute imports
<img src=https://user-images.githubusercontent.com/42924400/142065496-ee93ad94-3365-4ec1-b65a-61e8c4d6b86d.png height=200 />

It's interesting that IDE autocomplete "sees" correct and actual imports by tsconfig, but at any time - build of project fails

Unfortunately, it is  not reproducible locally and looks like yet one codesandbox bug :(

> Error: `Could not find dependency: 'pages' relative to '/src/App.tsx'`
> <img src=https://user-images.githubusercontent.com/42924400/142063678-caa15060-6d82-43f0-a958-81025b4d79f9.png height=200 />

## How has this issue affected you? What are you trying to accomplish?

I've tried:
- To reproduce error on new React Typescript project (unfortunately I did)
- To reproduce error on new Typescript project
- To reproduce error locally
- To reproduce on another browser (Firefox)
- To fix error by import aliases (without success)
- To refresh pages (many times)
- To update tsconfig options
- To reinstall different versions of Typescript
- To search issue solution at codesandbox's issues ([one](https://github.com/codesandbox/codesandbox-client/issues/499), [two](https://github.com/codesandbox/codesandbox-client/issues/2276))

> Error: `Could not find module in path: '~/pages' relative to '/src/App.tsx'`
> <img src=https://user-images.githubusercontent.com/42924400/142063839-3678c70e-418e-4ec7-a2a8-2a61aaee299e.png height=200 />

### To Reproduce

1. Create any TypeScript project
2. Add baseUrl for absolute imports 
    OR 
    Add aliases for imports
3. Get error of unresolved imports

> As a [simple example](https://codesandbox.io/s/eloquent-napier-xpqn2?file=/src/index.ts)
> <img src=https://user-images.githubusercontent.com/42924400/142064310-387e0de5-da04-4034-8f47-9758c48f85ee.png height=200 />

### Your Environment

| Software         | Name/Version |
| ---------------- | ------------ |
| Сodesandbox      |  `f89852e88`            |
| Browser          |  Chrome 95.0.4638.69 (64 bit)  |
| Operating System | Windows 10              |

[code_of_conduct]: https://github.com/codesandbox/codesandbox-client/blob/master/CODE_OF_CONDUCT.md
[contributing]: https://github.com/codesandbox/codesandbox-client/blob/master/CONTRIBUTING.md

**Comment by rscheuermann** [comment] 2021-11-16 21:18
➕  Also experiencing this issue! Thanks @azinit for raising it

**Comment by CompuIves** [comment] 2021-11-17 10:45
Thanks for reporting this! We're going to look into it!

**Comment by DeMoorJasper** [comment] 2021-11-17 11:55
Had no clue we supported this so forgot to support it in the new resolver, will implement this as part of the `tsconfig` and `jsconfig` support we were planning anyway

Related to #807

**Comment by azinit** [comment] 2021-11-17 12:36
> Had no clue we supported this so forgot to support it in the new resolver, will implement this as part of the `tsconfig` and `jsconfig` support we were planning anyway

It's strange because it worked correctly  before (at least at October) 🤔

**Comment by DeMoorJasper** [comment] 2021-11-17 16:02
> > Had no clue we supported this so forgot to support it in the new resolver, will implement this as part of the `tsconfig` and `jsconfig` support we were planning anyway
> 
> It's strange because it worked correctly before (at least at October) 🤔

Yup, it's definitely a regression just forgot we supported it, so forgot to include it in the new resolver. Will implement this tomorrow

**Comment by omeraplak** [comment] 2021-11-18 11:16
> > > Had no clue we supported this so forgot to support it in the new resolver, will implement this as part of the `tsconfig` and `jsconfig` support we were planning anyway
> > 
> > 
> > It's strange because it worked correctly before (at least at October) 🤔
> 
> Yup, it's definitely a regression just forgot we supported it, so forgot to include it in the new resolver. Will implement this tomorrow, sorry about this

Our nearly 100 CodeSanboxes were corrupted. We are very happy to see that this will be fixed. 👍

**Closed** 2021-11-18 19:51 UTC

**Comment by DeMoorJasper** [comment] 2021-11-18 19:53
Just merged the fix that re-implements this logic, feel free to let me know (tag me) if any related issues pop up again.

Again sorry about this bug

**Comment by yairEO** [comment] 2021-11-30 07:39
Still happening

**Comment by DeMoorJasper** [comment] 2021-11-30 07:43
> Still happening 

Please add a way to reproduce this as the examples in here work

**Comment by yairEO** [comment] 2021-11-30 07:45
@DeMoorJasper - for example, this used to work, and did not change for a long time

https://codesandbox.io/s/ppkid

**Comment by DeMoorJasper** [comment] 2021-11-30 09:44
@yairEO Thanks, this is caused by our pre-packager not including the correct files, now that we support `exports` we sometimes use files that are not included in the pre-packaged bundle, which we should probably download from unpkg or jsdelivr but instead we error out...

We have a new version of the pre-packager planned, unfortunately that takes a bit of time so this won't be solved quickly, will log this internally and see if I can come up with a quicker fix sometime this week
